# Generated by Django 2.0.9 on 2020-03-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opal', '0037_auto_20181114_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICUHandover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqlserver_patientmasterfile_uniqueid', models.CharField(blank=True, max_length=255, null=True)),
                ('sqlserver_uniqueid', models.CharField(blank=True, max_length=255, null=True)),
                ('sqlserver_insert_datetime', models.CharField(blank=True, max_length=255, null=True)),
                ('sqlserver_lastupdated_datetime', models.CharField(blank=True, max_length=255, null=True)),
                ('database_version', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_mrn', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_surname', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_forename1', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_height', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_dob', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_weight', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('discharge_date', models.CharField(blank=True, max_length=255, null=True)),
                ('discharged', models.CharField(blank=True, max_length=255, null=True)),
                ('last_action_performed', models.CharField(blank=True, max_length=255, null=True)),
                ('referring_consultant', models.CharField(blank=True, max_length=255, null=True)),
                ('date_itu_admission', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_location_prior_to_admission', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_reason_itu_admission', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_history_present_illness', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_chronic_health_evaluation', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_past_medical_history', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_regular_medication', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_allergies', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_gcs_score', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_gcs_best_motor', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_gcs_eye_opening', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_gcs_best_verbal', models.CharField(blank=True, max_length=255, null=True)),
                ('dailyprogress_registrars_comments', models.CharField(blank=True, max_length=255, null=True)),
                ('dailyprogress_consultant_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('dailyprogress_nurses_handover_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('dailyprogress_critical_care_mdt', models.CharField(blank=True, max_length=255, null=True)),
                ('dailyprogress_main_diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('dailyprogress_results_of_investigations', models.CharField(blank=True, max_length=255, null=True)),
                ('dailyprogress_to_do_list', models.CharField(blank=True, max_length=255, null=True)),
                ('dailyprogress_therapy_input_ot', models.CharField(blank=True, max_length=255, null=True)),
                ('dailyprogress_therapy_input_pt', models.CharField(blank=True, max_length=255, null=True)),
                ('dailyprogress_organ_infection', models.CharField(blank=True, max_length=255, null=True)),
                ('dailyprogress_therapy_input_dietician', models.CharField(blank=True, max_length=255, null=True)),
                ('dailyprogress_therapy_input_slt', models.CharField(blank=True, max_length=255, null=True)),
                ('dailyprogress_organ_gi', models.CharField(blank=True, max_length=255, null=True)),
                ('dailyprogress_organ_cvs', models.CharField(blank=True, max_length=255, null=True)),
                ('dailyprogress_organ_renal', models.CharField(blank=True, max_length=255, null=True)),
                ('dailyprogress_organ_others', models.CharField(blank=True, max_length=255, null=True)),
                ('dailyprogress_organ_resp', models.CharField(blank=True, max_length=255, null=True)),
                ('dailyprogress_organ_cns', models.CharField(blank=True, max_length=255, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icuhandover', to='opal.Patient')),
            ],
        ),
    ]
