# Generated by Django 2.0.9 on 2020-03-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icuhandover',
            name='admission_allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='admission_chronic_health_evaluation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='admission_gcs_best_motor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='admission_gcs_best_verbal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='admission_gcs_eye_opening',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='admission_gcs_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='admission_history_present_illness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='admission_past_medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='admission_reason_itu_admission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='admission_regular_medication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='admission_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='dailyprogress_consultant_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='dailyprogress_critical_care_mdt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='dailyprogress_main_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='dailyprogress_nurses_handover_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='dailyprogress_organ_cns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='dailyprogress_organ_cvs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='dailyprogress_organ_gi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='dailyprogress_organ_infection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='dailyprogress_organ_others',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='dailyprogress_organ_renal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='dailyprogress_organ_resp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='dailyprogress_registrars_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='dailyprogress_results_of_investigations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='dailyprogress_therapy_input_dietician',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='dailyprogress_therapy_input_ot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='dailyprogress_therapy_input_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='dailyprogress_therapy_input_slt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='dailyprogress_to_do_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='database_version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='date_itu_admission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='discharge_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='discharged',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='last_action_performed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='patient_dob',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='patient_forename1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='patient_height',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='patient_location_prior_to_admission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='patient_mrn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='patient_surname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='patient_weight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='referring_consultant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='sqlserver_insert_datetime',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='sqlserver_lastupdated_datetime',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='sqlserver_patientmasterfile_uniqueid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuhandover',
            name='sqlserver_uniqueid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
