# Generated by Django 2.0.13 on 2020-05-28 13:48

from django.db import migrations
from plugins.icu import constants

def forwards(apps, schema_editor):
    Role = apps.get_model(
        'opal', 'Role'
    )
    Role.objects.create(name=constants.ICU_ROLE)


def backwards(apps, schema_editor):
    Role = apps.get_model(
        'opal', 'Role'
    )
    Role.objects.filter(name=constants.ICU_ROLE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0004_icuhandoverlocation'),
        ('opal',  '0037_auto_20181114_1445'),

    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
