# Generated by Django 2.0.13 on 2020-05-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0005_auto_create_roles_20200528_1348'),
    ]

    operations = [
    ]
