# Generated by Django 2.0.13 on 2020-05-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0006_auto_20200528_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICUWard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
