# Generated by Django 2.0.13 on 2020-05-28 13:57

from django.db import migrations

def forwards(apps, schema_editor):
    ICUWard = apps.get_model('icu', 'ICUWard')
    for wardname in ['West', 'South', 'East', 'SHDU']:
        ICUWard.objects.create(name=wardname)


def backwards(apps, schema_editor):
    ICUWard = apps.get_model('icu', 'ICUWard')
    ICUWard.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0007_icuward'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
