# Generated by Django 2.0.13 on 2020-05-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0008_auto_add_ward_data20200528_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='icuhandoverlocation',
            name='admitted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
