# Generated by Django 2.0.13 on 2021-10-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0010_auto_20210111_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ICUWard',
        ),
    ]
