# Generated by Django 2.0.9 on 2019-03-16 15:41
from django.db import migrations
from plugins.labtests import constants


def forwards(apps, schema_editor):
    Role = apps.get_model(
        'opal', 'Role'
    )
    Role.objects.create(name=constants.USE_NEW_API)


def backwards(apps, schema_editor):
    Role = apps.get_model(
        'opal', 'Role'
    )
    Role.objects.filter(name=constants.USE_NEW_API).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]

