# Generated by Django 2.0.13 on 2019-04-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0002_auto_20190316_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtest',
            options={'ordering': ['-datetime_ordered']},
        ),
    ]
