# Generated by Django 2.0.13 on 2020-01-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0003_auto_20190415_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='clinical_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
