# Generated by Django 2.0.13 on 2020-01-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0004_auto_20200121_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observation_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
