# Generated by Django 2.0.13 on 2021-05-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0005_auto_20200121_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='accession_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='encounter_consultant_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='encounter_location_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='encounter_location_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
