# Generated by Django 2.0.13 on 2020-10-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        ('labtests', '0005_auto_20200121_1442'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='labtest',
            index_together={('patient', 'test_name', 'test_code')},
        ),
    ]
