# Generated by Django 2.0.13 on 2021-06-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0006_auto_20210525_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='reported_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
