# Generated by Django 2.0.13 on 2021-10-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0008_observationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='lab_number',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
    ]
