# Generated by Django 2.2.16 on 2021-11-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0009_starredobservation'),
        ('labtests', '0009_auto_20211015_1244'),
    ]

    operations = [
    ]
