# Generated by Django 2.2.16 on 2022-01-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0009_auto_20211015_1244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObservationHistory',
        ),
    ]
