# Generated by Django 2.2.16 on 2025-12-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0010_labtest_department_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
