# Generated by Django 2.0.13 on 2020-04-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20200403_0828_create_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidReportingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tests_conducted', models.IntegerField()),
                ('tests_positive', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
        ),
    ]
