# Generated by Django 2.0.13 on 2020-04-22 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_covidreportingday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coviddashboard',
            name='negative',
        ),
        migrations.RemoveField(
            model_name='coviddashboard',
            name='patients_tested',
        ),
        migrations.RemoveField(
            model_name='coviddashboard',
            name='positive',
        ),
        migrations.AddField(
            model_name='coviddashboard',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 12, 48, 53, 363677)),
            preserve_default=False,
        ),
    ]
