# Generated by Django 2.0.13 on 2020-04-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_auto_20200429_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidreportingday',
            name='first_resulted',
            field=models.IntegerField(default=0, help_text='Number of patients with resulted tests for COVID 19'),
            preserve_default=False,
        ),
    ]
