# Generated by Django 2.0.13 on 2020-04-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0007_covidreportingday_first_resulted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidreportingday',
            old_name='lab_confirmed',
            new_name='patients_positive',
        ),
        migrations.RenameField(
            model_name='covidreportingday',
            old_name='first_resulted',
            new_name='patients_resulted',
        ),
    ]
