# Generated by Django 2.0.13 on 2020-04-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0008_auto_20200429_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidreportingday',
            old_name='death',
            new_name='deaths',
        ),
    ]
