# Generated by Django 2.0.13 on 2020-05-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0010_covidadmission_covidcomorbidities_covidct_covidcxr_covidfollowupcall_covidsmokinghistory_covidsocial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ituadmission',
            options={'verbose_name': 'ITU Admission'},
        ),
        migrations.AlterField(
            model_name='covidadmission',
            name='fi02',
            field=models.CharField(blank=True, help_text='Oxygen flow rate if on nasal specs or non-fixed delivery mask', max_length=255, null=True, verbose_name='FiO2'),
        ),
        migrations.AlterField(
            model_name='covidcomorbidities',
            name='hiv',
            field=models.NullBooleanField(verbose_name='HIV'),
        ),
        migrations.AlterField(
            model_name='covidct',
            name='pe',
            field=models.NullBooleanField(verbose_name='Pulmonary Embolism'),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='follow_up_outcome',
            field=models.CharField(blank=True, choices=[('Discharge', 'Discharge'), ('Repeat CXR and F/U Call', 'Repeat CXR and F/U Call'), ('CT Chest', 'CT Chest'), ('PFTs', 'PFTs'), ('Resp OPD', 'Resp OPD'), ('Refer back to Primary Care', 'Refer back to Primary Care')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ituadmission',
            name='apache_score_on_arrival',
            field=models.CharField(blank=True, max_length=244, null=True, verbose_name='APACHE II score on ITU arrival'),
        ),
    ]
