# Generated by Django 2.0.13 on 2020-05-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0011_auto_20200518_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidadmission',
            name='temperature',
            field=models.FloatField(blank=True, help_text='oC', null=True),
        ),
    ]
