# Generated by Django 2.0.13 on 2020-05-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0012_auto_20200520_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='recontact',
            field=models.NullBooleanField(verbose_name='Would you be willing to be contacted again to take part in research?'),
        ),
    ]
