# Generated by Django 2.0.13 on 2020-05-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0013_auto_20200521_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='call_satisfaction',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True, verbose_name='Patient satisfied with call?'),
        ),
        migrations.AlterField(
            model_name='lungfunctiontest',
            name='lf_dlco',
            field=models.CharField(blank=True, max_length=244, null=True, verbose_name='Lung Function DLCO %'),
        ),
    ]
