# Generated by Django 2.0.13 on 2020-05-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0014_auto_20200521_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidadmission',
            name='covid_code',
        ),
        migrations.AlterField(
            model_name='covidadmission',
            name='max_fio2_nc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Max FiO2 if Nasal Cannula'),
        ),
        migrations.AlterField(
            model_name='covidadmission',
            name='max_fio2_non_nc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Max FiO2 non Nasal Cannula'),
        ),
    ]
