# Generated by Django 2.0.13 on 2020-05-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0015_auto_20200521_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidadmission',
            name='days_on_ippv',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number Of Days On IPPV'),
        ),
    ]
