# Generated by Django 2.0.13 on 2020-05-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0016_covidadmission_days_on_ippv'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidct',
            name='thrombosis',
            field=models.NullBooleanField(),
        ),
    ]
