# Generated by Django 2.0.13 on 2020-05-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0017_covidct_thrombosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidadmission',
            name='maximum_resp_support',
            field=models.CharField(blank=True, choices=[('No support', 'No support'), ('O2', 'O2'), ('CPAP', 'CPAP'), ('NIV', 'NIV'), ('IV', 'IV')], max_length=200, null=True),
        ),
    ]
