# Generated by Django 2.0.13 on 2020-05-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0018_auto_20200522_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidadmission',
            name='chills',
            field=models.NullBooleanField(verbose_name='Chills or sweats'),
        ),
        migrations.AlterField(
            model_name='covidadmission',
            name='anosmia',
            field=models.NullBooleanField(verbose_name='Loss of smell'),
        ),
        migrations.AlterField(
            model_name='covidadmission',
            name='predominant_symptom',
            field=models.CharField(blank=True, choices=[('Cough', 'Cough'), ('Shortness of breath', 'Shortness of breath'), ('Sore throat', 'Sore throat'), ('Blocked or runny nose', 'Blocked or runny nose'), ('Fever', 'Fever'), ('Myalgia', 'Myalgia'), ('Headache', 'Headache'), ('Anorexia', 'Anorexia'), ('Diarrhoea', 'Diarrhoea'), ('Abdominal pain', 'Abdominal pain'), ('Chest pain/tightness', 'Chest pain/tightness'), ('Confusion/fuzzy head', 'Confusion/fuzzy head'), ('Periperal oedema', 'Periperal oedema'), ('Focal weakness', 'Focal weakness')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='covidadmission',
            name='rhinitis',
            field=models.NullBooleanField(verbose_name='Blocked or runny nose'),
        ),
    ]
