# Generated by Django 2.0.13 on 2020-05-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0019_auto_20200527_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidfollowupcall',
            name='chills',
            field=models.NullBooleanField(verbose_name='Chills or sweats'),
        ),
    ]
