# Generated by Django 2.0.13 on 2020-05-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0020_covidfollowupcall_chills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='abdominal_pain',
            field=models.NullBooleanField(verbose_name='Abdominal pain'),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='loss_of_taste',
            field=models.NullBooleanField(verbose_name='Loss of taste'),
        ),
    ]
