# Generated by Django 2.0.13 on 2020-05-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0022_auto_20200531_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='back_to_normal',
            field=models.NullBooleanField(verbose_name='Do you feel back to normal?'),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='back_to_work',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True, verbose_name='If working, are you back to work?'),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='baseline_health_proximity',
            field=models.IntegerField(blank=True, null=True, verbose_name='How close to 100% of usual health do you feel?'),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='follow_up_outcome',
            field=models.CharField(blank=True, choices=[('Unreachable', 'Unreachable'), ('Unable to complete', 'Unable to complete'), ('Further Follow Up', 'Further Follow Up'), ('Discharge', 'Discharge')], max_length=50, null=True),
        ),
    ]
