# Generated by Django 2.0.13 on 2020-06-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0024_covidreportcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidfollowupcall',
            name='smoking_status',
        ),
        migrations.AddField(
            model_name='covidsmokinghistory',
            name='followup_status',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Ex-smoker', 'Ex-smoker'), ('Current', 'Current'), ('Unknown', 'Unknown')], max_length=200, null=True, verbose_name='Smoking staus at follow up'),
        ),
    ]
