# Generated by Django 2.0.13 on 2020-06-10 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0026_auto_20200610_0534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='covidfollowupactions',
            options={'verbose_name': 'Covid Follow Up Actions'},
        ),
    ]
