# Generated by Django 2.0.13 on 2020-07-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0029_auto_20200610_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='current_et',
            field=models.CharField(blank=True, help_text='Metres', max_length=50, null=True, verbose_name='Current ET (metres)'),
        ),
    ]
