# Generated by Django 2.0.13 on 2020-07-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0030_auto_20200714_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='depressed',
            field=models.CharField(blank=True, choices=[('0', '(0) Not At All'), ('1', '(1) Several days'), ('2', '(2) More than half the days'), ('3', '(3) Nearly every day')], max_length=50, null=True, verbose_name='Feeling down, depressed or hopeless'),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='interest',
            field=models.CharField(blank=True, choices=[('0', '(0) Not At All'), ('1', '(1) Several days'), ('2', '(2) More than half the days'), ('3', '(3) Nearly every day')], max_length=50, null=True, verbose_name='Little interest or pleasure in doing things'),
        ),
    ]
