# Generated by Django 2.0.13 on 2020-07-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0032_auto_20200714_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='current_breathlessness',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='current_cough',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='current_fatigue',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='current_sleep_quality',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='max_breathlessness',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='max_cough',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='max_fatigue',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='max_sleep_quality',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=5, null=True),
        ),
    ]
