# Generated by Django 2.0.13 on 2020-07-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0033_auto_20200714_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidfollowupcall',
            name='gp_copy',
            field=models.TextField(blank=True, null=True, verbose_name='Copy for clinic letter'),
        ),
    ]
