# Generated by Django 2.0.13 on 2020-07-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0034_covidfollowupcall_gp_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidfollowupcall',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
