# Generated by Django 2.0.13 on 2020-07-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0035_covidfollowupcall_ethnicity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidadmission',
            name='height',
        ),
        migrations.RemoveField(
            model_name='covidadmission',
            name='weight',
        ),
        migrations.AddField(
            model_name='covidfollowupcall',
            name='height',
            field=models.CharField(blank=True, help_text='m', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='covidfollowupcall',
            name='weight',
            field=models.CharField(blank=True, help_text='kg', max_length=20, null=True),
        ),
    ]
