# Generated by Django 2.0.13 on 2020-07-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0036_auto_20200727_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidfollowupcall',
            name='diabetic',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True, verbose_name=' (If diabetic), were you started on insulin during your admission? If so, do you have support or follow-up from hospital diabetic team/community team/your GP?'),
        ),
        migrations.AddField(
            model_name='covidfollowupcall',
            name='haem_anticoag',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True, verbose_name='(If patient had PE/DVT), have you been offered an appointment with the haematology team/anticoagulation clinic?'),
        ),
        migrations.AddField(
            model_name='covidfollowupcall',
            name='online_information',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True, verbose_name='Do you want any online information on post-COVID support?'),
        ),
        migrations.AddField(
            model_name='covidfollowupcall',
            name='pulse_oximeter',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True, verbose_name='If A&E patient, were you discharged with a pulse oximeter?'),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='call_satisfaction',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True, verbose_name='Did you find this call useful?'),
        ),
    ]
