# Generated by Django 2.0.13 on 2020-07-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0037_auto_20200727_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidct',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='covidct',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='covidct',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='covidcxr',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='covidcxr',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='covidcxr',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='covidsmokinghistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='covidsmokinghistory',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='covidsmokinghistory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='covidsocialhistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='covidsocialhistory',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='covidsocialhistory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='covidtrialenrollment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='covidtrialenrollment',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='covidtrialenrollment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='ituadmission',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ituadmission',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='ituadmission',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='covidfollowupcall',
            name='admission_status',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Ex-smoker', 'Ex-smoker'), ('Current', 'Current'), ('Unknown', 'Unknown')], max_length=200, null=True, verbose_name='Smoking Status On Admission'),
        ),
        migrations.AddField(
            model_name='covidfollowupcall',
            name='carers',
            field=models.CharField(blank=True, choices=[('OD', 'OD'), ('BD', 'BD'), ('TDS', 'TDS'), ('QDS', 'QDS')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='covidfollowupcall',
            name='followup_status',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Ex-smoker', 'Ex-smoker'), ('Current', 'Current'), ('Unknown', 'Unknown')], max_length=200, null=True, verbose_name='Smoking staus at follow up'),
        ),
        migrations.AddField(
            model_name='covidfollowupcall',
            name='other_drugs',
            field=models.NullBooleanField(verbose_name='Other Drugs Smoked'),
        ),
        migrations.AddField(
            model_name='covidfollowupcall',
            name='pack_year_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='covidfollowupcall',
            name='shielding_status',
            field=models.CharField(blank=True, choices=[('Not', 'Not'), ('Voluntary Shielding', 'Voluntary Shielding'), ('Extremely Vulnerable', 'Extremely Vulnerable'), ('Letter Issued by HCP', 'Letter Issued by HCP')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='covidfollowupcall',
            name='social_circumstances',
            field=models.CharField(blank=True, choices=[('Independent', 'Independent'), ('Family help', 'Family help'), ('Carers', 'Carers'), ('NH/RH', 'NH/RH')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='covidfollowupcall',
            name='vape',
            field=models.NullBooleanField(verbose_name='Vape Smoked'),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='diabetic',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True, verbose_name='(If diabetic), were you started on insulin during your admission? If so, do you have support or follow-up from hospital diabetic team/community team/your GP?'),
        ),
        migrations.DeleteModel(
            name='CovidCT',
        ),
        migrations.DeleteModel(
            name='CovidCXR',
        ),
        migrations.DeleteModel(
            name='CovidSmokingHistory',
        ),
        migrations.DeleteModel(
            name='CovidSocialHistory',
        ),
        migrations.DeleteModel(
            name='CovidTrialEnrollment',
        ),
        migrations.DeleteModel(
            name='ITUAdmission',
        ),
    ]
