# Generated by Django 2.0.13 on 2020-07-27 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covid', '0038_auto_20200727_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidFollowUpCallFollowUpCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('when', models.DateTimeField(blank=True, null=True)),
                ('clinician', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, choices=[('Consultant', 'Consultant'), ('Registrar', 'Registrar'), ('Associate Specialist', 'Associate Specialist'), ('Other', 'Other')], max_length=255, null=True)),
                ('incomplete_reason', models.TextField(blank=True, null=True)),
                ('bloods', models.NullBooleanField()),
                ('imaging', models.NullBooleanField()),
                ('symptoms', models.NullBooleanField()),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('outcome', models.CharField(blank=True, max_length=255, null=True)),
                ('gp_copy', models.TextField(blank=True, null=True, verbose_name='Copy for clinic letter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_covid_covidfollowupcallfollowupcall_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_covid_covidfollowupcallfollowupcall_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
