# Generated by Django 2.0.13 on 2020-07-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0039_covidfollowupcallfollowupcall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidfollowupcallfollowupcall',
            name='incomplete_reason',
        ),
    ]
