# Generated by Django 2.0.13 on 2020-07-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0040_remove_covidfollowupcallfollowupcall_incomplete_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidfollowupcallfollowupcall',
            old_name='gp_copy',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='covidfollowupcallfollowupcall',
            name='outcome',
        ),
    ]
