# Generated by Django 2.0.13 on 2020-07-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0041_auto_20200727_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='height',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Height (m)'),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='covidfollowupcallfollowupcall',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Call Details'),
        ),
    ]
