# Generated by Django 2.0.13 on 2020-07-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0042_auto_20200728_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='covidfollowupcallfollowupcall',
            options={'verbose_name': 'Covid Follow Up Subsequent Call'},
        ),
    ]
