# Generated by Django 2.0.13 on 2020-08-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0043_auto_20200728_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='admission_status',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Ex-smoker', 'Ex-smoker'), ('Current', 'Current'), ('Unknown', 'Unknown')], max_length=200, null=True, verbose_name='Smoking status on admission'),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='followup_status',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Ex-smoker', 'Ex-smoker'), ('Current', 'Current'), ('Unknown', 'Unknown')], max_length=200, null=True, verbose_name='Smoking status at follow up'),
        ),
    ]
