# Generated by Django 2.0.13 on 2020-08-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0043_auto_20200728_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='call_satisfaction',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not sure', 'Not sure')], max_length=20, null=True, verbose_name='Did you find this call useful?'),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='carers',
            field=models.CharField(blank=True, choices=[('OD', 'OD'), ('BD', 'BD'), ('TDS', 'TDS'), ('QDS', 'QDS'), ('24h', '24h')], max_length=200, null=True),
        ),
    ]
