# Generated by Django 2.0.13 on 2020-08-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0045_auto_20200819_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidfollowupcall',
            name='ethnicity_code',
            field=models.CharField(blank=True, choices=[('BrC', 'BrC'), ('OC', 'OC'), ('BrA', 'BrA'), ('OA', 'OA'), ('BB', 'BB'), ('BO', 'BO'), ('O', 'O')], max_length=200, null=True),
        ),
    ]
