# Generated by Django 2.0.13 on 2020-10-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0046_covidfollowupcall_ethnicity_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='ethnicity_code',
            field=models.CharField(blank=True, choices=[('White', 'White'), ('Black', 'Black'), ('Asian', 'Asian'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
