# Generated by Django 2.0.13 on 2021-01-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0050_auto_20201124_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='mrc_dyspnoea_scale',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('N/A', 'N/A')], max_length=50, null=True, verbose_name='MRC Dyspnoea Scale'),
        ),
        migrations.AlterField(
            model_name='covidsixmonthfollowup',
            name='mrc_dyspnoea_scale',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('N/A', 'N/A')], max_length=50, null=True, verbose_name='MRC Dyspnoea Scale'),
        ),
    ]
