# Generated by Django 2.0.13 on 2021-01-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0050_auto_20201124_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='breathlessness_trend',
            field=models.CharField(blank=True, choices=[('Same', 'Same'), ('Better', 'Better'), ('Worse', 'Worse'), ('Back to baseline', 'Back to baseline')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='cough_trend',
            field=models.CharField(blank=True, choices=[('Same', 'Same'), ('Better', 'Better'), ('Worse', 'Worse'), ('Back to baseline', 'Back to baseline')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='fatigue_trend',
            field=models.CharField(blank=True, choices=[('Same', 'Same'), ('Better', 'Better'), ('Worse', 'Worse'), ('Back to baseline', 'Back to baseline')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='covidfollowupcall',
            name='sleep_quality_trend',
            field=models.CharField(blank=True, choices=[('Same', 'Same'), ('Better', 'Better'), ('Worse', 'Worse'), ('Back to baseline', 'Back to baseline')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='covidsixmonthfollowup',
            name='breathlessness_trend',
            field=models.CharField(blank=True, choices=[('Same', 'Same'), ('Better', 'Better'), ('Worse', 'Worse'), ('Back to baseline', 'Back to baseline')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='covidsixmonthfollowup',
            name='cough_trend',
            field=models.CharField(blank=True, choices=[('Same', 'Same'), ('Better', 'Better'), ('Worse', 'Worse'), ('Back to baseline', 'Back to baseline')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='covidsixmonthfollowup',
            name='fatigue_trend',
            field=models.CharField(blank=True, choices=[('Same', 'Same'), ('Better', 'Better'), ('Worse', 'Worse'), ('Back to baseline', 'Back to baseline')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='covidsixmonthfollowup',
            name='sleep_quality_trend',
            field=models.CharField(blank=True, choices=[('Same', 'Same'), ('Better', 'Better'), ('Worse', 'Worse'), ('Back to baseline', 'Back to baseline')], max_length=40, null=True),
        ),
    ]
