# Generated by Django 2.0.13 on 2021-01-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0054_auto_20210105_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidfollowupcall',
            name='hospital_site',
            field=models.CharField(blank=True, choices=[('RFH', 'RFH'), ('Barnet', 'Barnet')], max_length=255, null=True),
        ),
    ]
