# Generated by Django 2.0.13 on 2021-03-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0057_auto_20210205_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidPositivesAgeDateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('ages_0_24', models.IntegerField(default=0, verbose_name='0 - 24')),
                ('ages_25_34', models.IntegerField(default=0, verbose_name='25 - 34')),
                ('ages_35_49', models.IntegerField(default=0, verbose_name='35 - 49')),
                ('ages_50_69', models.IntegerField(default=0, verbose_name='50 - 69')),
                ('ages_70_plus', models.IntegerField(default=0, verbose_name='70+')),
            ],
        ),
    ]
