# Generated by Django 2.2.16 on 2021-12-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0058_covidfollowupcallfollowupcall_echo_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidfollowupcall',
            name='sent_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='covidfollowupcallfollowupcall',
            name='sent_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='covidsixmonthfollowup',
            name='sent_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
