# Generated by Django 2.0.13 on 2021-03-31 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0058_covidpositivesagedaterange'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidpositivesagedaterange',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
