# Generated by Django 2.0.13 on 2021-04-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0059_covidpositivesagedaterange_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidpatient',
            name='barnet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='covidpatient',
            name='rfh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='covidpositivesagedaterange',
            name='location',
            field=models.CharField(choices=[(['ALL', 'BARNET', 'RFH'], ['ALL', 'BARNET', 'RFH'])], default='ALL', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='covidreportingday',
            name='location',
            field=models.CharField(choices=[(['ALL', 'BARNET', 'RFH'], ['ALL', 'BARNET', 'RFH'])], default='ALL', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='covidreportingday',
            name='deaths',
            field=models.IntegerField(default=0, help_text='Number of patients who died on this day having tested positive for COVID 19'),
        ),
        migrations.AlterField(
            model_name='covidreportingday',
            name='patients_positive',
            field=models.IntegerField(default=0, help_text='Number of patients who first had a COVID 19 test positve result on this day'),
        ),
        migrations.AlterField(
            model_name='covidreportingday',
            name='patients_resulted',
            field=models.IntegerField(default=0, help_text='Number of patients with resulted tests for COVID 19'),
        ),
        migrations.AlterField(
            model_name='covidreportingday',
            name='tests_ordered',
            field=models.IntegerField(default=0, help_text='Number of COVID 19 tests ordered on this day'),
        ),
        migrations.AlterField(
            model_name='covidreportingday',
            name='tests_resulted',
            field=models.IntegerField(default=0, help_text='Number of COVID 19 tests reported on this day'),
        ),
    ]
