# Generated by Django 2.0.13 on 2021-04-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0059_covidpositivesagedaterange_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidpatient',
            name='barnet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='covidpatient',
            name='location',
            field=models.CharField(choices=[(['ALL', 'BARNET', 'RFH'], ['ALL', 'BARNET', 'RFH'])], default='ALL', max_length=257),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='covidpatient',
            name='rfh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='covidpositivesagedaterange',
            name='location',
            field=models.CharField(choices=[(['ALL', 'BARNET', 'RFH'], ['ALL', 'BARNET', 'RFH'])], default='ALL', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='covidreportingday',
            name='location',
            field=models.CharField(choices=[(['ALL', 'BARNET', 'RFH'], ['ALL', 'BARNET', 'RFH'])], default='ALL', max_length=257),
            preserve_default=False,
        ),
    ]
