# Generated by Django 2.2.16 on 2022-01-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0059_auto_20211210_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidfollowupcall',
            old_name='sent_dt',
            new_name='sent_to_epr',
        ),
        migrations.RenameField(
            model_name='covidfollowupcallfollowupcall',
            old_name='sent_dt',
            new_name='sent_to_epr',
        ),
        migrations.RenameField(
            model_name='covidsixmonthfollowup',
            old_name='sent_dt',
            new_name='sent_to_epr',
        ),
    ]
