# Generated by Django 2.2.16 on 2022-12-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0060_auto_20220106_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidadmission',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='covidcomorbidities',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='covidfollowupcall',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='covidfollowupcallfollowupcall',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='covidsixmonthfollowup',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='covidvaccination',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lungfunctiontest',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
