# Generated by Django 2.2.16 on 2022-01-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0060_auto_20220106_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='lungfunctiontest',
            name='kco',
            field=models.CharField(blank=True, max_length=244, null=True, verbose_name='KCO'),
        ),
        migrations.AddField(
            model_name='lungfunctiontest',
            name='pef',
            field=models.CharField(blank=True, max_length=244, null=True, verbose_name='PEF'),
        ),
        migrations.AddField(
            model_name='lungfunctiontest',
            name='vc',
            field=models.CharField(blank=True, max_length=244, null=True, verbose_name='VC'),
        ),
    ]
