# Generated by Django 2.0.13 on 2021-09-23 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0040_auto_20201007_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPATRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('accepted', models.NullBooleanField()),
                ('rejection_reason', models.TextField(default='')),
                ('decision_making_consultant', models.CharField(blank=True, max_length=256, null=True)),
                ('referral_date', models.DateField(blank=True, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('opat_start_date', models.DateField(blank=True, null=True)),
                ('opat_end_date', models.DateField(blank=True, null=True)),
                ('administration', models.CharField(blank=True, choices=[('Self', 'Self'), ('Family', 'Family'), ('Carer', 'Carer'), ('District Nurse', 'District Nurse'), ('HAH', 'HAH'), ('Private Local', 'Private Local'), ('OPAT', 'OPAT'), ('Local A&E', 'Local A&E'), ('Other', 'Other')], max_length=200, null=True)),
                ('supply', models.CharField(blank=True, choices=[('RNOH', 'RNOH'), ('GP', 'GP'), ('Local hospital', 'Local hospital'), ('Private', 'Private')], max_length=200, null=True)),
                ('outcome_early', models.CharField(blank=True, choices=[('Cured', 'Cured'), ('Improved - off antibiotics', 'Improved - off antibiotics'), ('Improved - on suppression', 'Improved - on suppression'), ('Improved - further treatment planned', 'Improved - further treatment planned'), ('Failed', 'Failed'), ('Indeterminate', 'Indeterminate')], max_length=200, null=True)),
                ('outcome_early_date', models.DateField(blank=True, null=True)),
                ('outcome_one_year', models.CharField(blank=True, choices=[('Cured', 'Cured'), ('Improved - off antibiotics', 'Improved - off antibiotics'), ('Improved - on suppression', 'Improved - on suppression'), ('Improved - further treatment planned', 'Improved - further treatment planned'), ('Failed', 'Failed'), ('Indeterminate', 'Indeterminate')], max_length=200, null=True)),
                ('outcome_one_year_date', models.DateField(blank=True, null=True)),
                ('outcome_two_years', models.CharField(blank=True, choices=[('Cured', 'Cured'), ('Improved - off antibiotics', 'Improved - off antibiotics'), ('Improved - on suppression', 'Improved - on suppression'), ('Improved - further treatment planned', 'Improved - further treatment planned'), ('Failed', 'Failed'), ('Indeterminate', 'Indeterminate')], max_length=200, null=True)),
                ('outcome_two_years_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opat_opatrecord_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_opat_opatrecord_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'OPAT',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
