# Generated by Django 2.0.13 on 2021-09-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opatrecord',
            name='referral_source',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
