# Generated by Django 2.0.13 on 2021-09-30 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opat', '0003_opatactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPATIndication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('system', models.CharField(blank=True, max_length=255, null=True, verbose_name='System')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Code')),
                ('version', models.CharField(blank=True, max_length=255, null=True, verbose_name='Version')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='opatrecord',
            name='accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opatrecord',
            name='indication_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opatrecord',
            name='rejected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opatrecord',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='opatindication',
            unique_together={('code', 'system')},
        ),
        migrations.AddField(
            model_name='opatrecord',
            name='indication_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opat.OPATIndication'),
        ),
    ]
