# Generated by Django 2.2.16 on 2025-03-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opat', '0008_opatrecord_microbiology'),
    ]

    operations = [
        migrations.AddField(
            model_name='opatrecord',
            name='monitoring',
            field=models.NullBooleanField(default=False),
        ),
    ]
