# Generated by Django 2.2.16 on 2025-08-27 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opat', '0011_auto_20250318_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opatrecord',
            name='treatment_outcome',
            field=models.CharField(blank=True, choices=[('Cured', 'Cured'), ('Improved', 'Improved'), ('Death OPAT related', 'Death OPAT related'), ('Death unrelated to OPAT', 'Death unrelated to OPAT'), ('Failed', 'Failed'), ('Improved', 'Improved'), ('IPAT (completed as in-patient)', 'IPAT (completed as in-patient)'), ('Stopped early for other clinical reasons', 'Stopped early for other clinical reasons'), ('Transferred to other hospital', 'Transferred to other hospital'), ('Moved to Lifelong / Palliative list', 'Moved to Lifelong / Palliative list')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='RelevantOpatBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('details', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opat_relevantopatbackground_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_opat_relevantopatbackground_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
