# Generated by Django 2.2.16 on 2025-10-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opat', '0012_auto_20250827_0631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relevantopatbackground',
            options={'verbose_name': 'Relevant Background'},
        ),
        migrations.AlterField(
            model_name='opatrecord',
            name='complications',
            field=models.CharField(blank=True, choices=[('Allergy', 'Allergy'), ('Liver impairment', 'Liver impairment'), ('Renal impairment', 'Renal impairment'), ('OtherVascular access (infection)', 'OtherVascular access (infection)'), ('Vascular access (thrombus)', 'Vascular access (thrombus)'), ('Vascular access (other)', 'Vascular access (other)'), ('Drug reaction (allergy)', 'Drug reaction (allergy)'), ('Drug reaction (renal impairment)', 'Drug reaction (renal impairment)'), ('Drug reaction (hepatic)', 'Drug reaction (hepatic)'), ('Drug reaction (other)', 'Drug reaction (other)'), ('C difficile diarrhoea', 'C difficile diarrhoea'), ('Issue with compliance', 'Issue with compliance')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='opatrecord',
            name='discharge_date',
            field=models.DateField(blank=True, help_text='This date will be used to calculate Bed Days Saved', null=True, verbose_name='Hospital Discharge Date'),
        ),
        migrations.AlterField(
            model_name='opatrecord',
            name='opat_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='OPAT End Date'),
        ),
        migrations.AlterField(
            model_name='opatrecord',
            name='treatment_outcome',
            field=models.CharField(blank=True, choices=[('Cured', 'Cured'), ('Improved', 'Improved'), ('Death OPAT related', 'Death OPAT related'), ('Death unrelated to OPAT', 'Death unrelated to OPAT'), ('Failed', 'Failed'), ('IPAT', 'IPAT'), ('Stopped early for other clinical reasons', 'Stopped early for other clinical reasons'), ('Transferred to other hospital', 'Transferred to other hospital'), ('Moved to Palliative list', 'Moved to Palliative list')], max_length=200, null=True),
        ),
    ]
