from collections import defaultdict

"""
TOP-LEVEL TAB GROUPINGS:

BIOCHEMISTRY = OTHER-BIOCHEMISTRY + SERUM-BIOCHEMISTRY + URINE-BIOCHEMISTRY
HAEMATOLOGY = HAEMATOLOGY-LAB + TRANSFUSION + COAGULATION
INFECTION = MICROBIOLOGY + VIROLOGY
OTHER = IMMUNOLOGY + HISTOCYTOPATHOLOGY + GENETICS + LAB-COMMENTS
"""

_LAB_TEST_TAGS = {
    "OTHER-BIOCHEMISTRY": [
        "BETA HCG [CSF]",
        "BODYFLUID GLUCOSE",
        "BODYFLUID UREA",
        "BODYFLUID CALCIUM",
        "BODYFLUID SODIUM",
        "BODYFLUID POTASSIUM",
        "BODYFLUID ENZ CREATININE",
        "BODYFLUID AMYLASE",
        "BODYFLUID PHOSPHATE",
        "BODYFLUID BILIRUBIN",
        "BODYFLUID LDH",
        "BODYFLUID PROTEIN",
        "BODYFLUID MAGNESIUM",
        "BODYFLUID CREATININE",
        "BODYFLUID CHLORIDE",
        "FLUID CA-125",
        "STONE ANALYSIS",
        "CSF PROTEIN",
        "CSF GLUCOSE",
        "POTASSIUM [WHOLE BLOOD]",
        "CHROMIUM [WHOLE BLOOD]",
        "LACTATE [WHOLE BLOOD]",
        "COBALT [WHOLE BLOOD]",
        "MANGANESE (WHOLE BLOOD)",
        "IONISED CALCIUM [WHOLE B]",
        "WHOLE BLOOD ACYLCARNITINE",
        "FAECAL POTASSIUM",
        "FAECAL REDUCING SUBS",
        "FAECAL CHROMATOGRAPHY",
        "FAECAL A1AT",
        "FAECAL PH",
        "FAECAL SODIUM",
        "FAECAL PORPHYRINS",
        "FAECAL CHYMOTRYPSIN",
        "FAECAL ELECTROLYTES",
        "ASCITIC FLUID",
        "FLUID ALBUMIN",
        "FLUID TRIGLYCERIDES",
        "PLACENTAL ALP",
        "FLUID PH",
        "FLUID CEA",
        "PD FLUID PROFILE",
        "FLUID CA-199",
        "FLUID AFP",
        "CITM VAL: FLUID 1",
        "CITM VAL: FLUID 2",
        "FLUID HCG",
        "FLUID ADENOSINE DEAMINASE",
        "FLUID OSMOLALITY",
        "LIVER IRON",
        "LIVER ALP",
        "AFP [CSF]",
        "CSF PIGMENTS",
        "LACTATE [CSF]",
        "ACE [CSF]",
        "CSF TAU PROTEIN",
        "CSF A-BETA 1-42",
        "NEQAS CSF",
        "CSF Tau/A Beta 142 ratio",
    ],
    "SERUM-BIOCHEMISTRY": [
        "AMINO ACID CHROMATOG",
        "EOSIN-5-MALEIMIDE ASSAY",
        "VERY LONG CHAIN F. ACIDS",
        "REFERRED CREATININE",
        "GAL-1-P-URIDYLTRANSFERASE",
        "YEQAS FOB",
        "NEQAS PSA",
        "HSPU CHEMISTRY BLOOD GAS",
        "TRANSFERRIN GLYCOFORM",
        "HSPU CHEMISTRY CRP",
        "IL28B TEST",
        "UREA AND ELECTROLYTES",
        "POTASSIUM",
        "MAGNESIUM",
        "BONE PROFILE",
        "LIVER PROFILE",
        "AFP",
        "BETA-HYDROXYBUTARATE",
        "PYRUVATE KINASE ASSAY",
        "LACTATE DEHYDROGENASE",
        "ALT",
        "GAMMA-GT",
        "ENZ.CREATININE",
        "C REACTIVE PROTEIN",
        "RENAL PROFILE",
        "CHOLESTEROL/TRIGLYCERIDES",
        "DHR (DIHYDRORHODAMINE)",
        "IRON STUDIES",
        "HAEMATINICS",
        "HBA1C", "HBA1C (DCCT)"
        "CORTISOL AT 9AM",
        "THYROID FUNCTION TESTS",
        "B12 AND FOLATE SCREEN",
        "PROCOLLAGEN III NP",
        "CARB. DEF. TRANSFERRIN",
        "THIO.PURINE METHYL T'ASE",
        "IMMUNOGLOBULIN G",
        "GLUCOSE",
        "TRANSCOBALAMIN",
        "VITAMIN K LEVEL",
        "ESR",
        "SHORT SYNACTHEN TEST",
        "25-OH VITAMIN D",
        "PROTEIN ELECTROPHORESIS",
        "BICARBONATE",
        "URATE",
        "VENOUS BLOOD PH",
        "PH",
        "REFERRAL TFT",
        "CALCITONIN",
        "AMYLASE",
        "DHEA-SULPHATE",
        "A1AT PHENOTYPE",
        "PTH",
        "INTRAOPERATIVE PTH 15'",
        "IGF BINDING PROTEIN 3",
        "CARDIAC TROPONIN T",
        "NT PRO-BNP",  # N-terminal pro-brain natriuretic peptide
        "GENTAMICIN LEVEL",
        "TISSUE TRANSGLUTAMINASE",
        "TACROLIMUS",
        "METHYL MALONIC ACID",
        "GLUCAGON TEST",
        "VITAMIN B6",
        "PSA",
        "COMPLEMENT",
        "FOLATE",
        "CYCLOSERINE LEVEL ASSAY",
        "FLUCYTOSINE LEVEL ASSAY",
        "FRUCTOSAMINE",
        "CREATINE KINASE",
        "CARDIAC PROFILE",
        "TOTAL PROTEIN",
        "SERUM AMYLOID A",
        "ARTERIAL BLOOD GASES",
        "HELICO. PYLORI  AGN. TEST",
        "CREATININE CLEARANCE",  # requires both serum and urine test
        "RHEUMATOID FACTOR",
        "OXYGEN DISSOCIATION",
        "TESTOSTERONE",
        "PROLACTIN",
        "OESTRADIOL",
        "CREATININE",
        "TOTAL BILIRUBIN",
        "CA 125",
        "PHOSPHATE",
        "FERRITIN",
        "CORTISOL",
        "ZINC",
        "NEQAS MONOCLONAL SERUM",
        "COC-AMPHET RELATED TRANSC",
        "WHITE CELL ENZYME SCREEN",
        "COPPER",
        "CORRECTED CALCIUM",
        "ALBUMIN",
        "MANNOSE BINDING LECTIN",
        "AST",
        "DIRECT LDL CHOLESTEROL",
        "GTT (ACROMEGALY)",
        "OESTRADIOL",
        "CEA",
        "REFERRED GLYCATED HB",
        "RNA POLYMERASE",
        "LIPASE",
        "LYSOZYME ASSAY",
        "FAECAL CALPROTECTIN",
        "GUT HORMONE PROFILE",
        "LIPID FRACTIONATION",
        "FT3",
        "PAEDIATRIC PROFILE",
        "PROGESTERONE",
        "PROTEASE (PR)",
        "BETA HCG",
        "ALKALINE PHOSPHATASE",
        "GLYCATED HB (DCCT)",
        "FREE ANDROGEN INDEX",
        "D-DIMER",
        "LH",
        "GNRH STIMULATION TEST",
        "170H PG STIMULATION TEST",
        "FREE PSA",
        "CA 199",
        "IRON STUDIES (FER)",
        "THYROGLOBULIN (BHAM)",
        "THYROID PEROXIDASE",
        "CARDIOLIPIN",
        "PLATELET NUCLEOTIDES",
        "ININS",
        "RED CELL MEMBRANE ANALY",
        "SWEAT TEST",
        "COLLAGEN BINDING ACTIVITY",
        "RDU PRE-DIALYSIS SCREEN",
        "INTEGRASE",
        " ANTI NUCLEAR AB",  # leading space in source document
        "ENA CHARACTERISATION",
        "CCP ANTIBODY",
        "ANCA",
        "MYOSITIS AUTOANTIBODIES",
        "DS DNA ABS",
        "ENA BATTERY",
        "ANTIBIOTIC ASSAY",
        "LUPUS SCREEN",
        "SHBG",
        "RENIN AND ALDOSTERONE",
        "MAST CELL TRYPTASE",
        "CARNITINE",
        "TRIGLYCERIDES",
        "GLUCAGON",
        "ARGATROBAN LEVEL",
        "DABIGATRAN LEVEL",
        "MERCURY",
        "TOPIRAMATE",
        "ADAMTS13 ASSAY",
        "PDF CA 125",
        "APTT",
        "URINE 5HIAA",
        "CORTISOL AT 9AM",
        "GLUCOSE TOLERANCE TEST",
        "OSMOLALITY",
        "ACE",
        "CHLORIDE",
        "REVERSE TRANSCRIPTASE",
        "ALPHA 1 ANTITRYSPIN",
        "B2 MICROGLOBULIN",
        "CHROMOGRANIN A",
        "CAERULOPLASMIN",
        "DIGOXIN",
        "RETINOL BINDING PROTEIN",
        "B2 GLYCOPROTEIN 1",
        "PLASMA A-GALACTOSIDASE",
        "SELENIUM",
        "PLACENTAL ALP ISOENZYME",
        "ETHANOL",
        "CYCLOSPORIN",
        "BETA D GLUCAN TEST",
        "MYELOPEROXIDASE AB",
        "ALP ISOENZYMES",
        "PARACETAMOL",
        "LIPID ELECTROPHORESIS",
        "CHOLESTEROL",
        "SIROLIMUS",
        "FAECAL OCCULT BLOOD",
        "PR3 AB",
        "CHROMOGRANIN A (IN HOUSE)",
        "APO LIPOPROTEIN AII",
        "AMMONIA",
        "TSH RECEPTOR ANTIBODY",
        "THYROGLOBULIN",
        "FT4",
        "LITHIUM",
        "CA 153",
        "AMYLASE ISOENZYMES",
        "G6PD SCREEN",
        "THIOGUANINE NUCLEOTIDES",
        "TROPONIN I",
        "APO LIPOPROTEIN B",
        "ERYTHROPOIETIN LEVEL",
        "EGFR (C+G)",
        "IGF-1",
        "EGFR (MDRD)",
        "APO LIPOPROTEIN AI",
        "PLASMA METADRENALINES",
        "CK ISOENZYMES",
        "HOMOCYSTINE",
        "HAPTOGLOBIN",
        "BILE ACIDS",
        "UREA",
        "INTRAOPERATIVE PTH 10'",
        "SALICYLATE",
        "GBM AB",
        "CALCIUM",
        "SOMATOSTATIN",
        "CHROMOGRANIN B",
        "CHROMOGRANIN A (SENDAWAY)",
        "CHOLINESTERASE",
        "EXTRINSIC FACTOR ASSAYS",
        "ALUMINIUM",
        "GASTRIN",
        "ALDOSTERONE",
        "TSH",
        "RED CELL FOLATE",
        "ACTH",
        "INTRAOPERATIVE PTH",
        "FUNCTIONAL COMPLEMENT",
        "FAECAL ELASTASE",
        "CRYOGLOBULIN",
        "PLASMA CHITOTRIOSIDASE",
        "GALACTOMANNAN AGN. ELISA",
        "IM TEST",
        "ANDROSTENEDIONE",
        "17-0H PROGESTERONE",
        "ADRENAL",
        "PANCREATIC ISLET CELL",
        "INTRAOPERATIVE PTH 5'",
        "HYDROCORTISONE DAY CURVE",
        "EXT INSULIN STRESS TEST",
        "5 POINT DAY CURVE FOR GH",
        "CATECHOLAMINES [PLASMA]",
        "DIHYDROTESTOSTERONE",
        "INSULIN TOLERANCE TEST",
        "INHIBIN B",
        "VIP",
        "TRH STIMULATION TEST",
        "EXTENDED SYNACTHEN TEST",
        "CORTISOL BINDING GLOBULIN",
        "SODIUM",
        "INTRINSIC FACTOR",
        "IGG4",
        "ESR - RNOH",
        "HIGH SENSITIVE TROPONIN T",
        "CK MB [FRACTION]",
        "VITAMIN B12",
        "1,25 VITAMIN D",
        "C-PEPTIDE",
        "C1 ESTERASE",
        "TOTAL IRON BINDING CAPACI",
        "LIVER TISSUE COPPER",
        "G6PD ASSAY",
        "PENICILLOYL G",
        "PLASMA HAEMOGLOBIN",
        "TOTAL T3",
        "IMMUNOREACTIVE TRYPSIN",
        "11-DEOXYCORTISOL",
        "SEROTONIN",
        "BILIARY ALP",
        "LEUK A-GALACTOSIDASE",
        "TOTAL T4",
        "COLD AGGLUTININ  TITRE",
        "BETA-TRANSFERRIN",
        "CK-MB",
        "ARSENIC",
        "IRON CONCENTRATION",
        "FREE FATTY ACIDS",
        "FASTING GLUCOSE",
        "ERYTHROCYTE PROTOPORPHYRI",
        "INTESTINAL ALP",
        "THYROXINE BINDING GLOBULI",
        "TATC",
        "PYRIMIDINE 5'NUCLEOTIDASE",
        "ACETOACETATE",
        "PHYTANIC ACID",
        "THYROGLOBULIN ANTIBODY",
        "ENZ CREAT CLEARANCE",
        "WHITE CELL CYSTINE",
        "PREALBUMIN",
        "COMPLEMENT C2",
        "PLASMINOGEN:AG",
        "GP1B",
        "TRYPSIN",
        "RISTOCETIN 1.0 MG/ML",
        "CHROMOGENIC F8 (BOVINE)",
        "BONE ALP",
        "FIBRBLAST GROWTH FACTOR23",
        "LDH ISOENZYMES",
        "OXALATE  [PLASMA]",
        "LEAD",
        "VITAMIN A",
        "FILM REPORT - RNOH",
        "DIALYSATE SODIUM",
        "BIOTINIDASE",
        "ACIDIFIED SERUM LYSIS",
        "N-ACETYL GLUCOSAMINE",
        "INHIBITOR TITRE (PORCINE)",
        "UNSTABLE HAEMOGLOBIN",
        "PREKALLIKREIN",
        "PANCREATIC POLYPEPTIDE",
        "GTT - EXTENDED",
        "OMEGA-5 GLIADIN",
        "CARBOXY-HAEMOGLOBIN",
        "HBSC",
        "ANTI-MULLERIAN (ADULT)",
        "ANTI-MULLERIAN (CHILD)",
        "RBC ENZYME INTERMEDIATES",
        "HDL CHOLESTEROL",
        "PYRUVATE",
        "AVIAN PRECIPITINS",
        "ACID PHOSPHATASE",
        "VITAMIN E",
        "LACTATE [PLASMA]",
        "B-GLUCOSIDASE ACTIVITY",
        "HIGH SENSITIVITY CRP",
        "PROTEASE:",
        "THIO.PURINE METHYL T'ASE",
        "APOE PHENOTYPE",
        "NEQAS LIPIDS LINE 1",
        "PTH RELATED PROTEIN",
    ],
    "URINE-BIOCHEMISTRY": [
        "OLIGOCLONAL BANDS",
        "OSMALITY",
        "PROTEIN ELECTROPHORESIS",
        "URINE PROTEIN/CR RATIO",
        "URINE ALB:CREAT RATIO",
        "URINE PROTEIN CONCENTR",
        "URINE ELECTROPHORESIS",
        "CREATININE CLEARANCE",  # is both a blood and a urine test
        "URINE IMMUNOFIXATION",
        "UR. GLYCOSAMINOGLYCANS",
        "UR. ETHANOL",
        "UR AMINO ACID CHROMATOG",
        "UR. RBP/CREATININE RATIO",
        "UR.CALCIUM:CREAT RATIO",
        "UR. NAG/CREATININE RATIO",
        "24 HR URINE PROTEIN",
        "24 HR URINE ELECTROLYTES",
        "24 HR URINE CREATININE",
        "24HR UR. IN PLAIN BOTTLE",
        "24 HR URINE UREA",
        "URINE METADRENALINES 24HR",
        "BENCE JONES PROTEIN",
        "URINE DRUG SCREEN",
        "URINE ELECTROLYTES",
        "PARAPROTEIN",
        "24HR UR. IN ACID BOTTLE",
        "24 HR URINE CALCIUM",
        "URINE STONE SPOT",
        "URINE OSMOLALITY",
        "24 HR URINE SODIUM",
        "URINE DIPSTICK ANALYSIS",
        "NEQAS URINE CHEMISTRIES",
        "URINE NTX",
        "24HR URINE FREE CORTISOL",
        "URINE COPPER",
        "URINE CREATININE CONCENTR",
        "URINE METADRENALINES SPOT",
        "URINE PHOSPHATE CONC",
        "24HR URINE PHOSPHATE",
        "URINE VOLUME",
        "URINE CALCIUM CONCENTR",
        "URINE ALBUMIN CONCENTR",
        "URINE URATE CONCENTR",
        "NEQAS MONOCLONAL BJP",
        "URINE STEROID PROFILE",
        "URINE MAGNESIUM CONCENTR",
        "URINE CYSTINE",
        "URINE UREA CONCENTRATION",
        "URINE PREGNANCY TEST",
        "24 HR URINE OXALATE",
        "URINE SODIUM CONCENTR",
        "24 HR URINE MAGNESIUM",
        "URINE PORPHYRINS",
        "URINE CHLORIDE",
        "24 HR URINE POTASSIUM",
        "URINE PH",
        "24 HR URINE URATE",
        "URINE CITRATE",
        "URINE PBG",
        "URINE ORGANIC ACIDS",
        "URINE COPPER CONCENTR",
        "URINE AMYLASE CONC",
        "URINE GLYCOLATE",
        "URINE ALBUMIN",
        "URINE ZINC CONCENTRATION",
        "URINE BLOOD",
        "24 HR URINE ZINC",
        "URINE HAEMOSIDERIN",
        "URINE KETONES",
        "24HR URINE CYSTINE",
        "URINE POTASSIUM CONCENTR",
        "CITM VAL: URINE 1",
        "URINE CYSTINE SCREEN",
        "24HR URINE CHLORIDE",
        "URINE BILIRUBIN",
        "URINE HAEMOGLOBIN",
        "URINE REDUCING SUGARS",
        "URINE BICARBONATE",
        "URINE MERCURY",
        "VB URINE",
        "URINE CADMIUM",
        "URINE UROBILINOGEN",
        "URINE OXALATE CONCENTR",
        "URINE GLUCOSE",
        "24 HR URINE IRON",
        "URINE MYOGLOBIN",
        "URINE SUGAR CHROMATOG",
        "URINE IRON CONCENTRATION",
        "URINE CYSTINE/HOMOCYSTINE",
    ],
    "DRUG-LEVELS": [
        # for both therapeutic monitoring and toxicology purposes
        "GENTAMICIN LEVEL",
        "THYROID FUNCTION TESTS",  # for monitoring thyroxine dosing
        "TACROLIMUS",
        "QUANTIFERON TB GOLD IT",
        "AMIKACIN LEVEL",
        "VANCOMYCIN LEVEL",
        "DIGOXIN",
        "AMOXICILLOYL",
        "ETHANOL",
        "CYCLOSPORIN",
        "PARACETAMOL",
        "SIROLIMUS",
        "LITHIUM",
        "SALICYLATE",
        "CLOZAPINE/NORCLOZAPINE",
        "PREDNISOLONE",
        "TEICOPLANIN LEVEL",
        "PHENYTOIN",
        "MYCOPHENOLIC ACID",
        "METHOTREXATE",
        "VALPROATE",
        "INSULIN",
        "CARBAMAZEPINE",
        "TINZAPARIN ANTIXA LEVEL",
        "INFLIXIMAB PROFILE",
        "LEVETIRACETAM",
        "LAMOTRIGINE",
        "PHENOBARBITONE",
        "OXCARBAZEPINE",
        "WARFARIN MONITOR",
        "METHANOL",
        "AMIODARONE",
        "AMITRIPTYLINE",
        "BARBITURATES",
        "CLONAZEPAM",
        "CLOBAZAM",
        "NORTRIPTYLINE",
        "ETHOSUXIMIDE",
        "METHADONE",
        "ANTIBIOTIC ASSAY",
        "ANTIFUNGAL DRUG ASSAY",
        "THEOPHYLLINE",
        "TRICYCLIC ANTIDEPRESSANTS",
        "OLANZAPINE",
        "FONDAPARINUX LEVEL",
        "GABA-PENTIN",
        "APIXABAN LEVEL",
        "RIVAROXABAN LEVEL",
        "TOPIRAMATE",
        "ADALIMUMAB PROFILE",
        "ARGATROBAN (APTT RATIO)",
        "PENICILLOYL V",
        "CYCLOSERINE LEVEL ASSAY",
        "FLUCYTOSINE LEVEL ASSAY",
    ],
    "TUMOUR-MARKERS": [
        "PSA",
        "CA 125",
        "CEA",
        "FAECAL CALPROTECTIN",
        "FREE PSA",
        "CA 199",
        "URINE 5HIAA",
        "CA 153",
        "FLUID CA-125",
        "TUMOUR MARK",
    ],
    # Haematology
    # For display purposes transfusion, coagulation and haematology can be sensibly grouped.
    "HAEMATOLOGY-LAB": [
        "FULL BLOOD COUNT", "FULL BLOOD COUNT RNOH",
        "LYMPHOCYTE SUBSETS",
        "ESR",  # debatable - who does the ESRs in a lab?
        "FILM REPORT",  # report from a blood film microscopy
        "ANC HAEMOGLOBINOPATHY SCR",
        "HAEMOGLOBINOPATHY SCREEN",
        "HAEMOGLOBINOPATHY SCREEN-",
        "REFLEX HAEMOGLOBINOPATHY",
        "CAM HB ELECTROPHORESIS",
        "RETICULOCYTE COUNT",
        "RETIC - RNOH",
        "PLATELET AGGREGATION",
        "HEINZ BODIES",
        "HB VARIANT FURTHER INVEST",
        "HAEM B CARRIER DETECTION",
        "AUTO HAEMOLYSIS TEST",
        "OSMOTIC FRAGILITY TEST",
        "PLASMA VISCOSITY",
    ],
    "TRANSFUSION": [
        "FULL BLOOD GROUP",
        "BLOOD GROUP",
        "SAVE SERUM",
        # Haemolytic disease of newborn (HDN)
        "NEWBORN GROUP + DAT",
        "KLEIHAUER",
        "FETAL RHD GENOTYPING",
        "ANTIBODY SCREEN",  # transfusion atypical antibody screen
        "TRANSFUSION REACTION",
    ],
    "COAGULATION": [
        "CLOTTING SCREEN",
        "VWF:AG",
        "VWF:CB",
        "VWF: RICOF ASSAY",
        "VWF COLLAGEN BINDING POST",
        "VWD TYPE 2 A/B/M ANALYSIS",
        "VWF INHIBITOR SCREEN",
        "VWD TYPE 2N ANALYSIS",
        "90MIN VWF:RCO",
        "VWF:AC",
        "VWF:AB LATEX",
        "VWF MULTIMERS",
        "VWF:RICOF ASSAY (POST)",
        "VWF:RCO DOSE",
        "VWF: AG LATEX ASSAY",
        "VWF:RICOF ASSAY (PRE)",
        "VWF:AG (POST)",
        "VWF:AG (PRE)",
        "PROTHROMBIN TIME",
        "PROTHROMBIN TIME (MANUAL)",
        "THROMBIN TIME",
        "INR",
        "APTT",
        "APTT 50:50 MIX",
        "HEPARIN RATIO",
        "PROTHROMBOTIC SCREEN 1",
        "FIBRINOGEN",
        "D-DIMER",
        "FDPS",  # fibrin degradation products
        "PLATELET AGGREGATION",
        "TPA:AG",
        "ALPHA 2 ANTIPLASMIN:AC",
        "FIBRINOGEN ANTIGEN",
        "HAEM A CARRIER DETECTION",
        "PLASMINOGEN:AC",
        "FACTOR VIII:C BIOASSAY",
        "FACTOR 11 ANTIGEN",
        "PROTEIN C:F VII RATIO",
        "FVIII INHIBITORS",
        "ANTI XA ASSAY",
        "REPTILASE TIME",
        "PROTEIN S:TOTAL",
        "INTRINSIC PATHWAY ASSAYS",
        "ANTITHROMBIN:AC",
        "PROTEIN S FREE: LATEX",
        "F IX INHIBITORS",
        "PROTEIN C:AC",
        "ANTI-PLATELET FACTOR 4",
        "FACTOR X1 ASSAY",
        "FACTOR IX:C ASSAY",
        "F VIII POST TREATMENT",
        "THROMBOELASTOMETRY",
        "UFH (ANTI XA LEVEL)",
        "UFH (APTT RATIO)",
        "APTT (MANUAL)",
        "HMW KININOGEN",
        "APTT AND HEPARIN RATIO",
        "APTT INHIBITOR SCREEN",
        "FACTOR I LEVEL",
        "PROTHROMBIN F 1+2",
        "PROTHROMBIN 3' UTR VARIAN",
        "RISTOCETIN 1.2 MG/ML",
        "CHROMOGENIC F8 INHIBITORS",
        "FACTOR II ASSAY (POST)",
        "FACTOR VII:AG ELISA",
        "FVIII:AG ELISA",
        "RISTOCETIN 0.75 MG/ML",
        "FVIII CHROMOGENIC",
        "FVIII CVS ANALYSIS",
        "CRYOFIBRINOGEN SCREEN",
        "FXIII ACTIVITY",
        "ANTI-PLATELET FACTOR 4",
        "FACTOR XII ASSAY",
        "FACTOR VII BIOASSAY",
        "FACTOR X BIOASSAY",
        "FACTOR IX:C ASSAY (POST)",
        "FACTOR II BIOASSAY",
        "FACTOR V LEIDEN GENOTYPE",
        "FACTOR XIII A SUBUNIT",
        "FACTOR V BIOASSAY",
        "VWF COLLAGEN BINDING PRE",
        "DALTEPARIN ANTI XA LEVEL",
        "FACTOR XI INHIBITORS",
        "FACTOR XI ASSAY (POST)",
        "ENOXAPARIN ANTI XA LEVEL",
        "HSPU HAEMATOLOGY COAG",
        "FACTOR VIII BINDING ASSAY",
        "CITRATE PLATELET COUNT",
        "DANAPAROID ANTI XA LEVEL",
        "FACTOR X ASSAY (POST)",
        "FACTOR XIII SCREEN",
        "FACTOR XIII B SUBUNIT",
        "FACTOR IX:AG",
        "FACTOR H LEVEL",
        "ANTITHROMBIN:AG",
        "PROTEIN S (FREE) BIOASSAY",
        "PROTEIN C:AG",
        "DIRECT ANTIGLOBULIN TEST",
        # DDAVP functional tests (Haemophilia)
        "90MIN POST DDAVP",
        "PRE DDAVP TRIAL",
        "4HR POST DDAVP",
        "DDAVP ADMINISTRATION",
        "PRE DDAVP-HAEMA",
        "4HR DDAVP - HAEM A",
        "6HR POST DDAVP",
        "6HR DDAVP - HAEM A",
        "2HR DDAVP - HAEM A",
        "30MIN DDAVP - HAEM A",
        "1HR DDAVP-HAEM A",
        "30MIN POST DDAVP",
        "2HR POST DDAVP",
        "1HR POST DDAVP",
        "PRE VW:AG DDAVP TRIAL",
    ],
    # Microbiology & Virology
    "MICROBIOLOGY": [
        "URINE SCREENING TEST",  # flow cyto then culture
        # TB tests - (AFB = Acid-Fast Bacilli = mostly TB)
        "FLOW CYTOMETRY",
        "AFB : CULTURE",
        "AFB : EARLY MORN. URINE",
        "AFB BLOOD CULTURE",
        "MRSA SCREEN",
        "RESPIRATORY PCR",
        "CHLAMYDIA / GC SDA ASSAY",
        "SYPHILIS SEROLOGY",
        "SYPHILIS ANC REQUESTS",
        "CLOST. DIFFICILE TOXIN",
        "CARBAPENEMASE SCREEN",
        "HYDATID ANTIBODIES",
        "HYDATID ASPIRATE",
        "GASTROENTERITIS PCR",
        "ATYPICALPNEUMONIA PCR",
        "OVA CYST AND PARASITE",
        "PD FLUID",
        "FUNGAL EXAMINATION",
        "CHL.TRACHOMATIS SDA-ASSAY",
        "SKIN SWAB",
        "SEROTYPE PNEUMOCOCCAL AB",
        "MRSA MOLECULAR SCREEN",
        "BORRELIA BURGDORFERI ABS.",
        "MALARIA PARASITE",
        "TOXOPLASMA SEROLOGY",
        "TOXOPLASMA REF. LAB.",
        "PNEUMOCOCCAL C.P.  AB",
        "VRE SCREEN MC+S",
        "TB PCR TEST",
        "LEGIONELLA ANTIGEN TEST",
        "PNEUMOCOCCUS ANTIGEN",
        "SCHISTOSOMA ANTIBODIES",
        "ASPERGILLUS FUMIGATUS",
        "MYCOPLASMA SEROLOGY",
        "MALARIA ANTIBODIES",
        "ASP FUMIGATUS PPTNS",
        "HISTOPLASMA ANTIBODIES",
        "H.PYLORI REF LAB TEST",
        "STRONGYLOIDES ANTIBODIES",
        "BRONCHIAL WASHINGS",
        "HAEMOPHILUS INFLUENZAE AB",
        "CRYPTOSPORIDIUM MICRO.",
        "CRITHIDIA",
        "BORDETELLA  ANTIBODIES",
        "COXIELLA ANTIBODIES",
        "CRYPTOCOCCUS AGN. (BLOOD)",
        "FILARIA ANTIBODIES",
        "CANDIDA AURIS SCREEN",
        "TOXOPLASMA B1 PCR",
        "PNEUMOCYSTIS PCR",
        "RICKETTSIAL ANTIBODIES",
        "CANDIDA  ANTIGEN TEST",
        "LEISHMANIA ANTIBODIES",
        "C.TRACHOMATIS ( LGV )",
        "TOXOCARA SEROLOGY",
        "CHLAMYDIA SEROLOGY",
        "CRYPTOCOCCUS AGN. (CSF)",
        "STRONGYLOIDES CULTURE",
        "MYCOPLASMA PNEUMONIAE PCR",
        "ASPERGILLUS PCR",
        "LEISHMANIA CULTURE / PCR",
        "HISTOPLASMA ANTIGEN TEST",
        "SCHISTOSOMES : URINE",
        "ENTEROVIRUS IGM",
        "REF LAB URINE LEGIONELLA",
        "MENINGOCOCCAL ANTIBODIES",
        "COCCIDIOIDES ANTIBODIES",
        "CH.TRACHOMATIS SDA URINE",
        "CAMPYLOBACTER SEROLOGY",
        "TRICHINELLA  ANTIBODIES",
        "BODETELLA PERTUSIS PCR",
        "LEPTOSPIRA DNA DETECTION",
        "SEMEN CULTURE",
        "YERSINIA ANTIBODIES",
        "MALARIA PARASITE SCREEN",
        "RABIES INVESTIGATIONS",
        "DIPHTHERIA ANTIBODIES",
        "MISC. PARASITOLOGY",
        "PARASITOLOGY : REF. LAB.",
        "EXTERNAL SOURCE-SEROL",
        "TOXOPLASMA PCR. REF. LAB.",
        "BARTONELLA SEROLOGY",
        "LEGIONELLA REF. LAB.",
        "MICROSPORIDIA PCR",
        "BRUCELLA ABS. REF. LAB.",
        "E.COLI  O157  ANTIBODIES",
        "P. JIROVECII PCR",
        "BRUCELLA ANTIBODIES",
        "HAEMOPHILUS ANTIGEN",
        "PNEUMOCOCCUS AGN.REF. LAB",
        "MICROSPORIDIA MICROSCOPY",
        "T-SPOT TB",
        "LEGIONELLA ABS. REF. LAB",
        "THREADWORM PREP.",
        "WIDAL TEST",
        "CANDIDA ALBICANS",
        "AMOEBIC ANTIBODIES",
        "LEPTOSPIRA ANTIBODIES",
        "MENINGOCOCCAL SCREEN :PCR",
        "MYCO / UREAPLASMA PCR :",
        "FUNGAL 18 S PCR SCREEN",
        "TROPHERYMA WHIPPELLII PCR",
        "PNEUMO. JIROVECII PCR",
        "TOXO IGM REF LAB. TEST",
        # site-specific tests
        "DRAIN FLUID",
        "IUCD",
        "BILE CULTURE",
        "CORNEAL SCRAPING",
        "SUPRA PUBIC ASPIRATE",
        "EAR SWAB",
        "CSU",
        "JOINT FLUID",
        "ENDOCERVICAL SWAB",
        "PLEURAL FLUID",
        "TIP CULTURE + SENS",
        "EYE SWAB",
        "NEPHROSTOMY FLUID",
        "ABSCESS SWAB",
        "RECTAL SWAB",
        "ULCER SWAB",
        "PERITONEAL FLUID",
        "BLOOD CULTURE",
        "HIGH VAGINAL SWAB",
        "STOOL CULTURE",
        "CSF  MICRO + CULTURE",
        "LOWER VAGINAL SWAB",
        "THROAT SWAB",
        "MISC. CULTURE",
        "FLUID CULTURE",
        "VAGINAL SWAB",
        "STD-URETHRAL SWAB",
        "GROIN SWAB",
        "SWAB - PLACENTA",
        "TONGUE SWAB",
        "MOUTH SWAB",
        "PERINEAL SWAB",
        "UMBILICAL SWAB",
        "PENILE SWAB",
        "STD-THROAT SWAB",
        "URETHRAL SWAB",
        "STD-RECTAL SWAB",
        "AXILLARY SWAB",
        "PERNASAL SWAB",
        "STD-CERVICAL SWAB",
        "LABIAL SWAB",
        "PUS - FLUID",
        "VULVAL SWAB",
        "CHLAMYDIA SWAB",
        "TRACHEOSTOMY SWAB",
        "DRAIN SWAB SITE - LK",
        "IV CATHETER SITE",
        "GENITAL SWAB",
        "WOUND SWAB CULTURE + SENS",
        "SPUTUM CULTURE",
        "NOSE SWAB",
        "ET TUBE ASPIRATE",
        "BONE MARROW CULTURE",
        "TRYPANOSOMAL ANTIBODIES",
        "FASCIOLA ANTIBODIES",
        "ELECTRON MICROSCOPY",
        "MYCO / UREAPLASMA CULTURE",
        "MISC. SEROLOGY",
        "MYCOPLASMA ABS. REF LAB.",
        "CSF SYPHILIS SEROLOGY",
        "ACINETOBACTER SCREEN",
        "EPIDEMIOLOGY SCREEN",
        "CYSTICERCOSIS ANTIBODIES",
        "STD SCREEN - GC",
        "HELICO. PYLORI SEROLOGY",
        "MYCOLOGY SEROLOGY",
        "REF. LAB. CHLAMYDIA ASSAY",
        "SULPHONYLUREA SCREEN",
        "CJD REFERRAL",
    ],
    "VIROLOGY": [
        # local organisation
        "ICDC ANNUAL SCREEN",
        # CMV
        "CMV PCR",
        "CMV IGM",
        "CMV IGG",
        "CMV ANTIVIRAL RESISTANCE",
        "CMV IGG AVIDITY",
        "SYPHILIS IGM ADD TEST",
        "GUTHRIE CARD CMV PCR",
        # HIV tests
        "HIV SECOND BLOOD SCREEN",
        "HIV-1 TROPISM",
        "HIV 1 + 2 ANTIBODIES",
        "HIV VIRAL LOAD PCR ASSAY",
        "HIV AB AVIDITY*DO NOT USE",
        "HIV 2 ANTIBODIES",
        "REFERRAL LAB HIV AVIDITY",
        "HIV-1 TROPISM ASSAY",
        "HIV CONFIRMATORY ASSAYS",
        "HIV1 INTEGRASE RESISTANCE",
        "INHOUSE HIV1 PROVIRAL DNA",
        "HIV PROVIRAL DNA",
        "HIV-2 VIRAL LOAD",
        "HIV-2 RESISTANCE",
        "QUALITATIVE HIV RNA",
        "CD8 ACTIVATION MARKERS",
        # HAV tests
        "HEPATITIS A IGG AB",
        # HBV tests
        "HBV PCR",
        "HEPATITIS B SURFACE AG",
        "HEPATITIS B E SCREEN",
        "HEP B CORE IGM",
        "HEP B CORE TOTAL",
        "HBV QUANTITATIVE 'S' AG",
        "HEP B SURFACE ANTIBODY",
        "HBV DNA",
        "PREVIOUS HEPATITIS SCREEN",
        "ANTI HBS",  # Antibodies to HepB Surface Antigen
        "ACUTE HEPATITIS SCREEN",
        "HEPATITIS B POSITIVE",
        "HEP B E ANTIGEN",
        # HCV tests
        "HCV PCR",
        "HEPATITIS C ANTIBODY",
        # HDV tests
        "HEPATITIS DELTA VIRUS RNA",
        "HEPATITIS DELTA VIRUS",
        # HEV tests
        "HEV SEROLOGY",
        "HEPATITIS E RNA",
        # VZV tests
        "VZV IGG EIA",
        "VZV PCR",
        # EBV tests
        "EBV IGM/EBNA",
        "EBV VCA IGG",
        "EBV PCR",
        # Rubella
        "RUBELLA PCR",
        "RUBELLA IGG AVIDITY",
        "RUBELLA IGG",
        "RUBELLA IGM",
        "ACUTE RUBELLA SCREEN",
        # HSV tests
        "HSV PCR",
        "CVID B CELL PHENOTYPING",
        "HSV 1 + 2 IGG AB",
        "HCV NS5A RESISTANCE",
        "HTLV I + II ANTIBODIES",
        "T CELL PHENOTYPING",
        "SWINE FLU PCRS",
        # parvovirus
        "PARVOVIRUS B19",
        "PARVOVIRUS B19 IGM",
        "BK PCR",  # BK virus
        "PARVOVIRUS B19 DNA",
        "ADENOVIRUS PCR",
        "TRANSPLANT SCREEN -HIV",
        # HHV
        "HSV / VZV PCR",
        "VZV IGM",
        "HUMAN HERPES VIRUS 6",
        "HUMAN HERPES VIRUS 7",
        "HUMAN HERPES VIRUS 8",
        "HCV GENOTYPE",
        "CMV AVIDITY SCREEN",
        # dengue
        "DENGUE SEROLOGY",
        "DENDUE IGG SEROLOGY",
        "DENGUE PCR",
        # mumps
        "ACUTE MUMPS SCREEN",
        "MUMPS IGG",
        "MUMPS IGM",
        "MUMPS PCR",
        # measles
        "MEASLES IGM",
        "ACUTE MEASLES SCREEN",
        "MEASLES PCR",
        "MEASLES IGG",
        # unusuals
        "WEST NILE ANTIBODIES",
        "EBOLA VIRUS RNA",
        "ENTEROVIRUS PCR",
        "FLU A TYPING PCR",
        "16 R RNA UNIV. BACT. PCR",
        "HDV QUANTITATIVE PCR",
        "JC PCR",
        "HSV TYPE SPECIFIC AB",
        "HCV NS5B DRUG RESISTANCE",
        "HEPATITIS E IGG",
        "APCRV",
        "ARBOVIRUS PCR",
        "PAEDIATRIC RSV POCT",
        "LASSA FEVER PCR",
        "ALPHAVIRUS ANTIBODY",
        "ZIKA VIRUS",
        "FLAVIVIRUS ANTIBODIES",
        "ARBOVIRUS SEROLOGY",
        "ACUTE PARVOVIRUS SCREEN",
        "HANTAVIRUS SEROLOGY",
        "VIRUS GENOTYPE",
        "HBV GENOTYPING",
        "HEPATITIS E IGM",
        "INFLUENZA RESISTANCE TEST",
        "HEP B E ANTIBODY",
        "ENCEPHALITIS SCREEN",
        "HCV RNA QUANTITATIVE",
        "STD SCREEN - TV",
        "TH17 PHENOTYPING",
    ],
    "IMMUNOLOGY": [
        "IMMUNOGLOBULINS",
        "COMPLEMENT C3D",
        "C3 NEPHRITIC FACTOR",
        "SERUM LIGHT CHAINS",
        "IMMUNODEFICIENCY PANEL",
        "ANA BATTERY",
        "ENDOMYSIAL IGG ABS",
        "IMMUNOFIXATION",
        "IMMUNOGLOBULINS",
        "IMMUNOGLOBULIN A",
        "IMMUNOGLOBULIN G",
        "IMMUNOGLOBULIN M",
        "IMMUNOGLOBULIN D",
        "HLA B5701",
        "HLA 27",
        "ANTI NEURONAL ANTIBODIES",
        "ANTI-GAD ANTIBODY",
        "ANTI-VGCC ANTIBODY",
        "ANTI-VGKC ANTIBODY",
        "JC ANTIBODY",
        "AQUAPORIN 4 ANTIBODY",
        "GANGLIOSIDE ANTIBODIES",
        "MAST CELL TRYPTASE",
        "ANTI STREPTOLYSIN O ABS",
        "DAT (SHORT PROFILE)",  # direct antiglobulin test
        "IMMUNOSUPPRESSION SCREEN",
        "ANTI M2 AB",
        "ACETYCHOLINE RECEPTOR AB",
        "SKIN ANTIBODIES",
        "IGG HEVYLITE CHAINS",
        "TISSUE BATTERY",  # Anti-Mito-Ab Anti-SM-Ab panel
        "PHOSPHOLIPASE A2 REC AB",
        "ANTI-NMDA RECEPTOR AB",
        "IGA HEVYLITE CHAINS",
        "ANTI-GAD AB",
        "MAG ANTIBODIES",
        "ANTI IGA ABS",
        "STRIATED MUSCLE AB",
        "STEROID CELL AB",
        "ANTI-HISTONE ANTIBODY",
        "ANTI-GABAB RECEPTOR AB",
        "SERUM LIGHT CHAINS BN2",
        "GLYCINE RECEPTOR ANTIBODY",
        "CARDIOLIPIN IGM",
        "GLIADIN IGG + IGA",
        "ANTI-SRP",
        "MPO + PR3 IGG ANTIBODIES",
        "IG HEAVY CHAIN GENE ANAL",
        "ANTI-C1Q ANTIBODY",
        "FUNCTIONAL C1IN",
        "ANTI-MPO/PR3/GBM BLOT",
        "ANTI NEURONAL AB REFERRAL",
        "BASAL GANGLIA ANTIBODIES",
        "PNH CELL MARKER ANALYSIS",
        "PNH SCREEN",  # paroxysmal nocturnal haemoglobinuria
        "TH17 PHENOTYPING",
        "IGM HEVYLITE CHAINS",
    ],
    "HISTOCYTOPATHOLOGY": [
        "HISTOLOGY",
        "BONE / TISSUE / BIOPSY",
        "DIAGNOSTIC CYTOLOGY",
        "BONE MARROW - 2",
        "BONE MARROW - 1",
        "GYNAE CYTOLOGY 1",
        "URINE SPERMATAZOA TEST",
        "GUT BIOPSY",
        "CSF REPORT",  # csf cytology
        "DIAG CYTO SUPP 2",
        "DIAG CYTO SUPP 3",
        "DIAG CYTO SUPP 4",
        "CJD REFERRAL",

    ],
    "GENETICS": [
        "JAK-2",
        "CODONS ANALYSED:",
        "CALR MUTATION ANALYSIS",
        "MPL MUTATION ANALYSIS",
        "GAUCHER'S DIS MUTATION",
        "HFE (HH) GENE MUTATION",
        "IG MUTATION ANALYSIS",
        "HAEM A MUTATION ANALYSIS",
        "F11 MUTATION ANALYSIS",
        "AT MUTATION ANALYSIS",
        "PROC MUTATION ANALYSIS",
        "HAEM B MUTATION ANALYSIS",
        "FVII MUTATION ANALYSIS",
        "JAK2 EXON12 MUTATION TEST",
        "PROS1 MUTATION ANALYSIS",
        "FX MUTATION ANALYSIS",
        "T-CELL GENE ANALYSIS",
        "GLOBIN GENE ANALYSIS",
        "CODON ANALYSED",
        "A1AT GENOTYPE",
    ],
    "LAB-COMMENTS": [
        "COMMENT",
        "SAMPLE COMMENT",
        "UNPROCESSED SAMPLE COMT",
        "HEPATITIS B E SCREEN",
        "ACUTE HEPATITIS SCREEN",
        "SUPPLEMENTARY REPORT",
        "SUPPLEMENTARY REPORT 1",
        "SUPPLEMENTARY REPORT 2",
        "SUPPLEMENTARY REPORT 3",
        "SUPPLEMENTARY REPORT 4",
        "SUPPLEMENTARY REPORT 5",
        "PCR COMMENT",
        "SEROLOGY COMMENT",
        "SAMPLE RELATED COMMENT",
        "RESISTANCE COMMENT",
        "HCV PCR COMMENT",
        "LABORATORY COMMENT",
        "HBV PCR COMMENT",
        "DOCTOR'S COMMENT",
        "REFERENCE RANGE COMMENT",
        "ALLERGEN COMMENT",
        "COMMENT ON SAMPLE",
        "HCV RESISTANCE COMMENT",
        "LAB COMMENT 2",
        "REFERRED TEST",
        "TIME OF COLLECTION",
        "TEST DO NOT UE",
        "VOID - DO NOTUSE!",
        "SURFACE COVERAGE",
        "DIAG CYTO SUPPLEMENTARY 2",
        "PORPHYRIN REFERRAL",
        "REFERRED TO REF LAB",
        "REFERRED MOL HEP TEST",
        "SAMPLE ACKNOWLEDGEMENT",
        "TEMP TEST CODE",
        "UNPROCESSED SAMPLE",
        "NO SAMPLE DATE AND TIME",
        "HOSPITAL SOURCE",
        "TEMP TEST CODE DO NOT USE",
        "CSF SAMPLE RECIEVED",
        "REFERRAL LABORATORY",
        "ESOTERIC TEST",
        "TEST DO NOT USE",
        "REFERENCE LAB REPORT",
        "TDM INCOMPLETE LIST",
        "COLLECTION PERIOD [HRS]",
        "TPPA TEST PLEASE USE TPPS",
    ],
    "SPECIALITY-ALLERGY": [
        "MAST CELL TRYPTASE",
        # food and chemical allergy tests
        "OTHER SINGLE ALLERGEN",
        "RICE",
        "PEAR",
        "POTATO",
        "CHILIPEPPER",
        "CRAB",
        "MUSHROOM (CHAMPIGNON)",
        "MAIZE, CORN",
        "PEA",
        "OAT",
        "HONEY BEE",
        "COFFEE",
        "MANGO",
        "AUBERGINE",
        "MOSQUITO",
        "AVOCADO",
        "WHITE BEAN",
        "GARLIC",
        "BROCCOLI",
        "LOBSTER",
        "ONION",
        "MUSTARD",
        "BUCKWHEAT",
        "BARLEY",
        "MELON",
        "PLUM",
        "CHERRY",
        "PLAICE",
        "YEAST",
        "RAT EPITHELIUM",
        "TITANIUM",
        "HONEY",
        "PORK",
        "CARROT",
        "MUTTON",
        "OPIATES",
        "CELERY",
        "RASPBERRY",
        "THALLIUM",
        "GREEN BEAN",
        "PUMPKIN SEED",
        "LUPINE SEED",
        "BLACK PEPPER",
        "PAPRIKA, SWEET PEPPER",
        "RAPE SEED",
        "RYE",
        "SPINACH",
        "MIXED MOULD",
        "GOLD",
        "CHUB MACKEREL",
        "CUCUMBER",
        "CORIANDER",
        "CABBAGE",
        "POPPY SEED",
        "TETANUS TOXOID ANTIBODY",
        "COBALT AND CHROMIUM",
        "MILK",
        "HOUSE DUST MITE",
        "EGG WHITE",
        "WHEAT",
        "SOYA BEAN",
        "CAT DANDER",
        "MIXED TREE POLLEN",
        "DOG DANDER",
        "MIXED NUTS",
        "PEANUT",
        "MUSK ANTIBODY",
        "EGG YOLK",
        "TUNA",
        "MIXED SEAFOOD",
        "COR-A-8 HAZEL (LTP)",
        "COR-A-1 HAZEL (PR-10)",
        "SILVER BIRCH POLLEN",
        "MIXED WEED POLLEN",
        "CASHEW NUT",
        "SESAME SEED",
        "HAZELNUT",
        "FISH (COD)",
        "ALMOND",
        "CHEESE, CHEDDAR TYPE",
        "MIXED FOOD",
        "SHRIMP",
        "WALNUT",
        "BLUE MUSSEL",
        "BRAZIL NUT",
        "STRAWBERRY",
        "PISTACHIO",
        "SALMON",
        "LATEX",
        "MUGWORT",
        "GLUTEN",
        "APPLE",
        "PECAN NUT",
        "LENTIL",
        "COCONUT",
        "HORSE DANDER",
        "CHICKEN MEAT",
        "CASEIN",
        "BANANA",
        "MIXED FEATHERS",
        "GOAT MILK",
        "ORANGE",
        "COMMON WASP",
        "LEMON",
        "PINEAPPLE",
        "CACAO",
        "PEACH",
        "MIXED GRASS POLLEN",
        "BEEF",
        "GRAPE",
        "CHICK PEA",
        "BUDGERIGAR FEATHERS",
        "HAMSTER EPITHELIUM",
        "CHEESE, MOULD TYPE",
        "RABBIT EPITHELIUM",
        "HAZEL POLLEN",
        "GUINEA PIG EPITHELIUM",
        "SUNFLOWER SEED",
        "ALTERNARIA ALTERNATA",
        "CLADOSPORIUM HERBARUM",
        "ARA-H-2 PEANUT",
        "TOMATO",
        "ETHYLENE OXIDE",
        "ARA-H-1 PEANUT",
        "KIWI",
        "MACADAMIA NUT",
        "MOUSE EPITHELIUM",
        "SWEET CHESTNUT",
        "SARDINE (PILCHARD)",
        "ARA-H-6 PEANUT",
        "ARA-H-8 PEANUT",
        "ARA-H-9 PEANUT (LTP)",
        "COR-A-9 HAZEL NUT",
        "COR-A-14 HAZEL NUT",
        "PINE NUT, PIGNOLES",
        "RJUG R 1 WALNUT",
        "ANA-O-3 CASHEW NUT",
        "RJUG R 3 LTP, WALNUT",
        "ARA-H-3 PEANUT",
    ],
    "SPECIALITY-ANTENATAL-CLINIC": [
        "SYPHILIS ANC REQUESTS",
        "ANC HAEMOGLOBINOPATHY SCR",
        "ANTE-NATAL SCREEN",
    ],
    "SPECIALITY-CARDIOLOGY": [
        "CARDIAC TROPONIN T",
        "TROPONIN I",
        "NT PRO-BNP",  # N-terminal pro-brain natriuretic peptide
        "LACTATE DEHYDROGENASE",  # old test for cardiac damage
        "CARDIAC PROFILE",
        "CK ISOENZYMES",
        "CK MB [FRACTION]",

    ],
    "SPECIALITY-CRITICAL-CARE": [
        "ARTERIAL BLOOD GASES",
        "UREA AND ELECTROLYTES",
        "LIVER PROFILE",
        "C REACTIVE PROTEIN",
        "MAGNESIUM",
        "CARDIAC TROPONIN T",
        "ATYPICALPNEUMONIA PCR",
    ],
    "SPECIALITY-ENDOCRINOLOGY": [
        # thyroid tests
        "THYROID FUNCTION TESTS",
        "TSH",
        "FT3",
        "THYROGLOBULIN (BHAM)",
        # cortisol related tests
        "CORTISOL AT 9AM",
        "CORTISOL",
        "SHORT SYNACTHEN TEST",
        "EXTENDED SYNACTHEN TEST",
        "CORTISOL BINDING GLOBULIN",
        "CORTISOL AT 9AM",
        # parathyroid
        "PTH",
        # pituitary hormones & relateds
        "FSH",
        "LH",
        "PROLACTIN",
        "OESTRADIOL",
        "TRH STIMULATION TEST",
        "TESTOSTERONE",
        "SHBG",
        "GNRH STIMULATION TEST",
        "17-0H PROGESTERONE",
        "170H PG STIMULATION TEST",
        "GROWTH HORMONE",
        "RENIN AND ALDOSTERONE",
        "URINE 5HIAA",
        "SOMATOSTATIN",
        "LEPTIN",
        "ANDROSTENEDIONE",
        "ADRENAL",
        "INTRAOPERATIVE PTH 10'",
        "PANCREATIC ISLET CELL",
        "INTRAOPERATIVE PTH 5'",
        "HYDROCORTISONE DAY CURVE",
        "EXT INSULIN STRESS TEST",
        "5 POINT DAY CURVE FOR GH",
        "CATECHOLAMINES [PLASMA]",
        "DIHYDROTESTOSTERONE",
        "INSULIN TOLERANCE TEST",
        "INHIBIN B",
        "VIP",
        "HIRSUTE",  # PRL, 170h-prog, etc local panel
        "ANTI-MULLERIAN (ADULT)",
        "ANTI-MULLERIAN (CHILD)",
        "PTH RELATED PROTEIN",
    ],
    "SPECIALITY-GASTROENTEROLOGY": [
        "TISSUE TRANSGLUTAMINASE",
        "ENDOMYSIAL IGG ABS",
        "ENDOMYSIAL IGA AB",
        "HELICO. PYLORI  AGN. TEST",
        "GASTROENTERITIS PCR",
        "CEA",
        "FAECAL CALPROTECTIN",
        "GUT HORMONE PROFILE",
        "SOMATOSTATIN",
        "GASTRIN",

    ],
    "SPECIALITY-HAEMATOLOGY": [
        # (clinical medical speciality, as distinct from the namesake lab discipline)
        # hypercoagulable states
        "FVII MUTATION ANALYSIS",
        "FX MUTATION ANALYSIS",
        # general
        "APTT",
        "TOTAL IRON BINDING CAPACI",
        # haematological malignancies
        "BONE MARROW - 2",
        "BONE MARROW - 1",
        "HTLV I + II ANTIBODIES",
        "HTLV 1+2 PROVIRAL DNA",
        # haemophilia
        "90MIN POST DDAVP",
        "PRE DDAVP TRIAL",
        "4HR POST DDAVP",
        "DDAVP ADMINISTRATION",
        "PRE DDAVP-HAEMA",
        "4HR DDAVP - HAEM A",
        "6HR POST DDAVP",
        "6HR DDAVP - HAEM A",
        "2HR DDAVP - HAEM A",
        "30MIN DDAVP - HAEM A",
        "1HR DDAVP-HAEM A",
        "30MIN POST DDAVP",
        "2HR POST DDAVP",
        "1HR POST DDAVP",
        "PRE VW:AG DDAVP TRIAL",
        "HAEM A MUTATION ANALYSIS",
        "HAEM B MUTATION ANALYSIS",
    ],
    "SPECIALITY-NEPHROLOGY": [
        "URINE PROTEIN/CR RATIO",
        "UREA AND ELECTROLYTES",
        "URINE ALB:CREAT RATIO",
        "CREATININE CLEARANCE",
        "EGFR (C+G)",
        "ERYTHROPOIETIN LEVEL",
        "EGFR (MDRD)",
        "RENIN",
        "RDU PRE HOLIDAY SCREEN",
        "RDU POST HOLIDAY",
    ],
    "SPECIALITY-RHEUMATOLOGY": [
        "RHEUMATOID FACTOR",
        " ANTI NUCLEAR AB",  # leading space is in source document
        "LUPUS SCREEN",
        "ENA CHARACTERISATION",
        "CCP ANTIBODY",
        "ANCA",
        "MYOSITIS AUTOANTIBODIES",
        "DS DNA ABS",
        "ENA BATTERY",
        "MPO + PR3 IGG ANTIBODIES",
        "PR3 AB",
        "TISSUE BATTERY",  # Anti-Mito-Ab Anti-SM-Ab panel
        "HLA B5701",
        "HLA 27",
    ],
    "SPECIALITY-SEXUAL-HEALTH": [
        "GENITAL SWAB",
        "HIV 1 + 2 ANTIBODIES",
        "CHLAMYDIA / GC SDA ASSAY",
        "SYPHILIS SEROLOGY",
        "SYPHILIS ANC REQUESTS",
        "HIGH VAGINAL SWAB",
        "HEPATITIS B SURFACE AG",
        "HIV AB AVIDITY*DO NOT USE",
        "STD SCREEN - TV",
    ],
    "UNTAGGED": [
    ]
    # sample test results for these may aid in identification
    "AMBIGUOUS": [
        "COM3 TEST",
        "TPAI1:AG",
        "TGT PPP (5PM)",
        "PIVKA II",
        "TGT (PPP LOW)",
        "TISSUE DISACCHARIDES",
        "TPA:AC",
        "SAMPLE RELATED COMM CELLS",
        "HSPU CHEMISTRY I-STAT",
        "HAEM MOLECULAR REF LAB",
        "PAP-8 AGGREGATION PANEL 1",
        "MTHFR",
        "HSPU CHEMISTRY PICCOLO",
        "ROTEM 0.12PM TF (CTI)",
        "PFA-100",
        "PML-RARA T(15:17)",
        "CHRONOLOG PANEL 1",
        "PEPH/IFIX/SLCH",
        "NEUROMUSCULAR PATH",
        "NEUROM SUPP REP 1",
        "2HR POST PFA-100",
        "DUPLEX PT3' + FVG",
        "BET-V-1",
        "IMPACT-R",
        "PI"  # possibly has internal meaning?
        "PEPH AND IFIX",
        "NBT TEST",
        "HSPU HAEMATOLOGY FBC",
        "FBC PART 1",
        "PROLIFERATION LYMPHOPREP",
        "TCR V-BETA REPERTOIRE",
        "RDU 6 MONTHLY SCREEN",  # references RDU ?local
        "NRTI",  # could be a few things
        "NNRTI",  # typo or related to NRTI?
        "REQ RULE TRIGGER",
        "RDU 3 MONTHLY SCREEN",
        "MQC1",
        "COLLAGEN 2 UG/ML",
        "MQC2",
        "BTC REFERRAL",
        "COLLAGEN/ADRENALINE",
        "COLLAGEN/ADP",
        "PROLIFERATION WHOLE BLOOD",
        "BCR-ABL T(9:22)",  # ? a biblical reference ?
        "GALACTO. AGN. REF. LAB.",
        "BTC REFERRAL F(OLD)",
        "COLLAGEN REC PEP 1.0UG/ML",
        "LP AI",
        "C-KIT",
        "MIXED MEAL TEST",  # allergy test?
        "RDU PRE HOLIDAY SCREEN",
        "RDU POST HOLIDAY",
        "PURINE/PYRAMIDINE REFERR",
        "REST OF PS1 TESTS",
        "NEQAS LIPIDS LINE 2",
        "PIS:",
        "TRAVEL FEVER SCREEN",
        "BARNET LAB NUMBER",
        "LEUKAEMIA ASSOC TRANSLOC.",
        "RH+K PHENOTYPING",
        "ELUTION - ANTIBODY",
        "SUPP REPORT LEGACY",
        "AP50 (ALTERNATE)",
        "CAM (DO NOT USE)",
        "RFC (CODE NOT IN USE)",
        "HBH INCLUSIONS",
        "DEB TEST",
        "CITM VAL: LIPASE",
        "RIQASI1",
        "1HR POST IMPACT-R",
        "2HR POST IMPACT-R",
        "1HOUR POST PFA-100",
        "IMPACT-R ASPIRIN TEST",
        "SUPP REPORT PM LGCY",
        "LP (A)",
        "ADRENALINE 5UM",
        "ADRENALINE 10 UM",
        "PARTNER/PATIENT X-REF",
        "ADP 5UM",
        "ADP 10 UM",
        "FLOATING BETA",
        "NRTIS",
        "ENHANCED LIVER FIBROSIS",
        "OVOMUCOID",
    ],
}

# this is a modified version of the tag-list inversion method
# from api.py - used here for interactive testing
def invert_lookups(tag_list):
    inverted_tag_list = defaultdict(list)

    for tag, test_names in tag_list.items():
        for test_name in test_names:
            inverted_tag_list[test_name].append(tag)

    return inverted_tag_list
