from collections import defaultdict
from itertools import chain

"""
TOP-LEVEL TAB GROUPINGS:

BIOCHEMISTRY = OTHER-BIOCHEMISTRY + SERUM-BIOCHEMISTRY + URINE-BIOCHEMISTRY
HAEMATOLOGY = HAEMATOLOGY-LAB + TRANSFUSION + COAGULATION
INFECTION = MICROBIOLOGY + VIROLOGY
OTHER = IMMUNOLOGY + HISTOCYTOPATHOLOGY + GENETICS + LAB-COMMENTS
"""

_LAB_TEST_TAGS = {
    "ALLERGY-TESTS": [
        "ALMOND",
        "ALTERNARIA ALTERNATA",
        "ANA-O-3 CASHEW NUT",
        "APPLE",
        "ARA-H-1 PEANUT",
        "ARA-H-2 PEANUT",
        "ARA-H-3 PEANUT",
        "ARA-H-6 PEANUT",
        "ARA-H-8 PEANUT",
        "ARA-H-9 PEANUT (LTP)",
        "AUBERGINE",
        "AVOCADO",
        "BANANA",
        "BARLEY",
        "BEEF",
        "BLACK PEPPER",
        "BLUE MUSSEL",
        "BRAZIL NUT",
        "BROCCOLI",
        "BUCKWHEAT",
        "BUDGERIGAR FEATHERS",
        "CABBAGE",
        "CACAO",
        "CARROT",
        "CASEIN",
        "CASHEW NUT",
        "CAT DANDER",
        "CELERY",
        "CHEESE, CHEDDAR TYPE",
        "CHEESE, MOULD TYPE",
        "CHERRY",
        "CHICK PEA",
        "CHICKEN MEAT",
        "CHILIPEPPER",
        "CHUB MACKEREL",
        "CLADOSPORIUM HERBARUM",
        "COBALT AND CHROMIUM",
        "COCONUT",
        "COFFEE",
        "COMMON WASP",
        "COR-A-1 HAZEL (PR-10)",
        "COR-A-14 HAZEL NUT",
        "COR-A-8 HAZEL (LTP)",
        "COR-A-9 HAZEL NUT",
        "CORIANDER",
        "CRAB",
        "CUCUMBER",
        "DOG DANDER",
        "EGG WHITE",
        "EGG YOLK",
        "ETHYLENE OXIDE",
        "FISH (COD)",
        "GARLIC",
        "GLUTEN",
        "GOAT MILK",
        "GOLD",
        "GRAPE",
        "GREEN BEAN",
        "GUINEA PIG EPITHELIUM",
        "HAMSTER EPITHELIUM",
        "HAZEL POLLEN",
        "HAZELNUT",
        "HONEY BEE",
        "HONEY",
        "HORSE DANDER",
        "HOUSE DUST MITE",
        "KIWI",
        "LATEX",
        "LEMON",
        "LENTIL",
        "LOBSTER",
        "LUPINE SEED",
        "MACADAMIA NUT",
        "MAIZE, CORN",
        "MANGO",
        "MELON",
        "MILK",
        "MIXED FEATHERS",
        "MIXED FOOD",
        "MIXED GRASS POLLEN",
        "MIXED MOULD",
        "MIXED NUTS",
        "MIXED SEAFOOD",
        "MIXED TREE POLLEN",
        "MIXED WEED POLLEN",
        "MOSQUITO",
        "MOUSE EPITHELIUM",
        "MUGWORT",
        "MUSHROOM (CHAMPIGNON)",
        "MUSK ANTIBODY",
        "MUSTARD",
        "MUTTON",
        "OAT",
        "ONION",
        "OPIATES",
        "ORANGE",
        "OTHER SINGLE ALLERGEN",
        "PAPRIKA, SWEET PEPPER",
        "PEA",
        "PEACH",
        "PEANUT",
        "PEAR",
        "PECAN NUT",
        "PINE NUT, PIGNOLES",
        "PINEAPPLE",
        "PISTACHIO",
        "PLAICE",
        "PLUM",
        "POPPY SEED",
        "PORK",
        "POTATO",
        "PUMPKIN SEED",
        "RABBIT EPITHELIUM",
        "RAPE SEED",
        "RASPBERRY",
        "RAT EPITHELIUM",
        "RICE",
        "RJUG R 1 WALNUT",
        "RJUG R 3 LTP, WALNUT",
        "RYE",
        "SALMON",
        "SARDINE (PILCHARD)",
        "SESAME SEED",
        "SHRIMP",
        "SILVER BIRCH POLLEN",
        "SOYA BEAN",
        "SPINACH",
        "STRAWBERRY",
        "SUNFLOWER SEED",
        "SWEET CHESTNUT",
        "TETANUS TOXOID ANTIBODY",
        "THALLIUM",
        "TITANIUM",
        "TOMATO",
        "TUNA",
        "WALNUT",
        "WHEAT",
        "WHITE BEAN",
        "YEAST",
    ],
    "COAGULATION": [
        "1HR DDAVP-HAEM A",
        "1HR POST DDAVP",
        "2HR DDAVP - HAEM A",
        "2HR POST DDAVP",
        "30MIN DDAVP - HAEM A",
        "30MIN POST DDAVP",
        "4HR DDAVP - HAEM A",
        "4HR POST DDAVP",
        "6HR DDAVP - HAEM A",
        "6HR POST DDAVP",
        "90MIN POST DDAVP",
        "90MIN VWF:RCO",
        "ALPHA 2 ANTIPLASMIN:AC",
        "ANTI XA ASSAY",
        "ANTI-PLATELET FACTOR 4",
        "ANTI-PLATELET FACTOR 4",
        "ANTITHROMBIN:AC",
        "ANTITHROMBIN:AG",
        "APTT (MANUAL)",
        "APTT 50:50 MIX",
        "APTT AND HEPARIN RATIO",
        "APTT INHIBITOR SCREEN",
        "APTT",
        "CHROMOGENIC F8 INHIBITORS",
        "CITRATE PLATELET COUNT",
        "CLOTTING SCREEN",
        "CRYOFIBRINOGEN SCREEN",
        "D-DIMER",
        "DALTEPARIN ANTI XA LEVEL",
        "DANAPAROID ANTI XA LEVEL",
        "DDAVP ADMINISTRATION",
        "DIRECT ANTIGLOBULIN TEST",
        "ENOXAPARIN ANTI XA LEVEL",
        "F IX INHIBITORS",
        "F VIII POST TREATMENT",
        "FACTOR 11 ANTIGEN",
        "FACTOR H LEVEL",
        "FACTOR I LEVEL",
        "FACTOR II ASSAY (POST)",
        "FACTOR II BIOASSAY",
        "FACTOR IX:AG",
        "FACTOR IX:C ASSAY (POST)",
        "FACTOR IX:C ASSAY",
        "FACTOR V BIOASSAY",
        "FACTOR V LEIDEN GENOTYPE",
        "FACTOR VII BIOASSAY",
        "FACTOR VII:AG ELISA",
        "FACTOR VIII BINDING ASSAY",
        "FACTOR VIII:C BIOASSAY",
        "FACTOR X ASSAY (POST)",
        "FACTOR X BIOASSAY",
        "FACTOR X1 ASSAY",
        "FACTOR XI ASSAY (POST)",
        "FACTOR XI INHIBITORS",
        "FACTOR XII ASSAY",
        "FACTOR XIII A SUBUNIT",
        "FACTOR XIII B SUBUNIT",
        "FACTOR XIII SCREEN",
        "FDPS",  # fibrin degradation products
        "FIBRINOGEN ANTIGEN",
        "FIBRINOGEN",
        "FVIII CHROMOGENIC",
        "FVIII CVS ANALYSIS",
        "FVIII INHIBITORS",
        "FVIII:AG ELISA",
        "FXIII ACTIVITY",
        "HAEM A CARRIER DETECTION",
        "HEPARIN RATIO",
        "HMW KININOGEN",
        "HSPU HAEMATOLOGY COAG",
        "INR",
        "INTRINSIC PATHWAY ASSAYS",
        "PLASMINOGEN:AC",
        "PLATELET AGGREGATION",
        "PRE DDAVP TRIAL",
        "PRE DDAVP-HAEMA",
        "PRE VW:AG DDAVP TRIAL",
        "PROTEIN C:AC",
        "PROTEIN C:AG",
        "PROTEIN C:F VII RATIO",
        "PROTEIN S (FREE) BIOASSAY",
        "PROTEIN S FREE: LATEX",
        "PROTEIN S:TOTAL",
        "PROTHROMBIN 3' UTR VARIAN",
        "PROTHROMBIN F 1+2",
        "PROTHROMBIN TIME (MANUAL)",
        "PROTHROMBIN TIME",
        "PROTHROMBOTIC SCREEN 1",
        "REPTILASE TIME",
        "RISTOCETIN 0.75 MG/ML",
        "RISTOCETIN 1.2 MG/ML",
        "THROMBIN TIME",
        "THROMBOELASTOMETRY",
        "TPA:AG",
        "UFH (ANTI XA LEVEL)",
        "UFH (APTT RATIO)",
        "VWD TYPE 2 A/B/M ANALYSIS",
        "VWD TYPE 2N ANALYSIS",
        "VWF COLLAGEN BINDING POST",
        "VWF COLLAGEN BINDING PRE",
        "VWF INHIBITOR SCREEN",
        "VWF MULTIMERS",
        "VWF: AG LATEX ASSAY",
        "VWF: RICOF ASSAY",
        "VWF:AB LATEX",
        "VWF:AC",
        "VWF:AG (POST)",
        "VWF:AG (PRE)",
        "VWF:AG",
        "VWF:CB",
        "VWF:RCO DOSE",
        "VWF:RICOF ASSAY (POST)",
        "VWF:RICOF ASSAY (PRE)",
    ],
    "DRUG-LEVELS": [
        # for both therapeutic monitoring and toxicology purposes
        "ADALIMUMAB PROFILE",
        "AMIKACIN LEVEL",
        "AMIODARONE",
        "AMITRIPTYLINE",
        "AMOXICILLOYL",
        "ANTIBIOTIC ASSAY",
        "ANTIFUNGAL DRUG ASSAY",
        "APIXABAN LEVEL",
        "ARGATROBAN (APTT RATIO)",
        "BARBITURATES",
        "CARBAMAZEPINE",
        "CLOBAZAM",
        "CLONAZEPAM",
        "CLOZAPINE/NORCLOZAPINE",
        "CYCLOSERINE LEVEL ASSAY",
        "CYCLOSPORIN",
        "DIGOXIN",
        "ETHANOL",
        "ETHOSUXIMIDE",
        "FLUCYTOSINE LEVEL ASSAY",
        "FONDAPARINUX LEVEL",
        "GABA-PENTIN",
        "GENTAMICIN LEVEL",
        "INFLIXIMAB PROFILE",
        "INSULIN",
        "LAMOTRIGINE",
        "LEVETIRACETAM",
        "LITHIUM",
        "METHADONE",
        "METHANOL",
        "METHOTREXATE",
        "MYCOPHENOLIC ACID",
        "NORTRIPTYLINE",
        "OLANZAPINE",
        "OXCARBAZEPINE",
        "PARACETAMOL",
        "PENICILLOYL V",
        "PHENOBARBITONE",
        "PHENYTOIN",
        "PREDNISOLONE",
        "QUANTIFERON TB GOLD IT",
        "RIVAROXABAN LEVEL",
        "SALICYLATE",
        "SIROLIMUS",
        "TACROLIMUS",
        "TEICOPLANIN LEVEL",
        "THEOPHYLLINE",
        "THYROID FUNCTION TESTS",  # for monitoring thyroxine dosing
        "TINZAPARIN ANTIXA LEVEL",
        "TOPIRAMATE",
        "TRICYCLIC ANTIDEPRESSANTS",
        "VALPROATE",
        "VANCOMYCIN LEVEL",
        "WARFARIN MONITOR",
    ],
    "GENETICS": [
        "A1AT GENOTYPE",
        "AT MUTATION ANALYSIS",
        "CALR MUTATION ANALYSIS",
        "CODON ANALYSED",
        "CODONS ANALYSED:",
        "F11 MUTATION ANALYSIS",
        "FVII MUTATION ANALYSIS",
        "FX MUTATION ANALYSIS",
        "GAUCHER'S DIS MUTATION",
        "GLOBIN GENE ANALYSIS",
        "HAEM A MUTATION ANALYSIS",
        "HAEM B MUTATION ANALYSIS",
        "HFE (HH) GENE MUTATION",
        "IG MUTATION ANALYSIS",
        "JAK-2",
        "JAK2 EXON12 MUTATION TEST",
        "MPL MUTATION ANALYSIS",
        "PROC MUTATION ANALYSIS",
        "PROS1 MUTATION ANALYSIS",
        "T-CELL GENE ANALYSIS",
    ],
    "HAEMATOLOGY-LAB": [
        "ANC HAEMOGLOBINOPATHY SCR",
        "AUTO HAEMOLYSIS TEST",
        "CAM HB ELECTROPHORESIS",
        "ESR",  # debatable - who does the ESRs in a lab? biochem/haem?
        "FILM REPORT",  # report from a blood film microscopy
        "FULL BLOOD COUNT RNOH",
        "FULL BLOOD COUNT",
        "HAEM B CARRIER DETECTION",
        "HAEMOGLOBINOPATHY SCREEN-",
        "HAEMOGLOBINOPATHY SCREEN",
        "HB VARIANT FURTHER INVEST",
        "HEINZ BODIES",
        "LYMPHOCYTE SUBSETS",
        "OSMOTIC FRAGILITY TEST",
        "PLASMA VISCOSITY",
        "PLATELET AGGREGATION",
        "REFLEX HAEMOGLOBINOPATHY",
        "RETIC - RNOH",
        "RETICULOCYTE COUNT",
    ],
    "HISTOCYTOPATHOLOGY": [
        "BONE / TISSUE / BIOPSY",
        "BONE MARROW - 1",
        "BONE MARROW - 2",
        "CJD REFERRAL",
        "CSF REPORT",  # csf cytology
        "DIAG CYTO SUPP 2",
        "DIAG CYTO SUPP 3",
        "DIAG CYTO SUPP 4",
        "DIAGNOSTIC CYTOLOGY",
        "GUT BIOPSY",
        "GYNAE CYTOLOGY 1",
        "HISTOLOGY",
        "URINE SPERMATAZOA TEST",

    ],
    "IMMUNOLOGY": [
        "ACETYCHOLINE RECEPTOR AB",
        "ANA BATTERY",
        "ANTI IGA ABS",
        "ANTI M2 AB",
        "ANTI NEURONAL AB REFERRAL",
        "ANTI NEURONAL ANTIBODIES",
        "ANTI STREPTOLYSIN O ABS",
        "ANTI-C1Q ANTIBODY",
        "ANTI-GABAB RECEPTOR AB",
        "ANTI-GAD AB",
        "ANTI-GAD ANTIBODY",
        "ANTI-HISTONE ANTIBODY",
        "ANTI-MPO/PR3/GBM BLOT",
        "ANTI-NMDA RECEPTOR AB",
        "ANTI-SRP",
        "ANTI-VGCC ANTIBODY",
        "ANTI-VGKC ANTIBODY",
        "AQUAPORIN 4 ANTIBODY",
        "BASAL GANGLIA ANTIBODIES",
        "C3 NEPHRITIC FACTOR",
        "CARDIOLIPIN IGM",
        "COMPLEMENT C3D",
        "DAT (SHORT PROFILE)",  # direct antiglobulin test
        "ENDOMYSIAL IGG ABS",
        "FUNCTIONAL C1IN",
        "GANGLIOSIDE ANTIBODIES",
        "GLIADIN IGG + IGA",
        "GLYCINE RECEPTOR ANTIBODY",
        "HLA 27",
        "HLA B5701",
        "IG HEAVY CHAIN GENE ANAL",
        "IGA HEVYLITE CHAINS",
        "IGG HEVYLITE CHAINS",
        "IGM HEVYLITE CHAINS",
        "IMMUNODEFICIENCY PANEL",
        "IMMUNOFIXATION",
        "IMMUNOGLOBULIN A",
        "IMMUNOGLOBULIN D",
        "IMMUNOGLOBULIN G",
        "IMMUNOGLOBULIN M",
        "IMMUNOGLOBULINS",
        "IMMUNOGLOBULINS",
        "IMMUNOSUPPRESSION SCREEN",
        "JC ANTIBODY",
        "MAG ANTIBODIES",
        "MAST CELL TRYPTASE",
        "MPO + PR3 IGG ANTIBODIES",
        "PHOSPHOLIPASE A2 REC AB",
        "PNH CELL MARKER ANALYSIS",
        "PNH SCREEN",  # paroxysmal nocturnal haemoglobinuria
        "SERUM LIGHT CHAINS BN2",
        "SERUM LIGHT CHAINS",
        "SKIN ANTIBODIES",
        "STEROID CELL AB",
        "STRIATED MUSCLE AB",
        "TH17 PHENOTYPING",
        "TISSUE BATTERY",  # Anti-Mito-Ab Anti-SM-Ab panel
    ],
    "LAB-COMMENTS": [
        "ACUTE HEPATITIS SCREEN",
        "ALLERGEN COMMENT",
        "COLLECTION PERIOD [HRS]",
        "COMMENT ON SAMPLE",
        "COMMENT",
        "CSF SAMPLE RECIEVED",
        "DIAG CYTO SUPPLEMENTARY 2",
        "DOCTOR'S COMMENT",
        "ESOTERIC TEST",
        "HBV PCR COMMENT",
        "HCV PCR COMMENT",
        "HCV RESISTANCE COMMENT",
        "HEPATITIS B E SCREEN",
        "HOSPITAL SOURCE",
        "LAB COMMENT 2",
        "LABORATORY COMMENT",
        "NO SAMPLE DATE AND TIME",
        "PCR COMMENT",
        "PORPHYRIN REFERRAL",
        "REFERENCE LAB REPORT",
        "REFERENCE RANGE COMMENT",
        "REFERRAL LABORATORY",
        "REFERRED MOL HEP TEST",
        "REFERRED TEST",
        "REFERRED TO REF LAB",
        "RESISTANCE COMMENT",
        "SAMPLE ACKNOWLEDGEMENT",
        "SAMPLE COMMENT",
        "SAMPLE RELATED COMMENT",
        "SEROLOGY COMMENT",
        "SUPPLEMENTARY REPORT 1",
        "SUPPLEMENTARY REPORT 2",
        "SUPPLEMENTARY REPORT 3",
        "SUPPLEMENTARY REPORT 4",
        "SUPPLEMENTARY REPORT 5",
        "SUPPLEMENTARY REPORT",
        "SURFACE COVERAGE",
        "TDM INCOMPLETE LIST",
        "TEMP TEST CODE DO NOT USE",
        "TEMP TEST CODE",
        "TEST DO NOT UE",
        "TEST DO NOT USE",
        "TIME OF COLLECTION",
        "TPPA TEST PLEASE USE TPPS",
        "UNPROCESSED SAMPLE COMT",
        "UNPROCESSED SAMPLE",
        "VOID - DO NOTUSE!",
    ],
    "MICROBIOLOGY": [
        "AFB : CULTURE",  # 'AFB' = mostly tuberculosis
        "AFB : EARLY MORN. URINE",
        "AFB BLOOD CULTURE",
        "AMOEBIC ANTIBODIES",
        "ASP FUMIGATUS PPTNS",
        "ASPERGILLUS FUMIGATUS",
        "ASPERGILLUS PCR",
        "ATYPICALPNEUMONIA PCR",
        "BARTONELLA SEROLOGY",
        "BODETELLA PERTUSIS PCR",
        "BORDETELLA  ANTIBODIES",
        "BORRELIA BURGDORFERI ABS.",
        "BRONCHIAL WASHINGS",
        "BRUCELLA ABS. REF. LAB.",
        "BRUCELLA ANTIBODIES",
        "C.TRACHOMATIS ( LGV )",
        "CAMPYLOBACTER SEROLOGY",
        "CANDIDA  ANTIGEN TEST",
        "CANDIDA ALBICANS",
        "CANDIDA AURIS SCREEN",
        "CARBAPENEMASE SCREEN",
        "CH.TRACHOMATIS SDA URINE",
        "CHL.TRACHOMATIS SDA-ASSAY",
        "CHLAMYDIA / GC SDA ASSAY",
        "CHLAMYDIA SEROLOGY",
        "CLOST. DIFFICILE TOXIN",
        "COCCIDIOIDES ANTIBODIES",
        "COXIELLA ANTIBODIES",
        "CRITHIDIA",
        "CRYPTOCOCCUS AGN. (BLOOD)",
        "CRYPTOCOCCUS AGN. (CSF)",
        "CRYPTOSPORIDIUM MICRO.",
        "DIPHTHERIA ANTIBODIES",
        "E.COLI  O157  ANTIBODIES",
        "ENTEROVIRUS IGM",
        "EXTERNAL SOURCE-SEROL",
        "FILARIA ANTIBODIES",
        "FLOW CYTOMETRY",
        "FUNGAL 18 S PCR SCREEN",
        "FUNGAL EXAMINATION",
        "GASTROENTERITIS PCR",
        "H.PYLORI REF LAB TEST",
        "HAEMOPHILUS ANTIGEN",
        "HAEMOPHILUS INFLUENZAE AB",
        "HISTOPLASMA ANTIBODIES",
        "HISTOPLASMA ANTIGEN TEST",
        "HYDATID ANTIBODIES",
        "HYDATID ASPIRATE",
        "LEGIONELLA ABS. REF. LAB",
        "LEGIONELLA ANTIGEN TEST",
        "LEGIONELLA REF. LAB.",
        "LEISHMANIA ANTIBODIES",
        "LEISHMANIA CULTURE / PCR",
        "LEPTOSPIRA ANTIBODIES",
        "LEPTOSPIRA DNA DETECTION",
        "MALARIA ANTIBODIES",
        "MALARIA PARASITE SCREEN",
        "MALARIA PARASITE",
        "MENINGOCOCCAL ANTIBODIES",
        "MENINGOCOCCAL SCREEN :PCR",
        "MICROSPORIDIA MICROSCOPY",
        "MICROSPORIDIA PCR",
        "MISC. PARASITOLOGY",
        "MRSA MOLECULAR SCREEN",
        "MRSA SCREEN",
        "MYCO / UREAPLASMA PCR :",
        "MYCOPLASMA PNEUMONIAE PCR",
        "MYCOPLASMA SEROLOGY",
        "OVA CYST AND PARASITE",
        "P. JIROVECII PCR",
        "PARASITOLOGY : REF. LAB.",
        "PD FLUID",
        "PNEUMO. JIROVECII PCR",
        "PNEUMOCOCCAL C.P.  AB",
        "PNEUMOCOCCUS AGN.REF. LAB",
        "PNEUMOCOCCUS ANTIGEN",
        "PNEUMOCYSTIS PCR",
        "RABIES INVESTIGATIONS",
        "REF LAB URINE LEGIONELLA",
        "RESPIRATORY PCR",
        "RICKETTSIAL ANTIBODIES",
        "SCHISTOSOMA ANTIBODIES",
        "SCHISTOSOMES : URINE",
        "SEMEN CULTURE",
        "SEROTYPE PNEUMOCOCCAL AB",
        "SKIN SWAB",
        "STRONGYLOIDES ANTIBODIES",
        "STRONGYLOIDES CULTURE",
        "SYPHILIS ANC REQUESTS",
        "SYPHILIS SEROLOGY",
        "T-SPOT TB",
        "TB PCR TEST",
        "THREADWORM PREP.",
        "TOXO IGM REF LAB. TEST",
        "TOXOCARA SEROLOGY",
        "TOXOPLASMA B1 PCR",
        "TOXOPLASMA PCR. REF. LAB.",
        "TOXOPLASMA REF. LAB.",
        "TOXOPLASMA SEROLOGY",
        "TRICHINELLA  ANTIBODIES",
        "TROPHERYMA WHIPPELLII PCR",
        "URINE SCREENING TEST",  # flow cyto then culture
        "VRE SCREEN MC+S",
        "WIDAL TEST",
        "YERSINIA ANTIBODIES",
        "DRAIN FLUID",
        "IUCD",
        "BILE CULTURE",
        "CORNEAL SCRAPING",
        "SUPRA PUBIC ASPIRATE",
        "EAR SWAB",
        "CSU",
        "JOINT FLUID",
        "ENDOCERVICAL SWAB",
        "PLEURAL FLUID",
        "TIP CULTURE + SENS",
        "EYE SWAB",
        "NEPHROSTOMY FLUID",
        "ABSCESS SWAB",
        "RECTAL SWAB",
        "ULCER SWAB",
        "PERITONEAL FLUID",
        "BLOOD CULTURE",
        "HIGH VAGINAL SWAB",
        "STOOL CULTURE",
        "CSF  MICRO + CULTURE",
        "LOWER VAGINAL SWAB",
        "THROAT SWAB",
        "MISC. CULTURE",
        "FLUID CULTURE",
        "VAGINAL SWAB",
        "STD-URETHRAL SWAB",
        "GROIN SWAB",
        "SWAB - PLACENTA",
        "TONGUE SWAB",
        "MOUTH SWAB",
        "PERINEAL SWAB",
        "UMBILICAL SWAB",
        "PENILE SWAB",
        "STD-THROAT SWAB",
        "URETHRAL SWAB",
        "STD-RECTAL SWAB",
        "AXILLARY SWAB",
        "PERNASAL SWAB",
        "STD-CERVICAL SWAB",
        "LABIAL SWAB",
        "PUS - FLUID",
        "VULVAL SWAB",
        "CHLAMYDIA SWAB",
        "TRACHEOSTOMY SWAB",
        "DRAIN SWAB SITE - LK",
        "IV CATHETER SITE",
        "GENITAL SWAB",
        "WOUND SWAB CULTURE + SENS",
        "SPUTUM CULTURE",
        "NOSE SWAB",
        "ET TUBE ASPIRATE",
        "BONE MARROW CULTURE",
        "TRYPANOSOMAL ANTIBODIES",
        "FASCIOLA ANTIBODIES",
        "ELECTRON MICROSCOPY",
        "MYCO / UREAPLASMA CULTURE",
        "MISC. SEROLOGY",
        "MYCOPLASMA ABS. REF LAB.",
        "CSF SYPHILIS SEROLOGY",
        "ACINETOBACTER SCREEN",
        "EPIDEMIOLOGY SCREEN",
        "CYSTICERCOSIS ANTIBODIES",
        "STD SCREEN - GC",
        "HELICO. PYLORI SEROLOGY",
        "MYCOLOGY SEROLOGY",
        "REF. LAB. CHLAMYDIA ASSAY",
        "SULPHONYLUREA SCREEN",
        "CJD REFERRAL",
    ],
    "OTHER-BIOCHEMISTRY": [
        "BETA HCG [CSF]",
        "BODYFLUID GLUCOSE",
        "BODYFLUID UREA",
        "BODYFLUID CALCIUM",
        "BODYFLUID SODIUM",
        "BODYFLUID POTASSIUM",
        "BODYFLUID ENZ CREATININE",
        "BODYFLUID AMYLASE",
        "BODYFLUID PHOSPHATE",
        "BODYFLUID BILIRUBIN",
        "BODYFLUID LDH",
        "BODYFLUID PROTEIN",
        "BODYFLUID MAGNESIUM",
        "BODYFLUID CREATININE",
        "BODYFLUID CHLORIDE",
        "FLUID CA-125",
        "STONE ANALYSIS",
        "CSF PROTEIN",
        "CSF GLUCOSE",
        "POTASSIUM [WHOLE BLOOD]",
        "CHROMIUM [WHOLE BLOOD]",
        "LACTATE [WHOLE BLOOD]",
        "COBALT [WHOLE BLOOD]",
        "MANGANESE (WHOLE BLOOD)",
        "IONISED CALCIUM [WHOLE B]",
        "WHOLE BLOOD ACYLCARNITINE",
        "FAECAL POTASSIUM",
        "FAECAL REDUCING SUBS",
        "FAECAL CHROMATOGRAPHY",
        "FAECAL A1AT",
        "FAECAL PH",
        "FAECAL SODIUM",
        "FAECAL PORPHYRINS",
        "FAECAL CHYMOTRYPSIN",
        "FAECAL ELECTROLYTES",
        "ASCITIC FLUID",
        "FLUID ALBUMIN",
        "FLUID TRIGLYCERIDES",
        "PLACENTAL ALP",
        "FLUID PH",
        "FLUID CEA",
        "PD FLUID PROFILE",
        "FLUID CA-199",
        "FLUID AFP",
        "CITM VAL: FLUID 1",
        "CITM VAL: FLUID 2",
        "FLUID HCG",
        "FLUID ADENOSINE DEAMINASE",
        "FLUID OSMOLALITY",
        "LIVER IRON",
        "LIVER ALP",
        "AFP [CSF]",
        "CSF PIGMENTS",
        "LACTATE [CSF]",
        "ACE [CSF]",
        "CSF TAU PROTEIN",
        "CSF A-BETA 1-42",
        "NEQAS CSF",
        "CSF Tau/A Beta 142 ratio",
    ],
    "SERUM-BIOCHEMISTRY": [
        " ANTI NUCLEAR AB",  # leading space in source document
        "1,25 VITAMIN D",
        "11-DEOXYCORTISOL",
        "17-0H PROGESTERONE",
        "170H PG STIMULATION TEST",
        "25-OH VITAMIN D",
        "5 POINT DAY CURVE FOR GH",
        "A1AT PHENOTYPE",
        "ACE",
        "ACETOACETATE",
        "ACID PHOSPHATASE",
        "ACIDIFIED SERUM LYSIS",
        "ACTH",
        "ADAMTS13 ASSAY",
        "ADRENAL",
        "AFP",
        "ALBUMIN",
        "ALDOSTERONE",
        "ALKALINE PHOSPHATASE",
        "ALP ISOENZYMES",
        "ALPHA 1 ANTITRYSPIN",
        "ALT",
        "ALUMINIUM",
        "AMINO ACID CHROMATOG",
        "AMMONIA",
        "AMYLASE ISOENZYMES",
        "AMYLASE",
        "ANCA",
        "ANDROSTENEDIONE",
        "ANTE-NATAL SCREEN",  # panel may include other tests eg urine
        "ANTI-MULLERIAN (ADULT)",
        "ANTI-MULLERIAN (CHILD)",
        "ANTIBIOTIC ASSAY",
        "APO LIPOPROTEIN AI",
        "APO LIPOPROTEIN AII",
        "APO LIPOPROTEIN B",
        "APOE PHENOTYPE",
        "APTT",
        "ARGATROBAN LEVEL",
        "ARSENIC",
        "ARTERIAL BLOOD GASES",
        "AST",
        "AVIAN PRECIPITINS",
        "B-GLUCOSIDASE ACTIVITY",
        "B12 AND FOLATE SCREEN",
        "B2 GLYCOPROTEIN 1",
        "B2 MICROGLOBULIN",
        "BETA D GLUCAN TEST",
        "BETA HCG",
        "BETA-HYDROXYBUTARATE",
        "BETA-TRANSFERRIN",
        "BICARBONATE",
        "BILE ACIDS",
        "BILIARY ALP",
        "BIOTINIDASE",
        "BONE ALP",
        "BONE PROFILE",
        "C REACTIVE PROTEIN",
        "C-PEPTIDE",
        "C1 ESTERASE",
        "CA 125",
        "CA 153",
        "CA 199",
        "CAERULOPLASMIN",
        "CALCITONIN",
        "CALCIUM",
        "CARB. DEF. TRANSFERRIN",
        "CARBOXY-HAEMOGLOBIN",
        "CARDIAC PROFILE",
        "CARDIAC TROPONIN T",
        "CARDIOLIPIN",
        "CARNITINE",
        "CATECHOLAMINES [PLASMA]",
        "CCP ANTIBODY",
        "CEA",
        "CHLORIDE",
        "CHOLESTEROL",
        "CHOLESTEROL/TRIGLYCERIDES",
        "CHOLINESTERASE",
        "CHROMOGENIC F8 (BOVINE)",
        "CHROMOGRANIN A (IN HOUSE)",
        "CHROMOGRANIN A (SENDAWAY)",
        "CHROMOGRANIN A",
        "CHROMOGRANIN B",
        "CK ISOENZYMES",
        "CK MB [FRACTION]",
        "CK-MB",
        "COC-AMPHET RELATED TRANSC",
        "COLD AGGLUTININ  TITRE",
        "COLLAGEN BINDING ACTIVITY",
        "COMPLEMENT C2",
        "COMPLEMENT",
        "COPPER",
        "CORRECTED CALCIUM",
        "CORTISOL AT 9AM",
        "CORTISOL AT 9AM",
        "CORTISOL BINDING GLOBULIN",
        "CORTISOL",
        "CREATINE KINASE",
        "CREATININE CLEARANCE",  # requires both serum and urine test
        "CREATININE",
        "CRYOGLOBULIN",
        "CYCLOSERINE LEVEL ASSAY",
        "CYCLOSPORIN",
        "D-DIMER",
        "DABIGATRAN LEVEL",
        "DHEA-SULPHATE",
        "DHR (DIHYDRORHODAMINE)",
        "DIALYSATE SODIUM",
        "DIGOXIN",
        "DIHYDROTESTOSTERONE",
        "DIRECT LDL CHOLESTEROL",
        "DS DNA ABS",
        "EGFR (C+G)",
        "EGFR (MDRD)",
        "ENA BATTERY",
        "ENA CHARACTERISATION",
        "ENDOMYSIAL IGA AB",
        "ENZ CREAT CLEARANCE",
        "ENZ.CREATININE",
        "EOSIN-5-MALEIMIDE ASSAY",
        "ERYTHROCYTE PROTOPORPHYRI",
        "ERYTHROPOIETIN LEVEL",
        "ESR - RNOH",
        "ESR",
        "ETHANOL",
        "EXT INSULIN STRESS TEST",
        "EXTENDED SYNACTHEN TEST",
        "EXTRINSIC FACTOR ASSAYS",
        "FAECAL CALPROTECTIN",
        "FAECAL ELASTASE",
        "FAECAL OCCULT BLOOD",
        "FASTING GLUCOSE",
        "FERRITIN",
        "FIBRBLAST GROWTH FACTOR23",
        "FILM REPORT - RNOH",
        "FLUCYTOSINE LEVEL ASSAY",
        "FOLATE",
        "FREE ANDROGEN INDEX",
        "FREE FATTY ACIDS",
        "FREE PSA",
        "FRUCTOSAMINE",
        "FSH",
        "FT3",
        "FT4",
        "FUNCTIONAL COMPLEMENT",
        "G6PD ASSAY",
        "G6PD SCREEN",
        "GAL-1-P-URIDYLTRANSFERASE",
        "GALACTOMANNAN AGN. ELISA",
        "GAMMA-GT",
        "GASTRIN",
        "GBM AB",
        "GENTAMICIN LEVEL",
        "GLUCAGON TEST",
        "GLUCAGON",
        "GLUCOSE TOLERANCE TEST",
        "GLUCOSE",
        "GLYCATED HB (DCCT)",
        "GNRH STIMULATION TEST",
        "GP1B",
        "GROWTH HORMONE",
        "GTT - EXTENDED",
        "GTT (ACROMEGALY)",
        "GUT HORMONE PROFILE",
        "HAEMATINICS",
        "HAPTOGLOBIN",
        "HBA1C", "HBA1C (DCCT)"
        "HBSC",
        "HDL CHOLESTEROL",
        "HELICO. PYLORI  AGN. TEST",
        "HIGH SENSITIVE TROPONIN T",
        "HIGH SENSITIVITY CRP",
        "HIRSUTE",  # represents a panel of sex hormone tests
        "HOMOCYSTINE",
        "HSPU CHEMISTRY BLOOD GAS",
        "HSPU CHEMISTRY CRP",
        "HYDROCORTISONE DAY CURVE",
        "IGF BINDING PROTEIN 3",
        "IGF-1",
        "IGG4",
        "IL28B TEST",
        "IM TEST",
        "IMMUNOGLOBULIN G",
        "IMMUNOREACTIVE TRYPSIN",
        "INHIBIN B",
        "INHIBITOR TITRE (PORCINE)",
        "ININS",
        "INSULIN TOLERANCE TEST",
        "INTEGRASE",
        "INTESTINAL ALP",
        "INTRAOPERATIVE PTH 10'",
        "INTRAOPERATIVE PTH 15'",
        "INTRAOPERATIVE PTH 5'",
        "INTRAOPERATIVE PTH",
        "INTRINSIC FACTOR",
        "IRON CONCENTRATION",
        "IRON STUDIES (FER)",
        "IRON STUDIES",
        "LACTATE [PLASMA]",
        "LACTATE DEHYDROGENASE",
        "LDH ISOENZYMES",
        "LEAD",
        "LEPTIN",
        "LEUK A-GALACTOSIDASE",
        "LH",
        "LIPASE",
        "LIPID ELECTROPHORESIS",
        "LIPID FRACTIONATION",
        "LITHIUM",
        "LIVER PROFILE",
        "LIVER TISSUE COPPER",
        "LUPUS SCREEN",
        "LYSOZYME ASSAY",
        "MAGNESIUM",
        "MANNOSE BINDING LECTIN",
        "MAST CELL TRYPTASE",
        "MERCURY",
        "METHYL MALONIC ACID",
        "MYELOPEROXIDASE AB",
        "MYOSITIS AUTOANTIBODIES",
        "N-ACETYL GLUCOSAMINE",
        "NEQAS LIPIDS LINE 1",
        "NEQAS MONOCLONAL SERUM",
        "NEQAS PSA",
        "NT PRO-BNP",  # N-terminal pro-brain natriuretic peptide
        "OESTRADIOL",
        "OESTRADIOL",
        "OMEGA-5 GLIADIN",
        "OSMOLALITY",
        "OXALATE  [PLASMA]",
        "OXYGEN DISSOCIATION",
        "PAEDIATRIC PROFILE",
        "PANCREATIC ISLET CELL",
        "PANCREATIC POLYPEPTIDE",
        "PARACETAMOL",
        "PDF CA 125",
        "PENICILLOYL G",
        "PH",
        "PHOSPHATE",
        "PHYTANIC ACID",
        "PLACENTAL ALP ISOENZYME",
        "PLASMA A-GALACTOSIDASE",
        "PLASMA CHITOTRIOSIDASE",
        "PLASMA HAEMOGLOBIN",
        "PLASMA METADRENALINES",
        "PLASMINOGEN:AG",
        "PLATELET NUCLEOTIDES",
        "POTASSIUM",
        "PR3 AB",
        "PREALBUMIN",
        "PREKALLIKREIN",
        "PROCOLLAGEN III NP",
        "PROGESTERONE",
        "PROLACTIN",
        "PROTEASE (PR)",
        "PROTEASE:",
        "PROTEIN ELECTROPHORESIS",
        "PSA",
        "PTH RELATED PROTEIN",
        "PTH",
        "PYRIMIDINE 5'NUCLEOTIDASE",
        "PYRUVATE KINASE ASSAY",
        "PYRUVATE",
        "RBC ENZYME INTERMEDIATES",
        "RDU PRE-DIALYSIS SCREEN",
        "RED CELL FOLATE",
        "RED CELL MEMBRANE ANALY",
        "REFERRAL TFT",
        "REFERRED CREATININE",
        "REFERRED GLYCATED HB",
        "RENAL PROFILE",
        "RENIN AND ALDOSTERONE",
        "RETINOL BINDING PROTEIN",
        "REVERSE TRANSCRIPTASE",
        "RHEUMATOID FACTOR",
        "RISTOCETIN 1.0 MG/ML",
        "RNA POLYMERASE",
        "SALICYLATE",
        "SELENIUM",
        "SEROTONIN",
        "SERUM AMYLOID A",
        "SHBG",
        "SHORT SYNACTHEN TEST",
        "SIROLIMUS",
        "SODIUM",
        "SOMATOSTATIN",
        "SWEAT TEST",
        "TACROLIMUS",
        "TATC",
        "TESTOSTERONE",
        "THIO.PURINE METHYL T'ASE",
        "THIO.PURINE METHYL T'ASE",
        "THIOGUANINE NUCLEOTIDES",
        "THYROGLOBULIN (BHAM)",
        "THYROGLOBULIN ANTIBODY",
        "THYROGLOBULIN",
        "THYROID FUNCTION TESTS",
        "THYROID PEROXIDASE",
        "THYROXINE BINDING GLOBULI",
        "TISSUE TRANSGLUTAMINASE",
        "TOPIRAMATE",
        "TOTAL BILIRUBIN",
        "TOTAL IRON BINDING CAPACI",
        "TOTAL PROTEIN",
        "TOTAL T3",
        "TOTAL T4",
        "TRANSCOBALAMIN",
        "TRANSFERRIN GLYCOFORM",
        "TRH STIMULATION TEST",
        "TRIGLYCERIDES",
        "TROPONIN I",
        "TRYPSIN",
        "TSH RECEPTOR ANTIBODY",
        "TSH",
        "UNSTABLE HAEMOGLOBIN",
        "URATE",
        "UREA AND ELECTROLYTES",
        "UREA",
        "URINE 5HIAA",
        "VENOUS BLOOD PH",
        "VERY LONG CHAIN F. ACIDS",
        "VIP",
        "VITAMIN A",
        "VITAMIN B12",
        "VITAMIN B6",
        "VITAMIN E",
        "VITAMIN K LEVEL",
        "WHITE CELL CYSTINE",
        "WHITE CELL ENZYME SCREEN",
        "YEQAS FOB",
        "ZINC",
    ],
    "SPECIALITY-ALLERGY": [
        # all tests in a speciality group are also in at least one
        # other top-level group (eg biochem, micro, viro)
        "ALMOND",
        "ALTERNARIA ALTERNATA",
        "ANA-O-3 CASHEW NUT",
        "APPLE",
        "ARA-H-1 PEANUT",
        "ARA-H-2 PEANUT",
        "ARA-H-3 PEANUT",
        "ARA-H-6 PEANUT",
        "ARA-H-8 PEANUT",
        "ARA-H-9 PEANUT (LTP)",
        "AUBERGINE",
        "AVOCADO",
        "BANANA",
        "BARLEY",
        "BEEF",
        "BLACK PEPPER",
        "BLUE MUSSEL",
        "BRAZIL NUT",
        "BROCCOLI",
        "BUCKWHEAT",
        "BUDGERIGAR FEATHERS",
        "CABBAGE",
        "CACAO",
        "CARROT",
        "CASEIN",
        "CASHEW NUT",
        "CAT DANDER",
        "CELERY",
        "CHEESE, CHEDDAR TYPE",
        "CHEESE, MOULD TYPE",
        "CHERRY",
        "CHICK PEA",
        "CHICKEN MEAT",
        "CHILIPEPPER",
        "CHUB MACKEREL",
        "CLADOSPORIUM HERBARUM",
        "COBALT AND CHROMIUM",
        "COCONUT",
        "COFFEE",
        "COMMON WASP",
        "COR-A-1 HAZEL (PR-10)",
        "COR-A-14 HAZEL NUT",
        "COR-A-8 HAZEL (LTP)",
        "COR-A-9 HAZEL NUT",
        "CORIANDER",
        "CRAB",
        "CUCUMBER",
        "DOG DANDER",
        "EGG WHITE",
        "EGG YOLK",
        "ETHYLENE OXIDE",
        "FISH (COD)",
        "GARLIC",
        "GLUTEN",
        "GOAT MILK",
        "GOLD",
        "GRAPE",
        "GREEN BEAN",
        "GUINEA PIG EPITHELIUM",
        "HAMSTER EPITHELIUM",
        "HAZEL POLLEN",
        "HAZELNUT",
        "HONEY BEE",
        "HONEY",
        "HORSE DANDER",
        "HOUSE DUST MITE",
        "KIWI",
        "LATEX",
        "LEMON",
        "LENTIL",
        "LOBSTER",
        "LUPINE SEED",
        "MACADAMIA NUT",
        "MAIZE, CORN",
        "MANGO",
        "MAST CELL TRYPTASE",
        "MELON",
        "MILK",
        "MIXED FEATHERS",
        "MIXED FOOD",
        "MIXED GRASS POLLEN",
        "MIXED MOULD",
        "MIXED NUTS",
        "MIXED SEAFOOD",
        "MIXED TREE POLLEN",
        "MIXED WEED POLLEN",
        "MOSQUITO",
        "MOUSE EPITHELIUM",
        "MUGWORT",
        "MUSHROOM (CHAMPIGNON)",
        "MUSK ANTIBODY",
        "MUSTARD",
        "MUTTON",
        "OAT",
        "ONION",
        "OPIATES",
        "ORANGE",
        "OTHER SINGLE ALLERGEN",
        "PAPRIKA, SWEET PEPPER",
        "PEA",
        "PEACH",
        "PEANUT",
        "PEAR",
        "PECAN NUT",
        "PINE NUT, PIGNOLES",
        "PINEAPPLE",
        "PISTACHIO",
        "PLAICE",
        "PLUM",
        "POPPY SEED",
        "PORK",
        "POTATO",
        "PUMPKIN SEED",
        "RABBIT EPITHELIUM",
        "RAPE SEED",
        "RASPBERRY",
        "RAT EPITHELIUM",
        "RICE",
        "RJUG R 1 WALNUT",
        "RJUG R 3 LTP, WALNUT",
        "RYE",
        "SALMON",
        "SARDINE (PILCHARD)",
        "SESAME SEED",
        "SHRIMP",
        "SILVER BIRCH POLLEN",
        "SOYA BEAN",
        "SPINACH",
        "STRAWBERRY",
        "SUNFLOWER SEED",
        "SWEET CHESTNUT",
        "TETANUS TOXOID ANTIBODY",
        "THALLIUM",
        "TITANIUM",
        "TOMATO",
        "TUNA",
        "WALNUT",
        "WHEAT",
        "WHITE BEAN",
        "YEAST",
    ],
    "SPECIALITY-ANTENATAL-CLINIC": [
        # all tests in a speciality group are also in at least one
        # other top-level group (eg biochem, micro, viro)
        "ANC HAEMOGLOBINOPATHY SCR",
        "ANTE-NATAL SCREEN",
        "SYPHILIS ANC REQUESTS",
    ],
    "SPECIALITY-CARDIOLOGY": [
        # all tests in a speciality group are also in at least one
        # other top-level group (eg biochem, micro, viro)
        "CARDIAC PROFILE",
        "CARDIAC TROPONIN T",
        "CK ISOENZYMES",
        "CK MB [FRACTION]",
        "LACTATE DEHYDROGENASE",  # old test for cardiac damage
        "NT PRO-BNP",  # N-terminal pro-brain natriuretic peptide
        "TROPONIN I",

    ],
    "SPECIALITY-CRITICAL-CARE": [
        # all tests in a speciality group are also in at least one
        # other top-level group (eg biochem, micro, viro)
        "ARTERIAL BLOOD GASES",
        "ATYPICALPNEUMONIA PCR",
        "C REACTIVE PROTEIN",
        "CARDIAC TROPONIN T",
        "LIVER PROFILE",
        "MAGNESIUM",
        "UREA AND ELECTROLYTES",
    ],
    "SPECIALITY-ENDOCRINOLOGY": [
        # thyroid tests
        "17-0H PROGESTERONE",
        "170H PG STIMULATION TEST",
        "5 POINT DAY CURVE FOR GH",
        "ADRENAL",
        "ANDROSTENEDIONE",
        "ANTI-MULLERIAN (ADULT)",
        "ANTI-MULLERIAN (CHILD)",
        "CATECHOLAMINES [PLASMA]",
        "CORTISOL AT 9AM",
        "CORTISOL AT 9AM",
        "CORTISOL BINDING GLOBULIN",
        "CORTISOL",
        "DIHYDROTESTOSTERONE",
        "EXT INSULIN STRESS TEST",
        "EXTENDED SYNACTHEN TEST",
        "FSH",
        "FT3",
        "GNRH STIMULATION TEST",
        "GROWTH HORMONE",
        "HIRSUTE",  # PRL, 170h-prog, etc local panel
        "HYDROCORTISONE DAY CURVE",
        "INHIBIN B",
        "INSULIN TOLERANCE TEST",
        "INTRAOPERATIVE PTH 10'",
        "INTRAOPERATIVE PTH 5'",
        "LEPTIN",
        "LH",
        "OESTRADIOL",
        "PANCREATIC ISLET CELL",
        "PROLACTIN",
        "PTH RELATED PROTEIN",
        "PTH",
        "RENIN AND ALDOSTERONE",
        "SHBG",
        "SHORT SYNACTHEN TEST",
        "SOMATOSTATIN",
        "TESTOSTERONE",
        "THYROGLOBULIN (BHAM)",
        "THYROID FUNCTION TESTS",
        "TRH STIMULATION TEST",
        "TSH",
        "URINE 5HIAA",
        "VIP",
    ],
    "SPECIALITY-GASTROENTEROLOGY": [
        # all tests in a speciality group are also in at least one
        # other top-level group (eg biochem, micro, viro)
        "CEA",
        "ENDOMYSIAL IGA AB",
        "ENDOMYSIAL IGG ABS",
        "FAECAL CALPROTECTIN",
        "GASTRIN",
        "GASTROENTERITIS PCR",
        "GUT HORMONE PROFILE",
        "HELICO. PYLORI  AGN. TEST",
        "SOMATOSTATIN",
        "TISSUE TRANSGLUTAMINASE",

    ],
    "SPECIALITY-HAEMATOLOGY": [
        # all tests in a speciality group are also in at least
        # one other top-level group (eg biochem, micro, viro)
        # (clinical medical speciality, as distinct from the
        # namesake lab discipline)
        "1HR DDAVP-HAEM A",
        "1HR POST DDAVP",
        "2HR DDAVP - HAEM A",
        "2HR POST DDAVP",
        "30MIN DDAVP - HAEM A",
        "30MIN POST DDAVP",
        "4HR DDAVP - HAEM A",
        "4HR POST DDAVP",
        "6HR DDAVP - HAEM A",
        "6HR POST DDAVP",
        "90MIN POST DDAVP",
        "APTT",
        "BONE MARROW - 1",
        "BONE MARROW - 2",
        "DDAVP ADMINISTRATION",
        "FVII MUTATION ANALYSIS",
        "FX MUTATION ANALYSIS",
        "HAEM A MUTATION ANALYSIS",
        "HAEM B MUTATION ANALYSIS",
        "HTLV 1+2 PROVIRAL DNA",
        "HTLV I + II ANTIBODIES",
        "PRE DDAVP TRIAL",
        "PRE DDAVP-HAEMA",
        "PRE VW:AG DDAVP TRIAL",
        "TOTAL IRON BINDING CAPACI",
    ],
    "SPECIALITY-NEPHROLOGY": [
        # all tests in a speciality group are also in at least one other
        # top-level group (eg biochem, micro, viro)
        "CREATININE CLEARANCE",
        "EGFR (C+G)",
        "EGFR (MDRD)",
        "ERYTHROPOIETIN LEVEL",
        "RDU POST HOLIDAY",
        "RDU PRE HOLIDAY SCREEN",
        "RENIN",
        "UREA AND ELECTROLYTES",
        "URINE ALB:CREAT RATIO",
        "URINE PROTEIN/CR RATIO",
    ],
    "SPECIALITY-RHEUMATOLOGY": [
        # all tests in a speciality group are also in at least one
        # other top-level group (eg biochem, micro, viro)
        " ANTI NUCLEAR AB",  # leading space is in source document
        "ANCA",
        "CCP ANTIBODY",
        "DS DNA ABS",
        "ENA BATTERY",
        "ENA CHARACTERISATION",
        "HLA 27",
        "HLA B5701",
        "LUPUS SCREEN",
        "MPO + PR3 IGG ANTIBODIES",
        "MYOSITIS AUTOANTIBODIES",
        "PR3 AB",
        "RHEUMATOID FACTOR",
        "TISSUE BATTERY",  # Anti-Mito-Ab Anti-SM-Ab panel
    ],
    "SPECIALITY-SEXUAL-HEALTH": [
        # all tests in a speciality group are also in at least one
        # other top-level group (eg biochem, micro, viro)
        "CHLAMYDIA / GC SDA ASSAY",
        "GENITAL SWAB",
        "HEPATITIS B SURFACE AG",
        "HIGH VAGINAL SWAB",
        "HIV 1 + 2 ANTIBODIES",
        "HIV AB AVIDITY*DO NOT USE",
        "STD SCREEN - TV",
        "SYPHILIS ANC REQUESTS",
        "SYPHILIS SEROLOGY",
    ],
    "TRANSFUSION": [
        "ANTIBODY SCREEN",  # transfusion atypical antibody screen
        "BLOOD GROUP",
        "FETAL RHD GENOTYPING",
        "FULL BLOOD GROUP",
        "KLEIHAUER",
        "NEWBORN GROUP + DAT",
        "SAVE SERUM",
        "TRANSFUSION REACTION",
    ],
    "TUMOUR-MARKERS": [
        "CA 125",
        "CA 153",
        "CA 199",
        "CEA",
        "FAECAL CALPROTECTIN",
        "FLUID CA-125",
        "FREE PSA",
        "PSA",
        "TUMOUR MARK",
        "URINE 5HIAA",
    ],
    "UNTAGGED": [
    ],
    "URINE-BIOCHEMISTRY": [
        "24 HR URINE CALCIUM",
        "24 HR URINE CREATININE",
        "24 HR URINE ELECTROLYTES",
        "24 HR URINE IRON",
        "24 HR URINE MAGNESIUM",
        "24 HR URINE OXALATE",
        "24 HR URINE POTASSIUM",
        "24 HR URINE PROTEIN",
        "24 HR URINE SODIUM",
        "24 HR URINE URATE",
        "24 HR URINE UREA",
        "24 HR URINE ZINC",
        "24HR UR. IN ACID BOTTLE",
        "24HR UR. IN PLAIN BOTTLE",
        "24HR URINE CHLORIDE",
        "24HR URINE CYSTINE",
        "24HR URINE FREE CORTISOL",
        "24HR URINE PHOSPHATE",
        "BENCE JONES PROTEIN",
        "CITM VAL: URINE 1",
        "CREATININE CLEARANCE",  # is both a blood and a urine test
        "NEQAS MONOCLONAL BJP",
        "NEQAS URINE CHEMISTRIES",
        "OLIGOCLONAL BANDS",
        "OSMALITY",
        "PARAPROTEIN",
        "PROTEIN ELECTROPHORESIS",
        "UR AMINO ACID CHROMATOG",
        "UR. ETHANOL",
        "UR. GLYCOSAMINOGLYCANS",
        "UR. NAG/CREATININE RATIO",
        "UR. RBP/CREATININE RATIO",
        "UR.CALCIUM:CREAT RATIO",
        "URINE ALB:CREAT RATIO",
        "URINE ALBUMIN CONCENTR",
        "URINE ALBUMIN",
        "URINE AMYLASE CONC",
        "URINE BICARBONATE",
        "URINE BILIRUBIN",
        "URINE BLOOD",
        "URINE CADMIUM",
        "URINE CALCIUM CONCENTR",
        "URINE CHLORIDE",
        "URINE CITRATE",
        "URINE COPPER CONCENTR",
        "URINE COPPER",
        "URINE CREATININE CONCENTR",
        "URINE CYSTINE SCREEN",
        "URINE CYSTINE",
        "URINE CYSTINE/HOMOCYSTINE",
        "URINE DIPSTICK ANALYSIS",
        "URINE DRUG SCREEN",
        "URINE ELECTROLYTES",
        "URINE ELECTROPHORESIS",
        "URINE GLUCOSE",
        "URINE GLYCOLATE",
        "URINE HAEMOGLOBIN",
        "URINE HAEMOSIDERIN",
        "URINE IMMUNOFIXATION",
        "URINE IRON CONCENTRATION",
        "URINE KETONES",
        "URINE MAGNESIUM CONCENTR",
        "URINE MERCURY",
        "URINE METADRENALINES 24HR",
        "URINE METADRENALINES SPOT",
        "URINE MYOGLOBIN",
        "URINE NTX",
        "URINE ORGANIC ACIDS",
        "URINE OSMOLALITY",
        "URINE OXALATE CONCENTR",
        "URINE PBG",
        "URINE PH",
        "URINE PHOSPHATE CONC",
        "URINE PORPHYRINS",
        "URINE POTASSIUM CONCENTR",
        "URINE PREGNANCY TEST",
        "URINE PROTEIN CONCENTR",
        "URINE PROTEIN/CR RATIO",
        "URINE REDUCING SUGARS",
        "URINE SODIUM CONCENTR",
        "URINE STEROID PROFILE",
        "URINE STONE SPOT",
        "URINE SUGAR CHROMATOG",
        "URINE URATE CONCENTR",
        "URINE UREA CONCENTRATION",
        "URINE UROBILINOGEN",
        "URINE VOLUME",
        "URINE ZINC CONCENTRATION",
        "VB URINE",
    ],
    "VIROLOGY": [
        "ICDC ANNUAL SCREEN",
        # CMV
        "CMV AVIDITY SCREEN",
        "CMV PCR",
        "CMV IGM",
        "CMV IGG",
        "CMV ANTIVIRAL RESISTANCE",
        "CMV IGG AVIDITY",
        "SYPHILIS IGM ADD TEST",
        "GUTHRIE CARD CMV PCR",
        # EBV tests
        "EBV IGM/EBNA",
        "EBV VCA IGG",
        "EBV PCR",
        # HAV tests
        "HEPATITIS A IGG AB",
        # HBV tests
        "HBV PCR",
        "HEPATITIS B SURFACE AG",
        "HEPATITIS B E SCREEN",
        "HEP B E ANTIBODY",
        "HEP B CORE IGM",
        "HEP B CORE TOTAL",
        "HBV QUANTITATIVE 'S' AG",
        "HEP B SURFACE ANTIBODY",
        "HBV DNA",
        "PREVIOUS HEPATITIS SCREEN",
        "ANTI HBS",  # Antibodies to HepB Surface Antigen
        "ACUTE HEPATITIS SCREEN",
        "HEPATITIS B POSITIVE",
        "HBV GENOTYPING",
        "HEP B E ANTIGEN",
        # HCV tests
        "HCV PCR",
        "HEPATITIS C ANTIBODY",
        "HCV RNA QUANTITATIVE",
        "HCV NS5B DRUG RESISTANCE",
        # HDV tests
        "HDV QUANTITATIVE PCR",
        "HEPATITIS DELTA VIRUS RNA",
        "HEPATITIS DELTA VIRUS",
        # HEV tests
        "HEV SEROLOGY",
        "HEPATITIS E RNA",
        "HEPATITIS E IGG",
        "HEPATITIS E IGM",
        # HIV tests
        "HIV SECOND BLOOD SCREEN",
        "HIV-1 TROPISM",
        "HIV 1 + 2 ANTIBODIES",
        "HIV VIRAL LOAD PCR ASSAY",
        "HIV AB AVIDITY*DO NOT USE",
        "HIV 2 ANTIBODIES",
        "REFERRAL LAB HIV AVIDITY",
        "HIV-1 TROPISM ASSAY",
        "HIV CONFIRMATORY ASSAYS",
        "HIV1 INTEGRASE RESISTANCE",
        "INHOUSE HIV1 PROVIRAL DNA",
        "HIV PROVIRAL DNA",
        "HIV-2 VIRAL LOAD",
        "HIV-2 RESISTANCE",
        "QUALITATIVE HIV RNA",
        "CD8 ACTIVATION MARKERS",
        # VZV tests
        "VZV IGG EIA",
        "VZV PCR",
        # Rubella
        "RUBELLA PCR",
        "RUBELLA IGG AVIDITY",
        "RUBELLA IGG",
        "RUBELLA IGM",
        "ACUTE RUBELLA SCREEN",
        # HSV tests
        "HSV PCR",
        "CVID B CELL PHENOTYPING",
        "HSV 1 + 2 IGG AB",
        "HCV NS5A RESISTANCE",
        "HTLV I + II ANTIBODIES",
        "T CELL PHENOTYPING",
        "SWINE FLU PCRS",
        # parvovirus
        "PARVOVIRUS B19",
        "PARVOVIRUS B19 IGM",
        "BK PCR",  # BK virus
        "PARVOVIRUS B19 DNA",
        "ADENOVIRUS PCR",
        "TRANSPLANT SCREEN -HIV",
        # HHV
        "HSV / VZV PCR",
        "HSV TYPE SPECIFIC AB",
        "VZV IGM",
        "HUMAN HERPES VIRUS 6",
        "HUMAN HERPES VIRUS 7",
        "HUMAN HERPES VIRUS 8",
        "HCV GENOTYPE",
        # dengue
        "DENGUE SEROLOGY",
        "DENDUE IGG SEROLOGY",
        "DENGUE PCR",
        # mumps
        "ACUTE MUMPS SCREEN",
        "MUMPS IGG",
        "MUMPS IGM",
        "MUMPS PCR",
        # measles
        "MEASLES IGM",
        "ACUTE MEASLES SCREEN",
        "MEASLES PCR",
        "MEASLES IGG",
        # other
        "WEST NILE ANTIBODIES",
        "EBOLA VIRUS RNA",
        "ENTEROVIRUS PCR",
        "FLU A TYPING PCR",
        "16 R RNA UNIV. BACT. PCR",
        "JC PCR",
        "APCRV",
        "HTLV 1+2 PROVIRAL DNA",
        "ARBOVIRUS PCR",
        "PAEDIATRIC RSV POCT",
        "LASSA FEVER PCR",
        "ALPHAVIRUS ANTIBODY",
        "ZIKA VIRUS",
        "FLAVIVIRUS ANTIBODIES",
        "ARBOVIRUS SEROLOGY",
        "ACUTE PARVOVIRUS SCREEN",
        "HANTAVIRUS SEROLOGY",
        "VIRUS GENOTYPE",
        "INFLUENZA RESISTANCE TEST",
        "ENCEPHALITIS SCREEN",
        "STD SCREEN - TV",
        "TH17 PHENOTYPING",
    ],
    # sample test results for these may aid in identification
    "AMBIGUOUS": [
        "1HOUR POST PFA-100",
        "1HR POST IMPACT-R",
        "2HR POST IMPACT-R",
        "2HR POST PFA-100",
        "ADP 10 UM",
        "ADP 5UM",
        "ADRENALINE 10 UM",
        "ADRENALINE 5UM",
        "AP50 (ALTERNATE)",
        "BARNET LAB NUMBER",
        "BCR-ABL T(9:22)",  # ? a biblical reference ?
        "BET-V-1",
        "BTC REFERRAL F(OLD)",
        "BTC REFERRAL",
        "C-KIT",
        "CAM (DO NOT USE)",
        "CHRONOLOG PANEL 1",
        "CITM VAL: LIPASE",
        "COLLAGEN 2 UG/ML",
        "COLLAGEN REC PEP 1.0UG/ML",
        "COLLAGEN/ADP",
        "COLLAGEN/ADRENALINE",
        "COM3 TEST",
        "DEB TEST",
        "DUPLEX PT3' + FVG",
        "ELUTION - ANTIBODY",
        "ENHANCED LIVER FIBROSIS",
        "FBC PART 1",
        "FLOATING BETA",
        "GALACTO. AGN. REF. LAB.",
        "HAEM MOLECULAR REF LAB",
        "HBH INCLUSIONS",
        "HSPU CHEMISTRY I-STAT",
        "HSPU CHEMISTRY PICCOLO",
        "HSPU HAEMATOLOGY FBC",
        "IMPACT-R ASPIRIN TEST",
        "IMPACT-R",
        "LEUKAEMIA ASSOC TRANSLOC.",
        "LP (A)",
        "LP AI",
        "MIXED MEAL TEST",  # allergy test?
        "MQC1",
        "MQC2",
        "MTHFR",
        "NBT TEST",
        "NEQAS LIPIDS LINE 2",
        "NEUROM SUPP REP 1",
        "NEUROMUSCULAR PATH",
        "NNRTI",  # typo or related to NRTI?
        "NRTI",  # could be a few things
        "NRTIS",
        "OVOMUCOID",
        "PAP-8 AGGREGATION PANEL 1",
        "PARTNER/PATIENT X-REF",
        "PEPH AND IFIX",
        "PEPH/IFIX/SLCH",
        "PFA-100",
        "PI"  # possibly has internal meaning?
        "PIS:",
        "PIVKA II",
        "PML-RARA T(15:17)",
        "PROLIFERATION LYMPHOPREP",
        "PROLIFERATION WHOLE BLOOD",
        "PURINE/PYRAMIDINE REFERR",
        "RDU 3 MONTHLY SCREEN",
        "RDU 6 MONTHLY SCREEN",  # references RDU ?local
        "RDU POST HOLIDAY",
        "RDU PRE HOLIDAY SCREEN",
        "REQ RULE TRIGGER",
        "REST OF PS1 TESTS",
        "RFC (CODE NOT IN USE)",
        "RH+K PHENOTYPING",
        "RIQASI1",
        "ROTEM 0.12PM TF (CTI)",
        "SAMPLE RELATED COMM CELLS",
        "SUPP REPORT LEGACY",
        "SUPP REPORT PM LGCY",
        "TCR V-BETA REPERTOIRE",
        "TGT (PPP LOW)",
        "TGT PPP (5PM)",
        "TISSUE DISACCHARIDES",
        "TPA:AC",
        "TPAI1:AG",
        "TRAVEL FEVER SCREEN",
    ],
}


# group the tests into top-level groups
_LAB_TEST_TAGS["BIOCHEMISTRY"] = list(chain(
    _LAB_TEST_TAGS["OTHER-BIOCHEMISTRY"],
    _LAB_TEST_TAGS["URINE-BIOCHEMISTRY"],
    _LAB_TEST_TAGS["SERUM-BIOCHEMISTRY"],
    _LAB_TEST_TAGS["DRUG-LEVELS"],
    _LAB_TEST_TAGS["TUMOUR-MARKERS"],
    ))

_LAB_TEST_TAGS["HAEMATOLOGY"] = list(chain(
    _LAB_TEST_TAGS["COAGULATION"],
    _LAB_TEST_TAGS["HAEMATOLOGY-LAB"],
    _LAB_TEST_TAGS["TRANSFUSION"],
))

_LAB_TEST_TAGS["INFECTION"] = list(chain(
    _LAB_TEST_TAGS["MICROBIOLOGY"],
    _LAB_TEST_TAGS["VIROLOGY"],
))

_LAB_TEST_TAGS["OTHER"] = list(chain(
    _LAB_TEST_TAGS["GENETICS"],
    _LAB_TEST_TAGS["HISTOCYTOPATHOLOGY"],
    _LAB_TEST_TAGS["IMMUNOLOGY"],
    _LAB_TEST_TAGS["LAB-COMMENTS"],
    _LAB_TEST_TAGS["ALLERGY-TESTS"],
))

_LAB_TEST_TAGS["ALL-TESTS"] = list(chain(
    _LAB_TEST_TAGS["BIOCHEMISTRY"],
    _LAB_TEST_TAGS["HAEMATOLOGY"],
    _LAB_TEST_TAGS["INFECTION"],
    _LAB_TEST_TAGS["OTHER"],
))


def invert_lookups(tag_list):
    # this is a modified version of the tag-list inversion method
    # from api.py - used here for interactive testing
    inverted_tag_list = defaultdict(list)

    for tag, test_names in tag_list.items():
        for test_name in test_names:
            inverted_tag_list[test_name].append(tag)

    return inverted_tag_list


LAB_TEST_TAGS = invert_lookups(_LAB_TEST_TAGS)
