# Generated by Django 2.0.13 on 2021-07-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnoh', '0002_rnohdemographics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rnohdemographics',
            options={'verbose_name': 'RNOH Demographics'},
        ),
    ]
