# Generated by Django 2.0.13 on 2021-07-30 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0062_auto_20210730_1042'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0040_auto_20201007_1346'),
        ('rnoh', '0003_auto_20210730_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='RNOHMicrobiology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('sample_date', models.DateField(blank=True, null=True)),
                ('hospital', models.CharField(blank=True, max_length=255, null=True)),
                ('number_positive', models.IntegerField(blank=True, null=True)),
                ('number_samples', models.IntegerField(blank=True, null=True)),
                ('sample_type', models.CharField(blank=True, choices=[('Tissue', 'Tissue'), ('Fluid', 'Fluid'), ('Sonication', 'Sonication'), ('Pus', 'Pus'), ('W/S', 'W/S'), ('MSU', 'MSU'), ('CSU', 'CSU'), ('Urine', 'Urine'), ('Sputum', 'Sputum'), ('Stool', 'Stool'), ('CSF', 'CSF')], max_length=200, null=True)),
                ('side', models.CharField(blank=True, choices=[('R', 'R'), ('L', 'L')], max_length=100, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('bottle', models.CharField(blank=True, choices=[('O2', 'O2'), ('AnO2', 'AnO2'), ('Both', 'Both'), ('Paed', 'Paed')], max_length=200, null=True)),
                ('day_positive', models.IntegerField(blank=True, null=True)),
                ('culture', models.CharField(blank=True, choices=[('Pend', 'Pend'), ('Flagging', 'Flagging'), ('NG 24', 'NG 24'), ('NG 48', 'NG 48'), ('NG', 'NG')], max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('organism_ft', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rnoh_rnohmicrobiology_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode')),
                ('organism_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elcid.MicrobiologyOrganism')),
                ('resistances', models.ManyToManyField(blank=True, related_name='resistances', to='opal.Antimicrobial')),
                ('sensitivities', models.ManyToManyField(blank=True, related_name='sensitivities', to='opal.Antimicrobial')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rnoh_rnohmicrobiology_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
