# Generated by Django 2.0.13 on 2021-07-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnoh', '0004_rnohmicrobiology'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rnohmicrobiology',
            options={'verbose_name': 'RNOH Microbiology'},
        ),
        migrations.RenameField(
            model_name='rnohmicrobiology',
            old_name='culture',
            new_name='result',
        ),
    ]
