# Generated by Django 2.0.13 on 2021-08-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnoh', '0008_auto_20210813_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='opatepisodes',
            name='administration',
            field=models.CharField(blank=True, choices=[('Self', 'Self'), ('Family', 'Family'), ('Carer', 'Carer'), ('District Nurse', 'District Nurse'), ('HAH', 'HAH'), ('Private Local', 'Private Local'), ('OPAT', 'OPAT'), ('Local A&E', 'Local A&E'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='opatepisodes',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opatepisodes',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opatepisodes',
            name='opat_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opatepisodes',
            name='supply',
            field=models.CharField(blank=True, choices=[('RNOH', 'RNOH'), ('GP', 'GP'), ('Local hospital', 'Local hospital'), ('Private', 'Private')], max_length=200, null=True),
        ),
    ]
