# Generated by Django 2.0.13 on 2022-03-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnoh', '0009_auto_20210813_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='RNOHConsultants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('system', models.CharField(blank=True, max_length=255, null=True, verbose_name='System')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Code')),
                ('version', models.CharField(blank=True, max_length=255, null=True, verbose_name='Version')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='rnohmicrobiology',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('Tissue', 'Tissue'), ('Fluid', 'Fluid'), ('Sonication', 'Sonication'), ('Pus', 'Pus'), ('W/S', 'W/S'), ('MSU', 'MSU'), ('CSU', 'CSU'), ('Urine', 'Urine'), ('Sputum', 'Sputum'), ('Stool', 'Stool'), ('CSF', 'CSF'), ('NPS', 'NPS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rnohmicrobiology',
            name='test_name',
            field=models.CharField(blank=True, choices=[('Blood Culture', 'Blood Culture'), ('Covid-19', 'Covid-19'), ('Culture', 'Culture'), ('MRSA Screen', 'MRSA Screen'), ('CPE Screen', 'CPE Screen')], max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rnohconsultants',
            unique_together={('code', 'system')},
        ),
    ]
