# Generated by Django 2.0.13 on 2022-03-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnoh', '0011_rnohteams'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnohteams',
            name='clinic',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='rnohteams',
            name='new_results',
            field=models.NullBooleanField(verbose_name='New results'),
        ),
        migrations.AddField(
            model_name='rnohteams',
            name='pending_ref_lab',
            field=models.NullBooleanField(verbose_name='Pending ref lab results'),
        ),
    ]
