# Generated by Django 2.2.16 on 2023-01-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnoh', '0012_auto_20220331_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opatepisodes',
            options={'verbose_name': 'OPAT Episodes'},
        ),
        migrations.AlterField(
            model_name='opatepisodes',
            name='opat_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='OPAT end date'),
        ),
    ]
