# Generated by Django 2.2.16 on 2022-12-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnoh', '0012_auto_20220331_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opatepisodes',
            options={'verbose_name': 'OPAT Episodes'},
        ),
        migrations.AddField(
            model_name='opatepisodes',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rnohactions',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rnohdemographics',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rnohmicrobiology',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rnohteams',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='opatepisodes',
            name='opat_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='OPAT end date'),
        ),
    ]
