# Generated by Django 2.2.16 on 2025-03-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnoh', '0013_auto_20221201_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='opatepisodes',
            name='further_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
