# Generated by Django 2.2.16 on 2025-03-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnoh', '0014_opatepisodes_further_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnohteams',
            name='mdt_knee',
            field=models.NullBooleanField(verbose_name='MDT-Knee'),
        ),
        migrations.AlterField(
            model_name='rnohteams',
            name='new_results',
            field=models.NullBooleanField(verbose_name='New-results'),
        ),
        migrations.AlterField(
            model_name='rnohteams',
            name='pending_ref_lab',
            field=models.NullBooleanField(verbose_name='Pending-ref-lab-results'),
        ),
    ]
