# Generated by Django 2.2.16 on 2025-03-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnoh', '0015_auto_20250312_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnohmicrobiology',
            name='site',
            field=models.CharField(blank=True, choices=[('Abdomen', 'Abdomen'), ('Ankle', 'Ankle'), ('Arm', 'Arm'), ('Back', 'Back'), ('Buttock', 'Buttock'), ('Calf', 'Calf'), ('Clavicle', 'Clavicle'), ('C-Spine', 'C-Spine'), ('Ear', 'Ear'), ('Elbow', 'Elbow'), ('Femur', 'Femur'), ('Fibula', 'Fibula'), ('Hip', 'Hip'), ('Humerus', 'Humerus'), ('Ilium Ischium', 'Ilium Ischium'), ('Ischial tuberosity', 'Ischial tuberosity'), ('Knee', 'Knee'), ('Leg', 'Leg'), ('L-Spine', 'L-Spine'), ('Nephrostomy', 'Nephrostomy'), ('Pelvis', 'Pelvis'), ('Pubis', 'Pubis'), ('Radius', 'Radius'), ('Sacrum', 'Sacrum'), ('Shoulder', 'Shoulder'), ('Spine', 'Spine'), ('Suprapubic', 'Suprapubic'), ('Tibia', 'Tibia'), ('Thigh', 'Thigh'), ('Throat', 'Throat'), ('T-spine', 'T-spine'), ('Ulnar', 'Ulnar'), ('Wrist', 'Wrist')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rnohmicrobiology',
            name='test_name',
            field=models.CharField(blank=True, choices=[('Blood Culture', 'Blood Culture'), ('Covid-19', 'Covid-19'), ('Culture', 'Culture'), ('MRSA Screen', 'MRSA Screen'), ('CPE Screen', 'CPE Screen'), ('Respiratory Virus Screen', 'Respiratory Virus Screen'), ('Candida Auris Screen', 'Candida Auris Screen'), ('Serology', 'Serology'), ('PCR', 'PCR')], max_length=200, null=True),
        ),
    ]
