# Generated by Django 2.2.16 on 2025-03-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnoh', '0016_auto_20250313_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rnohmicrobiology',
            name='result',
        ),
        migrations.AddField(
            model_name='rnohmicrobiology',
            name='status',
            field=models.CharField(blank=True, choices=[('Pend', 'Pend'), ('Flagging', 'Flagging')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rnohmicrobiology',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('Tissue', 'Tissue'), ('Fluid', 'Fluid'), ('Sonication', 'Sonication'), ('Pus', 'Pus'), ('W/S', 'W/S'), ('MSU', 'MSU'), ('CSU', 'CSU'), ('Urine', 'Urine'), ('Sputum', 'Sputum'), ('Stool', 'Stool'), ('CSF', 'CSF'), ('NPS', 'NPS'), ('Blood', 'Blood')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rnohmicrobiology',
            name='side',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('L', 'L'), ('Anterior', 'Anterior'), ('Posterior', 'Posterior')], max_length=100, null=True),
        ),
    ]
