# Generated by Django 2.2.16 on 2025-03-15 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0040_auto_20201007_1346'),
        ('rnoh', '0018_rnohmicrobiology_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='RNOHSBAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_id', models.IntegerField(blank=True, null=True)),
                ('mrn', models.CharField(blank=True, max_length=200, null=True)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('forename', models.CharField(blank=True, max_length=200, null=True)),
                ('dob', models.CharField(blank=True, max_length=200, null=True)),
                ('ward', models.CharField(blank=True, max_length=200, null=True)),
                ('consultant', models.CharField(blank=True, max_length=200, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('instructions', models.CharField(blank=True, max_length=200, null=True)),
                ('t8', models.TextField(blank=True, null=True)),
                ('extra1', models.TextField(blank=True, null=True)),
                ('extra3', models.TextField(blank=True, null=True)),
                ('extra4', models.TextField(blank=True, null=True)),
                ('extra5', models.TextField(blank=True, null=True)),
                ('extra7', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rnoh_sbar', to='opal.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRNOHSBARStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('has_sbar', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rnoh_patientrnohsbarstatus_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rnoh_patientrnohsbarstatus_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
