# Generated by Django 2.2.16 on 2025-03-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnoh', '0019_patientrnohsbarstatus_rnohsbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnohsbar',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
