# Generated by Django 2.2.16 on 2025-03-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnoh', '0020_auto_20250315_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rnohsbar',
            options={'ordering': ['sql_id']},
        ),
    ]
