# Generated by Django 2.2.16 on 2025-10-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnoh', '0021_auto_20250317_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnohteams',
            name='complex_opat',
            field=models.NullBooleanField(verbose_name='Complex-OPAT'),
        ),
    ]
