# Generated by Django 2.2.16 on 2025-11-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnoh', '0022_rnohteams_complex_opat'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnohdemographics',
            name='epic_hospital_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rnohmicrobiology',
            name='site',
            field=models.CharField(blank=True, choices=[('Abdomen', 'Abdomen'), ('Ankle', 'Ankle'), ('Arm', 'Arm'), ('Back', 'Back'), ('Buttock', 'Buttock'), ('Calf', 'Calf'), ('Clavicle', 'Clavicle'), ('C-Spine', 'C-Spine'), ('Ear', 'Ear'), ('Elbow', 'Elbow'), ('Femur', 'Femur'), ('Fibula', 'Fibula'), ('Hip', 'Hip'), ('Humerus', 'Humerus'), ('Ilium Ischium', 'Ilium Ischium'), ('Ischial tuberosity', 'Ischial tuberosity'), ('Knee', 'Knee'), ('Leg', 'Leg'), ('L-Spine', 'L-Spine'), ('Nephrostomy', 'Nephrostomy'), ('No Site', 'No Site'), ('Pelvis', 'Pelvis'), ('Pubis', 'Pubis'), ('Radius', 'Radius'), ('Sacrum', 'Sacrum'), ('Shoulder', 'Shoulder'), ('Spine', 'Spine'), ('Suprapubic', 'Suprapubic'), ('Tibia', 'Tibia'), ('Thigh', 'Thigh'), ('Throat', 'Throat'), ('T-spine', 'T-spine'), ('Ulnar', 'Ulnar'), ('Wrist', 'Wrist')], max_length=255, null=True),
        ),
    ]
