# Generated by Django 2.2.16 on 2026-01-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnoh', '0023_auto_20251127_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rnohmicrobiology',
            options={'ordering': ('sample_date',), 'verbose_name': 'Microbiology'},
        ),
    ]
