# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-15 13:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intrahospital_api', '0004_remove_externaldemographics_reconciled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaldemographics',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intrahospital_api_externaldemographics_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='externaldemographics',
            name='ethnicity_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opal.Ethnicity'),
        ),
        migrations.AlterField(
            model_name='externaldemographics',
            name='sex_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opal.Gender'),
        ),
        migrations.AlterField(
            model_name='externaldemographics',
            name='title_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opal.Title'),
        ),
        migrations.AlterField(
            model_name='externaldemographics',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_intrahospital_api_externaldemographics_subrecords', to=settings.AUTH_USER_MODEL),
        ),
    ]
