# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-22 17:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrahospital_api', '0007_auto_20180216_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPatientLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField()),
                ('stop', models.DateTimeField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('start',),
            },
        ),
        migrations.AddField(
            model_name='initialpatientload',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initialpatientload',
            name='start',
            field=models.DateTimeField(default=datetime.date(2018, 2, 22)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initialpatientload',
            name='stop',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
