# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-05 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intrahospital_api', '0009_auto_20180223_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initialpatientload',
            options={'ordering': ('started',)},
        ),
    ]
