# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-05 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intrahospital_api', '0010_auto_20180305_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchpatientload',
            options={'ordering': ('-started',)},
        ),
        migrations.AlterModelOptions(
            name='initialpatientload',
            options={'ordering': ('-started',)},
        ),
    ]
