# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-29 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrahospital_api', '0010_auto_20180305_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchpatientload',
            name='state',
            field=models.CharField(blank=True, choices=[(b'running', b'running'), (b'failure', b'failure'), (b'success', b'success'), (b'cancelled', b'cancelled')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='initialpatientload',
            name='state',
            field=models.CharField(blank=True, choices=[(b'running', b'running'), (b'failure', b'failure'), (b'success', b'success'), (b'cancelled', b'cancelled')], max_length=255, null=True),
        ),
    ]
