# Generated by Django 2.0.9 on 2018-11-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrahospital_api', '0010_auto_20180305_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaldemographics',
            name='ethnicity_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='externaldemographics',
            name='sex_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='externaldemographics',
            name='title_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
