# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-26 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrahospital_api', '0010_auto_20180305_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchpatientload',
            name='service_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
