# Generated by Django 2.0.9 on 2018-12-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrahospital_api', '0011_batchpatientload_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchpatientload',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='externaldemographics',
            name='ethnicity_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='externaldemographics',
            name='sex_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='externaldemographics',
            name='title_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
