# Generated by Django 2.0.13 on 2020-05-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrahospital_api', '0011_auto_20190205_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldemographics',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Death'),
        ),
        migrations.AddField(
            model_name='externaldemographics',
            name='death_indicator',
            field=models.BooleanField(default=False, help_text='This field will be True if the patient is deceased.'),
        ),
    ]
