# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-15 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrahospital_api', '0011_auto_20181114_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchpatientload',
            name='service_name',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
    ]
