# Generated by Django 2.0.9 on 2018-12-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrahospital_api', '0012_batchpatientload_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchpatientload',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
