# Generated by Django 2.0.13 on 2019-12-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrahospital_api', '0012_upstreamlabtestrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Abnormal_Flag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Accession_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_ADDRESS_LINE1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_ADDRESS_LINE2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_ADDRESS_LINE3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_ADDRESS_LINE4',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_Deceased_Flag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_EMAIL',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_Ethnic_Group',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_Forename1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_Forename2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_GP_NATIONAL_CODE',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_GP_PRACTICE_CODE',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_HOME_TELEPHONE',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_MAIN_LANGUAGE',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_MARITAL_STATUS',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_MOBILE_TELEPHONE',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_NATIONALITY',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_NHS_Number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_NOK_ADDRESS1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_NOK_ADDRESS2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_NOK_ADDRESS3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_NOK_ADDRESS4',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_NOK_FORENAME1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_NOK_FORENAME2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_NOK_HOME_TELEPHONE',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_NOK_MOBILE_TELEPHONE',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_NOK_POST_CODE',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_NOK_RELATIONSHIP',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_NOK_SURNAME',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_NOK_TYPE',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_NOK_WORK_TELEPHONE',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_Postcode',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_Religion',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_SEX',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_Surname',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_Title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='CRS_WORK_TELEPHONE',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Department',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Encounter_Consultant_Code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Encounter_Consultant_Name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Encounter_Consultant_Type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Encounter_Location_Code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Encounter_Location_Name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Encounter_Location_Type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Firstname',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='MSH_Control_ID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='OBR_Priority',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='OBR-5_Priority'),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='OBR_Sequence_ID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='OBR_Status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='OBR_exam_code_ID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='OBR_exam_code_Text',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='OBX_Sequence_ID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='OBX_Status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='OBX_exam_code_ID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='OBX_exam_code_Text',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Order_Number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Patient_Class',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Patient_ID_External',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Patient_Number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Relevant_Clinical_Info',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Requesting_Clinician',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Result_ID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Result_Range',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Result_Units',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Result_Value',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='SEX',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Specimen_Site',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Surname',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='Visit_Number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='visible',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
