# Generated by Django 2.0.13 on 2021-10-28 10:26

from django.db import migrations
from intrahospital_api import constants


def add(apps, schema_editor):
    Role = apps.get_model("opal", "Role")
    UserProfile = apps.get_model("opal", "UserProfile")

    role, _ = Role.objects.get_or_create(name=constants.SEND_TO_EPR)

    user_profiles = UserProfile.objects.filter(user__is_superuser=True)

    for user_profile in user_profiles:
        if not user_profile.roles.filter(
            id=role.id
        ):
            user_profile.roles.add(role)


def remove(apps, schema_editor):
    Role = apps.get_model("opal", "Role")
    Role.objects.filter(name=constants.SEND_TO_EPR).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('intrahospital_api', '0013_auto_20210329_1137'),
    ]

    operations = [
        migrations.RunPython(add, reverse_code=remove)
    ]
