# Generated by Django 2.0.13 on 2020-01-20 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrahospital_api', '0014_auto_20191227_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreamlabtestrow',
            name='PV1_3_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upstreamlabtestrow',
            name='PV1_3_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upstreamlabtestrow',
            name='PV1_7_CONSULTANT_NAME',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upstreamlabtestrow',
            name='PV1_7_C_NUMBER',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upstreamlabtestrow',
            name='obr_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upstreamlabtestrow',
            name='result_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamlabtestrow',
            name='opal_load_date',
            field=models.DateField(default=datetime.date(2020, 1, 20)),
        ),
    ]
