# Generated by Django 2.2.16 on 2023-01-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intrahospital_api', '0014_send_to_epr_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BatchPatientLoad',
        ),
    ]
