# Generated by Django 2.0.13 on 2020-05-18 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opal', '0037_auto_20181114_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upstream_id', models.IntegerField(blank=True, null=True)),
                ('msh_7', models.DateTimeField(blank=True, null=True)),
                ('msh_9_msg_type', models.CharField(blank=True, max_length=4, null=True)),
                ('evn_2_movement_date', models.DateTimeField(blank=True, null=True)),
                ('pid_3_mrn', models.CharField(blank=True, max_length=255, null=True)),
                ('pid_3_nhs', models.CharField(blank=True, max_length=255, null=True)),
                ('pid_18_account_number', models.CharField(blank=True, max_length=25, null=True)),
                ('pv1_2_patient_class', models.CharField(blank=True, max_length=50, null=True)),
                ('pv1_3_hospital', models.CharField(blank=True, max_length=50, null=True)),
                ('pv1_3_ward', models.CharField(blank=True, max_length=50, null=True)),
                ('pv1_3_room', models.CharField(blank=True, max_length=50, null=True)),
                ('pv1_3_bed', models.CharField(blank=True, max_length=50, null=True)),
                ('pv1_3_ambulatory_indicator', models.CharField(blank=True, max_length=50, null=True)),
                ('pv1_3_building', models.CharField(blank=True, max_length=50, null=True)),
                ('pv1_4_admission_type', models.CharField(blank=True, max_length=50, null=True)),
                ('pv1_6_hospital', models.CharField(blank=True, max_length=50, null=True)),
                ('pv1_6_ward', models.CharField(blank=True, max_length=50, null=True)),
                ('pv1_6_room', models.CharField(blank=True, max_length=50, null=True)),
                ('pv1_6_bed', models.CharField(blank=True, max_length=50, null=True)),
                ('pv1_7_consultant_code', models.CharField(blank=True, max_length=50, null=True)),
                ('consultant_name', models.CharField(blank=True, max_length=50, null=True)),
                ('pv1_10_speciality_code', models.CharField(blank=True, max_length=50, null=True)),
                ('speciality_name', models.CharField(blank=True, max_length=50, null=True)),
                ('pv1_14_admission_source', models.CharField(blank=True, max_length=50, null=True)),
                ('pv1_18_visit_patient_type_original', models.CharField(blank=True, max_length=50, null=True)),
                ('pv1_18_visit_patient_type_product', models.CharField(blank=True, max_length=50, null=True)),
                ('pv1_19_hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('pv1_41_account_status', models.CharField(blank=True, max_length=50, null=True)),
                ('pd1_3_practice_code', models.CharField(blank=True, max_length=50, null=True)),
                ('pd1_4_national_code', models.CharField(blank=True, max_length=50, null=True)),
                ('pv1_44_admit_date_time', models.DateTimeField(blank=True, null=True)),
                ('pv1_45_discharge_date_time', models.DateTimeField(blank=True, null=True)),
                ('pv2_2_patient_type', models.CharField(blank=True, max_length=50, null=True)),
                ('fin_hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('insert_date', models.DateTimeField(blank=True, null=True)),
                ('parent_mrn', models.CharField(blank=True, max_length=20, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='opal.Patient')),
            ],
        ),
    ]
