# Generated by Django 2.0.13 on 2021-04-21 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        ('admissions', '0003_auto_20210329_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpstreamLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(blank=True, max_length=50, null=True)),
                ('building', models.CharField(blank=True, max_length=50, null=True)),
                ('ward', models.CharField(blank=True, max_length=50, null=True)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('bed', models.CharField(blank=True, max_length=50, null=True)),
                ('admitted', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upstreamlocation', to='opal.Patient')),
            ],
        ),
    ]
