# Generated by Django 2.0.13 on 2021-04-23 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_transferhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreamlocation',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter', to='admissions.Encounter'),
        ),
    ]
