# Generated by Django 2.0.13 on 2021-05-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_upstreamlocation_encounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferhistory',
            name='mrn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transferhistory',
            name='spell_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
