# Generated by Django 2.0.13 on 2021-05-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_auto_20210511_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferhistory',
            name='spell_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
