# Generated by Django 2.0.13 on 2021-07-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_auto_20210511_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferhistory',
            options={'ordering': ['transfer_sequence_number']},
        ),
    ]
