# Generated by Django 2.0.13 on 2021-11-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_auto_20210720_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(blank=True, max_length=255, null=True)),
                ('building', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_site_code', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_site_description', models.CharField(blank=True, max_length=255, null=True)),
                ('ward_name', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.CharField(blank=True, max_length=255, null=True)),
                ('room_gender', models.CharField(blank=True, max_length=255, null=True)),
                ('bed', models.CharField(blank=True, max_length=255, null=True)),
                ('bed_status', models.CharField(blank=True, max_length=255, null=True)),
                ('isolation_description', models.CharField(blank=True, max_length=255, null=True)),
                ('encounter_id', models.CharField(blank=True, max_length=255, null=True)),
                ('encounter_type_description', models.CharField(blank=True, max_length=255, null=True)),
                ('person_id', models.CharField(blank=True, max_length=255, null=True)),
                ('spell_number', models.CharField(blank=True, max_length=255, null=True)),
                ('local_patient_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('nhs_number', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_date_time', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_method_code', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_method_description', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_classification_code', models.CharField(blank=True, max_length=255, null=True)),
                ('main_specialty_code', models.CharField(blank=True, max_length=255, null=True)),
                ('main_specialty_description', models.CharField(blank=True, max_length=255, null=True)),
                ('treatment_function_code', models.CharField(blank=True, max_length=255, null=True)),
                ('treatment_function_description', models.CharField(blank=True, max_length=255, null=True)),
                ('pod', models.CharField(blank=True, max_length=255, null=True)),
                ('pod_description', models.CharField(blank=True, max_length=255, null=True)),
                ('division_patient', models.CharField(blank=True, max_length=255, null=True)),
                ('division_ward', models.CharField(blank=True, max_length=255, null=True)),
                ('covid19_flag', models.CharField(blank=True, max_length=255, null=True)),
                ('side_room_flag', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
