# Generated by Django 2.0.13 on 2021-11-26 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        ('admissions', '0011_bedstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedstatus',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bedstatus', to='opal.Patient'),
        ),
    ]
