# Generated by Django 2.0.13 on 2021-12-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_transferhistory_created_in_elcid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferhistory',
            name='encounter_slice_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
