# Generated by Django 2.2.16 on 2021-12-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_bedstatus_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsolatedBed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_site_code', models.CharField(blank=True, max_length=255, null=True)),
                ('ward_name', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.CharField(blank=True, max_length=255, null=True)),
                ('bed', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
