# Generated by Django 2.2.16 on 2021-12-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_bedstatus_patient'),
        ('admissions', '0012_auto_20211202_1801'),
    ]

    operations = [
    ]
