# Generated by Django 2.2.16 on 2021-12-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_bedstatus_patient'),
        ('admissions', '0011_transferhistory_created_in_elcid'),
    ]

    operations = [
    ]
