# Generated by Django 2.2.16 on 2022-01-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_isolatedbed'),
        ('admissions', '0013_merge_20211208_1512'),
    ]

    operations = [
    ]
