# Generated by Django 2.2.16 on 2021-12-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_merge_20211202_1717'),
        ('admissions', '0012_auto_20211202_1801'),
    ]

    operations = [
    ]
