# Generated by Django 2.2.16 on 2022-12-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0015_transferhistory_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferhistory',
            name='active_transfer_sequence_number',
        ),
        migrations.RemoveField(
            model_name='transferhistory',
            name='created_datetime',
        ),
        migrations.AddField(
            model_name='transferhistory',
            name='spell_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferhistory',
            name='spell_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferhistory',
            name='trans_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferhistory',
            name='trans_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
