# Generated by Django 2.2.16 on 2026-06-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0016_auto_20221213_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferhistory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
