# Generated by Django 2.0.13 on 2021-06-24 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0002_auto_20210329_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='imaging',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
