IMAGING_LOAD_TIME_FACT = "IMAGING_LOAD_TIME_FACT"
IMAGING_LOAD_CREATED_COUNT_FACT = "IMAGING_LOAD_CREATED_COUNT_FACT"
IMAGING_LOAD_PATIENT_COUNT_FACT = "IMAGING_LOAD_PATIENT_COUNT_FACT"
IMAGING_COUNT_FACT = "IMAGING_COUNT_FACT"
