# Generated by Django 2.0.9 on 2019-02-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0009_auto_20190211_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeObservationWithExtras',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('lab.observation',),
        ),
    ]
