# Generated by Django 2.2.16 on 2022-01-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epma', '0002_auto_20211012_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epmamedorderdetail',
            name='action_sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='epmamedorderdetail',
            name='detail_sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
