# Generated by Django 2.2.16 on 2025-06-03 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epma', '0004_auto_20250602_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epmamedorder',
            name='action_sequence',
        ),
        migrations.RemoveField(
            model_name='epmamedorder',
            name='detail_sequence',
        ),
        migrations.RemoveField(
            model_name='epmamedorder',
            name='oe_field_display_value',
        ),
        migrations.RemoveField(
            model_name='epmamedorder',
            name='oe_field_dt_tm_value',
        ),
        migrations.RemoveField(
            model_name='epmamedorder',
            name='oe_field_id',
        ),
        migrations.RemoveField(
            model_name='epmamedorder',
            name='oe_field_meaning',
        ),
        migrations.RemoveField(
            model_name='epmamedorder',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='epmamedorder',
            name='updt_dt_tm',
        ),
        migrations.AddField(
            model_name='epmamedorderdetail',
            name='action_sequence',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='epmamedorderdetail',
            name='detail_sequence',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='epmamedorderdetail',
            name='epmamedorder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='epma.EPMAMedOrder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='epmamedorderdetail',
            name='load_dt_tm',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epmamedorderdetail',
            name='oe_field_display_value',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='epmamedorderdetail',
            name='oe_field_dt_tm_value',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epmamedorderdetail',
            name='oe_field_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='epmamedorderdetail',
            name='oe_field_meaning',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='epmamedorderdetail',
            name='order_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='epmamedorderdetail',
            name='updt_dt_tm',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
