# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-17 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opal', '0034_auto_20171214_1845'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('drinking', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Alcohol')),
                ('alcohol_dependent', models.NullBooleanField()),
                ('smoking', models.CharField(blank=True, max_length=250, null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('homelessness', models.TextField(blank=True, null=True)),
                ('intravenous_drug_use', models.CharField(blank=True, max_length=250, null=True)),
                ('incarceration', models.CharField(blank=True, max_length=250, null=True)),
                ('arrival_in_the_uk', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Year of arrival')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tb_socialhistory_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tb_socialhistory_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
