# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-17 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0009_auto_20180217_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecreationalDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='socialhistory',
            old_name='intravenous_drug_use',
            new_name='prison_history',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='incarceration',
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='homelessness_type',
            field=models.CharField(blank=True, choices=[(b'hostel', b'hostel'), (b'sofa surfing', b'sofa surfing'), (b'street', b'street')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='receiving_treatment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='recreational_drug_type_ft',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='recreational_drug_use',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bcg',
            name='bcg_type',
            field=models.CharField(blank=True, choices=[(b'neonatal', b'neonatal'), (b'school', b'school'), (b'other', b'other')], max_length=255, verbose_name=b'Time of BCG'),
        ),
        migrations.AlterField(
            model_name='tbhistory',
            name='tb_type',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Latent', b'Latent'), (b'Unknown', b'Unknown')], max_length=256, null=True, verbose_name=b'TB Type'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='recreational_drug_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tb.RecreationalDrug'),
        ),
    ]
