# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-13 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0034_auto_20171214_1845'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tb', '0022_auto_20180613_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('immigration_concerns', models.BooleanField(default=False)),
                ('immigration_details', models.TextField(blank=True)),
                ('immigration_support_officer', models.TextField(blank=True)),
                ('arrival_in_the_uk', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Year of arrival in the UK')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tb_nationality_subrecords', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tb_nationality_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nationality & Citizenship',
                'verbose_name_plural': 'Nationality & Citizenship',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='immigration',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='immigration',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='immigration',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='arrival_in_the_uk',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='immigration_concerns',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='immigration_concerns_details',
        ),
        migrations.DeleteModel(
            name='Immigration',
        ),
    ]
