# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-24 19:25
from __future__ import unicode_literals

from django.db import migrations
from apps.tb import constants


def forwards(apps, schema_editor):
    Role = apps.get_model(
        'opal', 'Role'
    )
    Role.objects.create(name=constants.TB_ROLE)


def backwards(apps, schema_editor):
    Role = apps.get_model(
        'opal', 'Role'
    )
    Role.objects.filter(name=constants.TB_ROLE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0033_patientconsultation_plan'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
