# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-29 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0037_auto_20190126_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbhistory',
            name='previous_tb_contact',
        ),
    ]
