# Generated by Django 2.0.13 on 2019-06-17 14:58

from django.db import migrations


def forwards(apps, schema_editor):
    TBHistory = apps.get_model(
        'tb', 'TBHistory'
    )
    IndexCase = apps.get_model(
        'tb', 'IndexCase'
    )
    tb_histories = TBHistory.objects.exclude(previous_tb_contact=False)
    for tb_history in tb_histories:
        IndexCase.objects.get_or_create(
            patient=tb_history.patient,
            details=tb_history.previous_tb_contact_details,
            created_by_id=tb_history.updated_by_id
        )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0042_auto_20190617_1458'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
