# Generated by Django 2.0.13 on 2019-06-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0043_auto_20190617_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexcase',
            old_name='index_case_diagnosis_day',
            new_name='diagnosis_day',
        ),
        migrations.RenameField(
            model_name='indexcase',
            old_name='index_case_diagnosis_month',
            new_name='diagnosis_month',
        ),
        migrations.RenameField(
            model_name='indexcase',
            old_name='index_case_diagnosis_year',
            new_name='diagnosis_year',
        ),
    ]
