# Generated by Django 2.0.9 on 2020-02-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0046_auto_20200203_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbhistory',
            options={'verbose_name': 'History Of TB', 'verbose_name_plural': 'TB Histories'},
        ),
    ]
