# Generated by Django 2.0.13 on 2020-02-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0048_auto_20200219_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantouxtest',
            name='date_administered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
