# Generated by Django 2.0.13 on 2021-07-19 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        ('labtests', '0007_add_reported_datetime'),
        ('tb', '0050_auto_20210329_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFBCulture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
                ('site', models.CharField(blank=True, default='', max_length=256)),
                ('lab_number', models.CharField(blank=True, default='', max_length=256)),
                ('test_name', models.CharField(blank=True, default='', max_length=256)),
                ('observation_datetime', models.DateTimeField(blank=True, null=True)),
                ('reported_datetime', models.DateTimeField(blank=True, null=True)),
                ('pending', models.BooleanField()),
                ('positive', models.BooleanField()),
                ('date_of_culture_result', models.DateField(blank=True, null=True)),
                ('tb_comment', models.TextField(blank=True, default='')),
                ('tb_clinical_comment', models.TextField(blank=True, default='')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labtests.Observation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AFBRefLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
                ('site', models.CharField(blank=True, default='', max_length=256)),
                ('lab_number', models.CharField(blank=True, default='', max_length=256)),
                ('test_name', models.CharField(blank=True, default='', max_length=256)),
                ('observation_datetime', models.DateTimeField(blank=True, null=True)),
                ('reported_datetime', models.DateTimeField(blank=True, null=True)),
                ('pending', models.BooleanField()),
                ('positive', models.BooleanField()),
                ('date_of_ref_lib_string', models.CharField(blank=True, default='', max_length=256)),
                ('date_of_ref_lib_report', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labtests.Observation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AFBSmear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
                ('site', models.CharField(blank=True, default='', max_length=256)),
                ('lab_number', models.CharField(blank=True, default='', max_length=256)),
                ('test_name', models.CharField(blank=True, default='', max_length=256)),
                ('observation_datetime', models.DateTimeField(blank=True, null=True)),
                ('reported_datetime', models.DateTimeField(blank=True, null=True)),
                ('pending', models.BooleanField()),
                ('positive', models.BooleanField()),
                ('date_of_microscopy', models.DateField(blank=True, null=True)),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labtests.Observation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TBPCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
                ('site', models.CharField(blank=True, default='', max_length=256)),
                ('lab_number', models.CharField(blank=True, default='', max_length=256)),
                ('test_name', models.CharField(blank=True, default='', max_length=256)),
                ('observation_datetime', models.DateTimeField(blank=True, null=True)),
                ('reported_datetime', models.DateTimeField(blank=True, null=True)),
                ('pending', models.BooleanField()),
                ('positive', models.BooleanField()),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labtests.Observation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
