# Generated by Django 2.0.13 on 2021-05-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        ('tb', '0050_auto_20210329_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_tb_positive_date', models.DateField(blank=True, null=True)),
                ('first_tb_positive_test_type', models.CharField(blank=True, default='', max_length=256)),
                ('first_tb_positive_obs_value', models.CharField(blank=True, default='', max_length=256)),
                ('recent_resulted_tb_date', models.DateField(blank=True, null=True)),
                ('recent_resulted_tb_test_type', models.CharField(blank=True, default='', max_length=256)),
                ('recent_resulted_tb_obs_value', models.CharField(blank=True, default='', max_length=256)),
                ('first_ntm_positive_date', models.DateField(blank=True, null=True)),
                ('first_ntm_positive_test_type', models.CharField(blank=True, default='', max_length=256)),
                ('first_ntm_positive_obs_value', models.CharField(blank=True, default='', max_length=256)),
                ('recent_resulted_ntm_date', models.DateField(blank=True, null=True)),
                ('recent_resulted_ntm_test_type', models.CharField(blank=True, default='', max_length=256)),
                ('recent_resulted_ntm_obs_value', models.CharField(blank=True, default='', max_length=256)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tb_patient', to='opal.Patient')),
            ],
        ),
    ]
