# Generated by Django 2.0.13 on 2021-07-09 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0007_add_reported_datetime'),
        ('opal', '0040_auto_20201007_1346'),
        ('tb', '0050_auto_20210329_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_positive_datetime', models.DateTimeField(blank=True, null=True)),
                ('first_positive_lab_number', models.CharField(blank=True, default='', max_length=256)),
                ('first_positive_site', models.CharField(blank=True, default='', max_length=256)),
                ('first_positive_observation_name', models.CharField(blank=True, default='', max_length=256)),
                ('first_positive_observation_value', models.CharField(blank=True, default='', max_length=256)),
                ('first_positive_culture_datetime', models.DateTimeField(blank=True, null=True)),
                ('first_positive_culture_lab_number', models.CharField(blank=True, default='', max_length=256)),
                ('first_positive_culture_site', models.CharField(blank=True, default='', max_length=256)),
                ('first_positive_culture_observation_value', models.CharField(blank=True, default='', max_length=256)),
                ('first_positive_ref_lab_datetime', models.DateTimeField(blank=True, null=True)),
                ('first_positive_ref_lab_lab_number', models.CharField(blank=True, default='', max_length=256)),
                ('first_positive_ref_lab_site', models.CharField(blank=True, default='', max_length=256)),
                ('first_positive_ref_lab_observation_name', models.CharField(blank=True, default='', max_length=256)),
                ('first_positive_ref_lab_observation_value', models.CharField(blank=True, default='', max_length=256)),
                ('most_recent_datetime', models.DateTimeField(blank=True, null=True)),
                ('most_recent_site', models.CharField(blank=True, default='', max_length=256)),
                ('most_recent_lab_number', models.CharField(blank=True, default='', max_length=256)),
                ('most_recent_observation_name', models.CharField(blank=True, default='', max_length=256)),
                ('most_recent_observation_value', models.CharField(blank=True, default='', max_length=256)),
                ('most_recent_positive', models.NullBooleanField()),
                ('first_tb_appointment_date', models.DateField(blank=True, null=True)),
                ('first_tb_appointment_type', models.CharField(blank=True, default='', max_length=256)),
                ('first_positive_culture_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tb_patient_first_positive_culture', to='labtests.Observation')),
                ('first_positive_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tb_patient_first_positive', to='labtests.Observation')),
                ('first_positive_ref_lab_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tb_patient_first_positive_ref_lab', to='labtests.Observation')),
                ('most_recent_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='most_recent_positive_tb_patient', to='labtests.Observation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
            ],
        ),
    ]
