# Generated by Django 2.0.13 on 2021-07-12 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0007_add_reported_datetime'),
        ('tb', '0051_tbpatient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbpatient',
            name='first_positive_culture_datetime',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='first_positive_datetime',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='first_positive_ref_lab_datetime',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='first_positive_ref_lab_observation_name',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='most_recent_datetime',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='most_recent_lab_number',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='most_recent_observation',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='most_recent_observation_name',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='most_recent_observation_value',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='most_recent_positive',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='most_recent_site',
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='first_positive_culture_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='first_positive_date',
            field=models.DateField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='first_positive_ref_lab_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='first_positive_ref_lab_date_string',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='recent_resulted_culture_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='recent_resulted_culture_lab_number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='recent_resulted_culture_observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tb_patient_recent_positive_culture', to='labtests.Observation'),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='recent_resulted_culture_observation_value',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='recent_resulted_culture_site',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='recent_resulted_date',
            field=models.DateField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='recent_resulted_lab_number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='recent_resulted_observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tb_patient_recent_positive', to='labtests.Observation'),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='recent_resulted_observation_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='recent_resulted_observation_value',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='recent_resulted_ref_lab_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='recent_resulted_ref_lab_date_string',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='recent_resulted_ref_lab_lab_number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='recent_resulted_ref_lab_observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tb_patient_recent_resulted_ref_lab', to='labtests.Observation'),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='recent_resulted_ref_lab_observation_value',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='recent_resulted_ref_lab_site',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='recent_resulted_site',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
