# Generated by Django 2.0.13 on 2021-05-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0051_tbpatient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbpatient',
            name='recent_resulted_ntm_date',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='recent_resulted_ntm_obs_value',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='recent_resulted_ntm_test_type',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='recent_resulted_tb_date',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='recent_resulted_tb_obs_value',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='recent_resulted_tb_test_type',
        ),
    ]
