# Generated by Django 2.0.13 on 2021-07-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        ('labtests', '0007_add_reported_datetime'),
        ('tb', '0051_afbculture_afbreflib_afbsmear_tbpcr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AFBRefLib',
            new_name='AFBRefLab',
        ),
        migrations.RenameField(
            model_name='afbreflab',
            old_name='date_of_ref_lib_report',
            new_name='date_of_ref_lab_report',
        ),
        migrations.RenameField(
            model_name='afbreflab',
            old_name='date_of_ref_lib_string',
            new_name='date_of_ref_lab_string',
        ),
    ]
