# Generated by Django 2.0.13 on 2021-07-12 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0007_add_reported_datetime'),
        ('opal', '0040_auto_20201007_1346'),
        ('tb', '0052_auto_20210712_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFBCulture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=256)),
                ('site', models.CharField(blank=True, default='', max_length=256)),
                ('lab_number', models.CharField(blank=True, default='', max_length=256)),
                ('observation_date', models.DateField(blank=True, null=True)),
                ('significant_date', models.DateField()),
                ('pending', models.BooleanField()),
                ('positive', models.BooleanField()),
                ('date_of_culture_result', models.DateField(blank=True, null=True)),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labtests.Observation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AFBRefLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=256)),
                ('site', models.CharField(blank=True, default='', max_length=256)),
                ('lab_number', models.CharField(blank=True, default='', max_length=256)),
                ('observation_date', models.DateField(blank=True, null=True)),
                ('significant_date', models.DateField()),
                ('pending', models.BooleanField()),
                ('positive', models.BooleanField()),
                ('date_of_ref_lib_string', models.CharField(blank=True, default='', max_length=256)),
                ('date_of_ref_lib_report', models.DateField(blank=True, null=True)),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labtests.Observation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AFBSmear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=256)),
                ('site', models.CharField(blank=True, default='', max_length=256)),
                ('lab_number', models.CharField(blank=True, default='', max_length=256)),
                ('observation_date', models.DateField(blank=True, null=True)),
                ('significant_date', models.DateField()),
                ('pending', models.BooleanField()),
                ('positive', models.BooleanField()),
                ('date_of_microscopy', models.DateField(blank=True, null=True)),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labtests.Observation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=256)),
                ('site', models.CharField(blank=True, default='', max_length=256)),
                ('lab_number', models.CharField(blank=True, default='', max_length=256)),
                ('observation_date', models.DateField(blank=True, null=True)),
                ('significant_date', models.DateField()),
                ('pending', models.BooleanField()),
                ('positive', models.BooleanField()),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labtests.Observation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='first_positive_culture_observation',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='first_positive_observation',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='first_positive_ref_lab_observation',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='recent_resulted_culture_observation',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='recent_resulted_observation',
        ),
        migrations.RemoveField(
            model_name='tbpatient',
            name='recent_resulted_ref_lab_observation',
        ),
        migrations.DeleteModel(
            name='TBPatient',
        ),
    ]
