# Generated by Django 2.0.13 on 2021-07-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0053_remove_afbreflab_date_of_ref_lab_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='infection_control',
            field=models.TextField(blank=True, default=''),
        ),
    ]
