# Generated by Django 2.0.13 on 2021-07-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0053_auto_20210712_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afbculture',
            name='value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='afbreflib',
            name='value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='afbsmear',
            name='value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pcr',
            name='value',
            field=models.TextField(blank=True, default=''),
        ),
    ]
