# Generated by Django 2.0.13 on 2021-07-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0054_auto_20210712_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='actioned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
