# Generated by Django 2.0.13 on 2021-10-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0055_auto_20210722_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='sent_upstream',
            field=models.BooleanField(default=False),
        ),
    ]
