# Generated by Django 2.0.13 on 2021-09-10 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        ('tb', '0055_auto_20210722_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=256)),
                ('lab_number', models.CharField(max_length=256)),
                ('event', models.CharField(max_length=256)),
                ('reported', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
            ],
        ),
    ]
