# Generated by Django 2.0.13 on 2021-08-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        ('tb', '0055_auto_20210722_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFBCultureSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_number', models.CharField(blank=True, max_length=256, null=True)),
                ('smear_positive', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
            ],
        ),
    ]
