# Generated by Django 2.0.13 on 2021-07-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0055_patientconsultation_actioned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afbculture',
            name='observation_date',
        ),
        migrations.RemoveField(
            model_name='afbreflib',
            name='observation_date',
        ),
        migrations.RemoveField(
            model_name='afbsmear',
            name='observation_date',
        ),
        migrations.RemoveField(
            model_name='pcr',
            name='observation_date',
        ),
        migrations.AddField(
            model_name='afbculture',
            name='clinical_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='afbculture',
            name='observation_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afbculture',
            name='reported_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afbculture',
            name='tb_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='afbreflib',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='afbreflib',
            name='observation_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afbreflib',
            name='reported_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afbsmear',
            name='observation_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afbsmear',
            name='reported_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcr',
            name='observation_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcr',
            name='reported_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
