# Generated by Django 2.2.16 on 2022-12-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0056_patientconsultation_sent_upstream'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergies',
            options={},
        ),
        migrations.AddField(
            model_name='accessconsiderations',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='adversereaction',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='allergies',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bcg',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='communinicationconsiderations',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='indexcase',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lymphnodeswellingsite',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mantouxtest',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='nationality',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='otherinvestigation',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tblocation',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tbmanagement',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tbmeta',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='previous_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
