# Generated by Django 2.0.13 on 2021-08-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0056_afbculturesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='afbculturesummary',
            name='culture_positive',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
