# Generated by Django 2.0.13 on 2021-08-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0056_addtomdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtomdt',
            name='site',
            field=models.CharField(blank=True, choices=[('RFH', 'RFH'), ('Barnet', 'Barnet')], max_length=256, null=True),
        ),
    ]
