# Generated by Django 2.0.13 on 2021-08-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0057_addtomdt_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtomdt',
            old_name='add_to_which_mdt',
            new_name='when',
        ),
    ]
