# Generated by Django 2.2.16 on 2022-12-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0057_auto_20221201_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientconsultation',
            options={},
        ),
    ]
