# Generated by Django 2.0.13 on 2021-08-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        ('tb', '0057_afbculturesummary_culture_positive'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AFBCultureSummary',
            new_name='AFBCulturePositiveHistory',
        ),
    ]
