# Generated by Django 2.2.16 on 2022-11-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0057_auto_20221130_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergies',
            name='original_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
