# Generated by Django 2.2.16 on 2022-11-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0058_allergies_original_mrn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergies',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patientconsultation',
            options={},
        ),
    ]
