# Generated by Django 2.2.16 on 2023-04-11 16:31
"""
Copy the Demographics.birth_place free text or foreign key field
onto the TB Nationality model
"""

from django.db import migrations


def migrate_forwards(apps, schema_editor):
    Demographics = apps.get_model(
        'elcid', 'Demographics'
    )
    Nationality = apps.get_model(
        'tb', 'Nationality'
    )
    for demo in Demographics.objects.exclude(birth_place_fk_id=None):
        Nationality.objects.filter(patient_id=demo.patient_id).update(
            birth_place_fk_id=demo.birth_place_fk_id
        )
    for demo in Demographics.objects.exclude(birth_place_ft='').exclude(birth_place_ft=None):
        Nationality.objects.filter(patient_id=demo.patient_id).update(
            birth_place_ft=demo.birth_place_ft
        )

def migrate_backwards(apps, schema_editor):
    Demographics = apps.get_model(
        'elcid', 'Demographics'
    )
    Nationality = apps.get_model(
        'tb', 'Nationality'
    )
    for nat in Nationality.objects.exclude(birth_place_fk_id=None):
        Demographics.objects.filter(patient_id=nat.patient_id).update(
            birth_place_fk_id=nat.birth_place_fk_id
        )
    for nat in Nationality.objects.exclude(birth_place_ft='').exclude(birth_place_ft=None):
        Demographics.objects.filter(patient_id=nat.patient_id).update(
            birth_place_ft=nat.birth_place_ft
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0059_auto_20230411_1627'),
    ]

    operations = [
        migrations.RunPython(
            migrate_forwards, reverse_code=migrate_backwards
        )
    ]
