# Generated by Django 2.2.16 on 2025-03-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0065_auto_20241001_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientconsultation',
            name='discussion',
            field=models.TextField(blank=True),
        ),
    ]
