# Generated by Django 2.2.16 on 2025-03-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0066_ntmhistory'),
        ('tb', '0066_auto_20250312_1123'),
    ]

    operations = [
    ]
