# Generated by Django 2.2.16 on 2025-03-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0067_merge_20250317_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ntmhistory',
            options={'verbose_name': 'NTM History'},
        ),
    ]
