# Generated by Django 2.0.13 on 2020-11-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMTHandover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqlserver_id', models.IntegerField()),
                ('sqlserver_insert_datetime', models.DateTimeField(blank=True, null=True)),
                ('sqlserver_lastupdated_datetime', models.DateTimeField(blank=True, null=True)),
                ('handover_version', models.IntegerField()),
                ('mrn', models.CharField(blank=True, max_length=255, null=True)),
                ('nhs_number', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_surname', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_forename', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_dob', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=255, null=True)),
                ('cerner_visit_id', models.CharField(blank=True, max_length=255, null=True)),
                ('speciality', models.CharField(blank=True, max_length=255, null=True)),
                ('update_user', models.CharField(blank=True, max_length=255, null=True)),
                ('discharged', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('rota', models.CharField(blank=True, max_length=100, null=True)),
                ('actual_location', models.CharField(blank=True, max_length=100, null=True)),
                ('bed_number', models.CharField(blank=True, max_length=100, null=True)),
                ('planned_location', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_added', models.DateTimeField(blank=True, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_other', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_user', models.CharField(blank=True, max_length=255, null=True)),
                ('presenting_complaint', models.CharField(blank=True, max_length=16000, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('shift', models.CharField(blank=True, max_length=100, null=True)),
                ('review_datetime', models.DateTimeField(blank=True, null=True)),
                ('to_be_clerked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('to_be_clerked_by_other', models.CharField(blank=True, max_length=255, null=True)),
                ('clerked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('clerked_by_other', models.CharField(blank=True, max_length=255, null=True)),
                ('clerked_datetime', models.DateTimeField(blank=True, null=True)),
                ('ptwr_datetime', models.DateTimeField(blank=True, null=True)),
                ('ptwr_consultant', models.CharField(blank=True, max_length=255, null=True)),
                ('consultant_diagnosis', models.CharField(blank=True, max_length=16000, null=True)),
                ('management_plan', models.CharField(blank=True, max_length=16000, null=True)),
                ('outcome', models.CharField(blank=True, max_length=16000, null=True)),
                ('discharge_destination', models.CharField(blank=True, max_length=255, null=True)),
                ('outcome_datetime', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amt_handover', to='opal.Patient')),
            ],
        ),
    ]
