# Generated by Django 2.0.13 on 2021-04-07 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handover', '0002_patientamthandoverstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingHandover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqlserver_uniqueid', models.IntegerField()),
                ('database_version', models.IntegerField()),
                ('os_user', models.CharField(blank=True, max_length=255, null=True)),
                ('handover_list_code', models.CharField(blank=True, max_length=255, null=True)),
                ('handover_list_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('sqlserver_insert_datetime', models.DateTimeField(blank=True, null=True)),
                ('sqlserver_lastupdated_datetime', models.DateTimeField(blank=True, null=True)),
                ('patient_mrn', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_surname', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_forename', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_dob', models.CharField(blank=True, max_length=255, null=True)),
                ('ward_code', models.CharField(blank=True, max_length=255, null=True)),
                ('bedno', models.CharField(blank=True, max_length=255, null=True)),
                ('consultant_code', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=16000, null=True)),
                ('clinical_instructions', models.CharField(blank=True, max_length=16000, null=True)),
                ('results_to_be_reviewed', models.CharField(blank=True, max_length=16000, null=True)),
                ('therapy_input_date', models.DateTimeField(blank=True, null=True)),
                ('therapy_input_dietician', models.CharField(blank=True, max_length=16000, null=True)),
                ('therapy_input_ot', models.CharField(blank=True, max_length=16000, null=True)),
                ('therapy_input_pt', models.CharField(blank=True, max_length=16000, null=True)),
                ('therapy_input_slt', models.CharField(blank=True, max_length=16000, null=True)),
                ('therapy_input_neuro', models.CharField(blank=True, max_length=16000, null=True)),
                ('pharmacy_input', models.CharField(blank=True, max_length=16000, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_handover', to='opal.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientNursingHandoverSatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('has_handover', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_handover_patientnursinghandoversatus_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_handover_patientnursinghandoversatus_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
