# Generated by Django 2.0.13 on 2021-04-07 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handover', '0003_nursinghandover_patientnursinghandoversatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientNursingHandoverStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('has_handover', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_handover_patientnursinghandoverstatus_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_handover_patientnursinghandoverstatus_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='patientnursinghandoversatus',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='patientnursinghandoversatus',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientnursinghandoversatus',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='PatientNursingHandoverSatus',
        ),
    ]
