# Generated by Django 2.0.13 on 2021-04-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0004_auto_20210407_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursinghandover',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
