# Generated by Django 2.0.13 on 2020-01-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_auto_20190211_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='resistant_antibiotics',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='sensitive_antibiotics',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='lab_test',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Antimicrobial',
        ),
        migrations.DeleteModel(
            name='DynamicLookupList',
        ),
        migrations.DeleteModel(
            name='DynamicResultChoices',
        ),
        migrations.DeleteModel(
            name='GenericInput',
        ),
        migrations.DeleteModel(
            name='Organism',
        ),
        migrations.DeleteModel(
            name='PendingPosNeg',
        ),
        migrations.DeleteModel(
            name='PosNeg',
        ),
        migrations.DeleteModel(
            name='PosNegEquivicalNotDone',
        ),
        migrations.DeleteModel(
            name='PosNegUnknown',
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
    ]
