# Generated by Django 2.0.13 on 2020-05-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_auto_20190211_1109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organism',
        ),
    ]
