# Generated by Django 2.2.16 on 2022-11-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_delete_organism'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='resistant_antibiotics',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='sensitive_antibiotics',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='lab_test',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Antimicrobial',
        ),
        migrations.DeleteModel(
            name='DynamicLookupList',
        ),
        migrations.DeleteModel(
            name='DynamicResultChoices',
        ),
        migrations.DeleteModel(
            name='GenericInput',
        ),
        migrations.DeleteModel(
            name='PendingPosNeg',
        ),
        migrations.DeleteModel(
            name='PosNeg',
        ),
        migrations.DeleteModel(
            name='PosNegEquivicalNotDone',
        ),
        migrations.DeleteModel(
            name='PosNegUnknown',
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
    ]
