# Generated by Django 2.0.13 on 2021-04-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infectionalert',
            options={'ordering': ['-trigger_datetime']},
        ),
        migrations.AlterField(
            model_name='infectionalert',
            name='category',
            field=models.CharField(choices=[('MRSA', 'MRSA'), ('CPE', 'CPE'), ('DIFF', 'DIFF'), ('TB', 'TB')], max_length=255),
        ),
    ]
