# Generated by Django 2.0.13 on 2021-05-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0003_auto_20210506_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infectionalert',
            name='category',
            field=models.CharField(choices=[('MRSA', 'MRSA'), ('CPE', 'CPE'), ('DIFF', 'DIFF'), ('TB', 'TB'), ('VRE', 'VRE')], max_length=255),
        ),
    ]
