# Generated by Django 2.2.16 on 2022-11-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0006_ipcstatus_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='infectionalert',
            name='original_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ipcstatus',
            name='original_mrn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
