# Generated by Django 2.0.13 on 2021-10-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0006_auto_20210930_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipcstatus',
            options={'verbose_name': 'IPC Portal Status'},
        ),
    ]
