# Generated by Django 2.0.13 on 2021-10-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0007_auto_20211004_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcstatus',
            name='other',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
