# Generated by Django 2.0.13 on 2023-06-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0008_sideroomstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcstatus',
            name='covid_19_lab_numbers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
