# Generated by Django 2.0.13 on 2023-09-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0009_ipcstatus_covid_19_lab_numbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sideroomstatus',
            old_name='admission_organism',
            new_name='problems',
        ),
    ]
