# Generated by Django 2.2.16 on 2025-07-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0011_auto_20230919_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcstatus',
            name='parovirus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipcstatus',
            name='parovirus_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipcstatus',
            name='parovirus_lab_numbers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
