# Generated by Django 2.2.16 on 2025-07-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0012_auto_20250714_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipcstatus',
            old_name='other',
            new_name='other_lab_numbers',
        ),
    ]
