# Generated by Django 2.2.16 on 2025-07-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0013_auto_20250714_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcstatus',
            name='other',
            field=models.BooleanField(default=False),
        ),
    ]
