# Generated by Django 2.2.16 on 2025-07-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0014_ipcstatus_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipcstatus',
            name='reactive',
        ),
        migrations.RemoveField(
            model_name='ipcstatus',
            name='reactive_date',
        ),
        migrations.RemoveField(
            model_name='ipcstatus',
            name='reactive_lab_numbers',
        ),
        migrations.RemoveField(
            model_name='ipcstatus',
            name='vre_neg',
        ),
        migrations.RemoveField(
            model_name='ipcstatus',
            name='vre_neg_date',
        ),
    ]
