# Generated by Django 2.2.16 on 2025-07-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0015_auto_20250714_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcstatus',
            name='norovirus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipcstatus',
            name='norovirus_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipcstatus',
            name='norovirus_lab_numbers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
