# Generated by Django 2.2.16 on 2026-01-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0016_auto_20250714_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('site', models.CharField(max_length=200)),
                ('flag', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
