# Generated by Django 2.2.16 on 2026-08-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0017_flagcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideroomstatus',
            name='occupancy_reason',
            field=models.CharField(blank=True, choices=[('Candida', 'Candida'), ('C diff', 'C diff'), ('CPO', 'CPO'), ('Diarrhoea (a/w result; a/w sample)', 'Diarrhoea (a/w result; a/w sample)'), ('Diarrhoea (with +ve micro result excluding C diff)', 'Diarrhoea (with +ve micro result excluding C diff)'), ('ESBL', 'ESBL'), ('MDR', 'MDR'), ('MRSA', 'MRSA'), ('TB', 'TB'), ('VRE', 'VRE'), ('Covid', 'Covid'), ('Influenza', 'Influenza'), ('RSV', 'RSV'), ('Norovirus/Rotavirus/Sapovirus', 'Norovirus/Rotavirus/Sapovirus'), ('Mpox', 'Mpox'), ('Rhino', 'Rhino'), ('HMPV', 'HMPV'), ('Seasonal Corona', 'Seasonal Corona'), ('Parainfluenza', 'Parainfluenza'), ('Adenovirus', 'Adenovirus'), ('Enterovirus', 'Enterovirus'), ('ParechovirusOther (Micro)', 'ParechovirusOther (Micro)'), ('Other (Viro)', 'Other (Viro)'), ('1:1 behavioral issues', '1:1 behavioral issues'), ('EOL / palliative', 'EOL / palliative'), ('Transplant', 'Transplant')], max_length=225, null=True),
        ),
    ]
