# Generated by Django 2.2.16 on 2026-08-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0018_sideroomstatus_occupancy_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideroomstatus',
            name='occupancy_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sideroomstatus',
            name='occupancy_reason',
            field=models.CharField(blank=True, choices=[('Candida', 'Candida'), ('C diff', 'C diff'), ('CPO', 'CPO'), ('Diarrhoea (a/w result; a/w sample)', 'Diarrhoea (a/w result; a/w sample)'), ('Diarrhoea (with +ve micro result excluding C diff)', 'Diarrhoea (with +ve micro result excluding C diff)'), ('ESBL', 'ESBL'), ('MDR', 'MDR'), ('MRSA', 'MRSA'), ('TB', 'TB'), ('VRE', 'VRE'), ('Other (Micro)', 'Other (Micro)'), ('Adenovirus', 'Adenovirus'), ('Covid', 'Covid'), ('Enterovirus', 'Enterovirus'), ('HMPV', 'HMPV'), ('Influenza', 'Influenza'), ('Mpox', 'Mpox'), ('Norovirus/Rotavirus/Sapovirus', 'Norovirus/Rotavirus/Sapovirus'), ('Parainfluenza', 'Parainfluenza'), ('Parechovirus', 'Parechovirus'), ('Rhino', 'Rhino'), ('RSV', 'RSV'), ('Seasonal Corona', 'Seasonal Corona'), ('Other (Viro)', 'Other (Viro)'), ('1:1 behavioral issues', '1:1 behavioral issues'), ('EOL / palliative', 'EOL / palliative'), ('Transplant', 'Transplant'), ('Clean', 'Clean')], max_length=225, null=True, verbose_name='Reason for occupancy'),
        ),
    ]
