# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-16 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0005_auto_20180211_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbhistory',
            name='how_long_treated_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='how_long_treated_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='how_long_treated_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbhistory',
            name='previous_tb_contact',
            field=models.CharField(blank=True, choices=[(b'Previous TB Diagnosis', b'Previous TB Diagnosis'), (b'Previous TB Contact', b'Previous TB Contact'), (b'None', b'None')], default=b'None', max_length=100),
        ),
    ]
