# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-17 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0008_auto_20180216_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bcg',
            name='date_of_bcg',
        ),
        migrations.RemoveField(
            model_name='bcg',
            name='history_of_bcg',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='telephone',
        ),
        migrations.AddField(
            model_name='bcg',
            name='bcg_type',
            field=models.CharField(blank=True, choices=[(b'neonatal', b'neonatal'), (b'school', b'school'), (b'other', b'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='incarceration',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=b'prison history'),
        ),
    ]
