# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-13 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0034_auto_20171214_1845'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tb', '0011_auto_20180218_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('provisional', models.BooleanField(default=False, help_text=b'True if the allergy is only suspected. Defaults to False.', verbose_name=b'Suspected?')),
                ('details', models.CharField(blank=True, max_length=255)),
                ('drug_ft', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tb_allergies_subrecords', to=settings.AUTH_USER_MODEL)),
                ('drug_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opal.Drug')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tb_allergies_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Allergies',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='destination_fk',
            new_name='country_fk',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='destination_ft',
            new_name='country_ft',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='dates',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='travel',
            name='years',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bcg',
            name='bcg_scar',
            field=models.BooleanField(default=False, verbose_name=b'BCG Scar Seen'),
        ),
        migrations.AlterField(
            model_name='bcg',
            name='bcg_type',
            field=models.CharField(blank=True, choices=[(b'neonatal', b'neonatal'), (b'school', b'school'), (b'adult', b'adult'), (b'unsure', b'unsure'), (b'none', b'none')], max_length=255, verbose_name=b'BCG'),
        ),
        migrations.AlterField(
            model_name='bcg',
            name='red_book_documentation_of_bcg_seen',
            field=models.BooleanField(default=False, verbose_name=b'Red Book Documentation Of BCG Given'),
        ),
    ]
