# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-14 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0012_auto_20180313_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='years',
            new_name='when',
        ),
    ]
