# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-14 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0013_auto_20180314_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcg',
            name='bcg_type',
            field=models.CharField(blank=True, choices=[(b'Neonatal', b'Neonatal'), (b'School', b'School'), (b'Adult', b'Adult'), (b'Unsure', b'Unsure'), (b'None', b'None')], max_length=255, verbose_name=b'BCG'),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='homelessness_type',
            field=models.CharField(blank=True, choices=[(b'Hostel', b'Hostel'), (b'Sofa surfing', b'Sofa surfing'), (b'Street', b'Street')], max_length=256, null=True),
        ),
    ]
