# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-14 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0034_auto_20171214_1845'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tb', '0014_auto_20180314_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantouxTestOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('batch_number', models.CharField(blank=True, default=b'', max_length=256)),
                ('expiry_date', models.DateField()),
                ('induration', models.IntegerField(verbose_name=b'Induration (mm)')),
                ('site', models.CharField(blank=True, choices=[(b'Left Lower Arm', b'Left Lower Arm'), (b'Right Lower Arm', b'Right Lower Arm')], default=b'', max_length=256)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tb_mantouxtestone_subrecords', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tb_mantouxtestone_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantoux(1)',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MantouxTestTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('batch_number', models.CharField(blank=True, default=b'', max_length=256)),
                ('expiry_date', models.DateField()),
                ('induration', models.IntegerField(verbose_name=b'Induration (mm)')),
                ('site', models.CharField(blank=True, choices=[(b'Left Lower Arm', b'Left Lower Arm'), (b'Right Lower Arm', b'Right Lower Arm')], default=b'', max_length=256)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tb_mantouxtesttwo_subrecords', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tb_mantouxtesttwo_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantoux(2)',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
