# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-13 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0024_socialhistory_prison_history_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialhistory',
            name='homelessness_type',
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='drinking',
            field=models.CharField(blank=True, choices=[(b'None', b'None'), (b'Occasional', b'Occasional'), (b'Excess', b'Excess'), (b'Dependent', b'Dependent')], max_length=250, null=True, verbose_name=b'Alcohol'),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='homelessness',
            field=models.CharField(blank=True, choices=[(b'Hostel', b'Hostel'), (b'Sofa surfing', b'Sofa surfing'), (b'Street', b'Street'), (b'Other', b'Other')], max_length=256, null=True),
        ),
    ]
