# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-13 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0025_auto_20180613_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialhistory',
            name='homelessness_type',
            field=models.CharField(blank=True, choices=[(b'Never', b'Never'), (b'Current', b'Current'), (b'Past', b'Past')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='housing_officer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='prison_history_details',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
