# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-15 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0029_auto_20180815_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbappointment',
            options={'verbose_name': 'Appointments'},
        ),
    ]
