# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-15 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0030_auto_20180815_2203'),
        ('tb', '0029_auto_20180815_1338'),
    ]

    operations = [
    ]
