# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-16 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0031_merge_20180815_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbappointment',
            options={'ordering': ['-start'], 'verbose_name': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='tbmanagement',
            options={'verbose_name': 'TB Management'},
        ),
        migrations.AlterField(
            model_name='tbmanagement',
            name='ltbr_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'LTBR Number'),
        ),
    ]
