# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-22 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0032_auto_20180816_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='plan',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
