# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-18 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0035_auto_20181218_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbhistory',
            name='previous_tb_contact',
            field=models.BooleanField(default=False, verbose_name=b'Previous TB contact'),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='previous_tb_diagnosis',
            field=models.BooleanField(default=False, verbose_name=b'Previous TB diagnosis'),
        ),
    ]
