# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-01 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0035_auto_20181001_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbstage',
            options={'verbose_name': 'Current Status'},
        ),
    ]
