# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-26 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0035_auto_20190124_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='assessment',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
