# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-26 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0036_patientconsultation_assessment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbhistory',
            old_name='details',
            new_name='diagnosis_details',
        ),
        migrations.RemoveField(
            model_name='tbhistory',
            name='how_long_ago_days',
        ),
        migrations.RemoveField(
            model_name='tbhistory',
            name='how_long_ago_months',
        ),
        migrations.RemoveField(
            model_name='tbhistory',
            name='how_long_ago_years',
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='contact_details',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='contact_how_long_ago_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='contact_how_long_ago_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='contact_how_long_ago_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='diagnosis_how_long_ago_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='diagnosis_how_long_ago_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='diagnosis_how_long_ago_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='previous_tb_diagnosis',
            field=models.BooleanField(default=False, verbose_name=b'Previous TB diagnosis'),
        ),
        migrations.AlterField(
            model_name='tbhistory',
            name='previous_tb_contact',
            field=models.BooleanField(default=False, verbose_name=b'Previous TB contact'),
        ),
    ]
