# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-22 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0036_auto_20181101_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbhistory',
            name='details',
        ),
        migrations.RemoveField(
            model_name='tbhistory',
            name='how_long_ago_days',
        ),
        migrations.RemoveField(
            model_name='tbhistory',
            name='how_long_ago_months',
        ),
        migrations.RemoveField(
            model_name='tbhistory',
            name='how_long_ago_years',
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='contact_details',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='contact_how_long_ago_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='contact_how_long_ago_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='contact_how_long_ago_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='diagnosis_details',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='diagnosis_how_long_ago_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='diagnosis_how_long_ago_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='diagnosis_how_long_ago_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='previous_tb_diagnosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tbhistory',
            name='previous_tb_contact',
            field=models.BooleanField(default=False),
        ),
    ]
