# Generated by Django 2.0.9 on 2018-12-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0036_auto_20181218_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessconsiderations',
            name='access_assistance',
            field=models.CharField(blank=True, choices=[('provision', 'provision'), ('finance', 'finance')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='allergies',
            name='drug_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allergies',
            name='provisional',
            field=models.BooleanField(default=False, help_text='True if the allergy is only suspected. Defaults to False.', verbose_name='Suspected?'),
        ),
        migrations.AlterField(
            model_name='bcg',
            name='bcg_scar',
            field=models.BooleanField(default=False, verbose_name='BCG Scar Seen'),
        ),
        migrations.AlterField(
            model_name='bcg',
            name='bcg_type',
            field=models.CharField(blank=True, choices=[('Neonatal', 'Neonatal'), ('School', 'School'), ('Adult', 'Adult'), ('Unsure', 'Unsure'), ('None', 'None')], max_length=255, verbose_name='BCG'),
        ),
        migrations.AlterField(
            model_name='bcg',
            name='red_book_documentation_of_bcg_seen',
            field=models.BooleanField(default=False, verbose_name='Red Book Documentation Of BCG Given'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='financial_status',
            field=models.CharField(blank=True, choices=[('Nil income', 'Nil income'), ('On benefits', 'On benefits'), ('Other(SS/NASS)', 'Other(SS/NASS)'), ('Employed', 'Employed')], max_length=256),
        ),
        migrations.AlterField(
            model_name='lymphnodeswellingsite',
            name='site_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mantouxtest',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='mantouxtest',
            name='induration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Induration (mm)'),
        ),
        migrations.AlterField(
            model_name='mantouxtest',
            name='site',
            field=models.CharField(blank=True, choices=[('Left Lower Arm', 'Left Lower Arm'), ('Right Lower Arm', 'Right Lower Arm')], default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='arrival_in_the_uk',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Year of arrival in the UK'),
        ),
        migrations.AlterField(
            model_name='patientconsultation',
            name='assessment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patientconsultation',
            name='initials',
            field=models.CharField(blank=True, help_text='The initials of the user who gave the consult.', max_length=255),
        ),
        migrations.AlterField(
            model_name='patientconsultation',
            name='plan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patientconsultation',
            name='reason_for_interaction_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='community_nurse',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='CPN/CMHT'),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='drinking',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Occasional', 'Occasional'), ('Excess', 'Excess'), ('Dependent', 'Dependent')], max_length=250, null=True, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='drug_community_worker',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Drug/alcohol worker'),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='homelessness',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Current', 'Current'), ('Past', 'Past')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='homelessness_type',
            field=models.CharField(blank=True, choices=[('Hostel', 'Hostel'), ('Sofa surfing', 'Sofa surfing'), ('Street', 'Street'), ('Other', 'Other')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='opiate_replacement_therapy',
            field=models.BooleanField(default=False, verbose_name='on opiate replacement therapy'),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='prison_history',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Current', 'Current'), ('Within the last 5 years', 'Within the last 5 years'), ('Over 5 years ago', 'Over 5 years ago')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='prison_history_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='recreational_drug_type_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='recreational_drug_use',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Current', 'Current'), ('Dependent', 'Dependent'), ('Past', 'Past')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='smoking',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Current', 'Current'), ('Past', 'Past')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tbhistory',
            name='contact_details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tbhistory',
            name='country_treated_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbhistory',
            name='diagnosis_details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tbhistory',
            name='previous_tb_contact',
            field=models.BooleanField(default=False, verbose_name='Previous TB contact'),
        ),
        migrations.AlterField(
            model_name='tbhistory',
            name='previous_tb_diagnosis',
            field=models.BooleanField(default=False, verbose_name='Previous TB diagnosis'),
        ),
        migrations.AlterField(
            model_name='tbhistory',
            name='site_of_tb_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbhistory',
            name='tb_type',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Latent', 'Latent'), ('Unknown', 'Unknown')], max_length=256, null=True, verbose_name='TB Type'),
        ),
        migrations.AlterField(
            model_name='tbhistory',
            name='treatment_centre_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbmanagement',
            name='case_manager_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbmanagement',
            name='ltbr_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='LTBR Number'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='country_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='reason_for_travel_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='drug_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='frequency_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='route_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='start_date',
            field=models.DateField(blank=True, help_text='The date on which the patient began receiving this treatment.', null=True),
        ),
    ]
