# Generated by Django 2.0 on 2018-11-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0036_auto_20181101_1146'),
    ]

    operations = [
    ]
