# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-23 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0036_auto_20181101_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='assessment',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
