# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-23 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0037_auto_20181122_1227'),
        ('tb', '0037_patientconsultation_assessment'),
    ]

    operations = [
    ]
