# Generated by Django 2.0.9 on 2018-12-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0039_auto_20181114_1445'),
        ('tb', '0038_merge_20181123_1409'),
    ]

    operations = [
    ]
