# Generated by Django 2.0.9 on 2018-12-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0039_auto_20181114_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbhistory',
            old_name='details',
            new_name='contact_details',
        ),
        migrations.RenameField(
            model_name='tbhistory',
            old_name='how_long_ago_days',
            new_name='contact_how_long_ago_days',
        ),
        migrations.RenameField(
            model_name='tbhistory',
            old_name='how_long_ago_months',
            new_name='contact_how_long_ago_months',
        ),
        migrations.RenameField(
            model_name='tbhistory',
            old_name='how_long_ago_years',
            new_name='contact_how_long_ago_years',
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='assessment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='diagnosis_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='diagnosis_how_long_ago_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='diagnosis_how_long_ago_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='diagnosis_how_long_ago_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='previous_tb_diagnosis',
            field=models.BooleanField(default=False, verbose_name='Previous TB diagnosis'),
        ),
        migrations.AlterField(
            model_name='tbhistory',
            name='previous_tb_contact',
            field=models.BooleanField(default=False, verbose_name='Previous TB contact'),
        ),
    ]
