# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-17 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0039_auto_20181114_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbhistory',
            old_name='details',
            new_name='contact_details',
        ),
        migrations.RenameField(
            model_name='tbhistory',
            old_name='how_long_ago_days',
            new_name='contact_how_long_ago_days',
        ),
        migrations.RenameField(
            model_name='tbhistory',
            old_name='how_long_ago_months',
            new_name='contact_how_long_ago_months',
        ),
        migrations.RenameField(
            model_name='tbhistory',
            old_name='how_long_ago_years',
            new_name='contact_how_long_ago_years',
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='assessment',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='diagnosis_details',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='diagnosis_how_long_ago_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='diagnosis_how_long_ago_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='diagnosis_how_long_ago_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
