# Generated by Django 2.0.9 on 2019-03-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0040_auto_20190211_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='progress',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patientconsultation',
            name='assessment',
            field=models.TextField(blank=True, default='', verbose_name='Clinical Assessment'),
        ),
    ]
