# Generated by Django 2.0.13 on 2019-04-18 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0037_auto_20181114_1445'),
        ('tb', '0040_auto_20190211_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('details', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tb_adversereaction_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tb_adversereaction_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OtherInvestigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('date', models.DateField(blank=True, null=True)),
                ('details', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tb_otherinvestigation_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tb_otherinvestigation_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='tbhistory',
            options={'verbose_name': 'TB Exposure', 'verbose_name_plural': 'TB Exposures'},
        ),
        migrations.RenameField(
            model_name='patientconsultation',
            old_name='assessment',
            new_name='examination_findings',
        ),
        migrations.RenameField(
            model_name='tbhistory',
            old_name='contact_details',
            new_name='previous_tb_contact_details',
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='progress',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='travel',
            name='additional_exposures',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='treatment',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
