# Generated by Django 2.0.9 on 2018-12-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0040_auto_20181217_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbhistory',
            name='previous_tb_contact',
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='previous_tb_diagnosis',
            field=models.BooleanField(default=False, verbose_name='Previous TB diagnosis'),
        ),
        migrations.AlterField(
            model_name='patientconsultation',
            name='assessment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tbhistory',
            name='diagnosis_details',
            field=models.TextField(default=''),
        ),
    ]
