# Generated by Django 2.0.9 on 2018-12-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0041_auto_20181217_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbhistory',
            name='previous_tb_contact',
            field=models.BooleanField(default=False, verbose_name='Previous TB contact'),
        ),
    ]
