# Generated by Django 2.0.13 on 2019-05-29 09:58

from django.db import migrations


def forwards(apps, schema_editor):
    TBHistory = apps.get_model(
        'tb', 'TBHistory'
    )
    IndexCase = apps.get_model(
        'tb', 'IndexCase'
    )
    tb_histories = TBHistory.objects.exclude(previous_tb_contact=False)
    for tb_history in tb_histories:
        IndexCase.objects.get_or_create(
            patient=tb_history.patient,
            details=previous_tb_contact_details
        )

def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0043_auto_20190529_0937'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
