# Generated by Django 2.0.9 on 2019-03-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0043_otherinvestigation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={'verbose_name': 'TB Treatment'},
        ),
    ]
