# Generated by Django 2.0.9 on 2019-03-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0044_auto_20190318_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbhistory',
            options={'verbose_name': "History of TB or TB contact'", 'verbose_name_plural': 'History of TB'},
        ),
    ]
