# Generated by Django 2.0.13 on 2019-06-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0044_auto_20190529_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexcase',
            old_name='index_case_diagnosis_days',
            new_name='index_case_diagnosis_day',
        ),
        migrations.RenameField(
            model_name='indexcase',
            old_name='index_case_diagnosis_months',
            new_name='index_case_diagnosis_month',
        ),
        migrations.RenameField(
            model_name='indexcase',
            old_name='index_case_diagnosis_years',
            new_name='index_case_diagnosis_year',
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='diagnosis_date_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='diagnosis_date_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbhistory',
            name='diagnosis_date_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
