# Generated by Django 2.0.13 on 2020-02-03 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0045_auto_20190618_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbhistory',
            options={'verbose_name': 'Personal History Of TB', 'verbose_name_plural': 'Personal histories of TB'},
        ),
    ]
