# Generated by Django 2.0.9 on 2019-03-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0045_auto_20190318_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbhistory',
            options={'verbose_name': 'History Of TB Or TB Contact', 'verbose_name_plural': 'History of TB'},
        ),
        migrations.RemoveField(
            model_name='patientconsultation',
            name='assessment',
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='examination_findings',
            field=models.TextField(blank=True, default=''),
        ),
    ]
