# Generated by Django 2.0.9 on 2019-03-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0046_auto_20190318_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbhistory',
            options={'verbose_name': 'TB Exposure', 'verbose_name_plural': 'TB Exposures'},
        ),
    ]
