# Generated by Django 2.0.9 on 2020-02-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0047_auto_20200205_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialhistory',
            old_name='history_of_alocohol_dependence',
            new_name='history_of_alcohol_dependence',
        ),
    ]
