# Generated by Django 2.0.9 on 2019-03-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0048_travel_not_travelled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={},
        ),
        migrations.AddField(
            model_name='treatment',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
