# Generated by Django 2.0.13 on 2019-04-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0050_travel_additional_exposures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='not_travelled',
        ),
    ]
