# Generated by Django 2.0.13 on 2019-04-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0051_remove_travel_not_travelled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbhistory',
            old_name='contact_details',
            new_name='previous_tb_contact_details',
        ),
    ]
