# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0015_auto_20171212_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergies',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='allergies',
            name='drug_fk',
        ),
        migrations.RemoveField(
            model_name='allergies',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='allergies',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='generalnote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='generalnote',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='generalnote',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='microbiologytest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='microbiologytest',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='microbiologytest',
            name='hiv_declined_fk',
        ),
        migrations.RemoveField(
            model_name='microbiologytest',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='pastmedicalhistory',
            name='condition_fk',
        ),
        migrations.RemoveField(
            model_name='pastmedicalhistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pastmedicalhistory',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='pastmedicalhistory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='destination_fk',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='malaria_drug_fk',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='reason_for_travel_fk',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Allergies',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='GeneralNote',
        ),
        migrations.DeleteModel(
            name='Hiv_no',
        ),
        migrations.DeleteModel(
            name='MicrobiologyTest',
        ),
        migrations.DeleteModel(
            name='PastMedicalHistory',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
