# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-15 13:36
from __future__ import unicode_literals

from django.db import migrations


def migrate_forwards(apps, schema_editor):
    LabTest = apps.get_model('lab', "LabTest")
    LabTest.objects.filter(lab_test_type="HL7 Result").update(
        lab_test_type="Upstream Lab Test"
    )


def migrate_backwards(apps, schema_editor):
    LabTest = apps.get_model('lab', "LabTest")
    LabTest.objects.filter(lab_test_type="Upstream Lab Test").update(
        lab_test_type="HL7 Result"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0017_auto_20180108_1614'),
    ]

    operations = [
        migrations.RunPython(
            migrate_forwards, reverse_code=migrate_backwards
        )
    ]
