# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-22 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0017_auto_20180108_1614'),
        ('elcid', '0017_auto_20171212_1614'),
    ]

    operations = [
    ]
