# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-14 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0022_auto_20180314_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralroute',
            name='referral_reason',
            field=models.CharField(blank=True, choices=[(b'Symptomatic', b'Symptomatic'), (b'TB contact screening', b'TB contact screening'), (b'New entract screening', b'New entract screening'), (b'Transferred in TB Rx', b'Transferred in TB Rx'), (b'Anti TNF Treatment', b'Anti TNF Treatment'), (b'BCG Vaccination', b'BCG Vaccination'), (b'Other', b'Other')], default=b'', max_length=256),
        ),
        migrations.AlterField(
            model_name='referralroute',
            name='referral_type',
            field=models.CharField(blank=True, choices=[(b'Primary care (GP)', b'Primary care (GP)'), (b'Primary care (other)', b'Primary care (other)'), (b'Secondary care', b'Secondary care'), (b'TB service', b'TB service'), (b'A&E', b'A&E'), (b'Find & treat', b'Find & treat'), (b'Prison screening', b'Prison screening'), (b'Port Health/HPA', b'Port Health/HPA')], default=b'', max_length=256),
        ),
    ]
