# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-18 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0019_auto_20180615_1045'),
        ('elcid', '0024_gp'),
    ]

    operations = [
    ]
