# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-26 12:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0035_auto_20180806_1150'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elcid', '0025_merge_20180718_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('state', models.CharField(blank=True, default=b'', max_length=256)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('clinic_resource', models.CharField(blank=True, default=b'', max_length=256)),
                ('appointment_type', models.CharField(blank=True, default=b'', max_length=256)),
                ('location', models.CharField(blank=True, default=b'', max_length=256)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_appointment_subrecords', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_appointment_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start'],
                'verbose_name': 'Appointments',
                'verbose_name_plural': 'Appointments',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='finaldiagnosis',
            options={'verbose_name': 'Final Diagnosis', 'verbose_name_plural': 'Final Diagnoses'},
        ),
        migrations.AlterModelOptions(
            name='infection',
            options={'verbose_name': 'Infection Related Issues'},
        ),
        migrations.AlterModelOptions(
            name='microbiologyinput',
            options={'verbose_name': 'Clinical Advice', 'verbose_name_plural': 'Clinical Advice'},
        ),
        migrations.AlterModelOptions(
            name='pastmedicalhistory',
            options={'verbose_name': 'PMH', 'verbose_name_plural': 'Past medical histories'},
        ),
        migrations.AlterModelOptions(
            name='primarydiagnosis',
            options={'verbose_name': 'Primary Diagnosis', 'verbose_name_plural': 'Primary Diagnoses'},
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'verbose_name': 'Operation / Procedures'},
        ),
        migrations.AlterModelOptions(
            name='referralroute',
            options={'verbose_name': 'Referral Route'},
        ),
        migrations.AlterModelOptions(
            name='symptomcomplex',
            options={'verbose_name': 'Symptoms', 'verbose_name_plural': 'Symptom complexes'},
        ),
        migrations.AlterField(
            model_name='referralroute',
            name='referral_type',
            field=models.CharField(blank=True, choices=[(b'Primary care (GP)', b'Primary care (GP)'), (b'Primary care (other)', b'Primary care (other)'), (b'Secondary care', b'Secondary care'), (b'TB service', b'TB service'), (b'A&E', b'A&E'), (b'Find & treat', b'Find & treat'), (b'Prison screening', b'Prison screening'), (b'Port Health/HPA', b'Port Health/HPA'), (b'Private', b'Private')], default=b'', max_length=256),
        ),
    ]
