# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-16 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0026_auto_20180815_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralroute',
            name='referral_type',
            field=models.CharField(blank=True, choices=[(b'Primary care (GP)', b'Primary care (GP)'), (b'Primary care (other)', b'Primary care (other)'), (b'Secondary care', b'Secondary care'), (b'TB service', b'TB service'), (b'A&E', b'A&E'), (b'Find & treat', b'Find & treat'), (b'Prison screening', b'Prison screening'), (b'Port Health/HPA', b'Port Health/HPA'), (b'Private', b'Private')], default=b'', max_length=256),
        ),
    ]
