# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-24 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0026_auto_20190124_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='medical_procedure_fk',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='medical_procedure_ft',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='surgical_procedure_fk',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='surgical_procedure_ft',
        ),
        migrations.AddField(
            model_name='procedure',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MedicalProcedure',
        ),
        migrations.DeleteModel(
            name='SurgicalProcedure',
        ),
    ]
