# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-29 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0026_auto_20181029_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positivebloodculturehistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='positivebloodculturehistory',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='positivebloodculturehistory',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='PositiveBloodCultureHistory',
        ),
    ]
