# Generated by Django 2.0.9 on 2018-12-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0027_auto_20181218_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='medical_procedure_fk',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='medical_procedure_ft',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='surgical_procedure_fk',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='surgical_procedure_ft',
        ),
        migrations.AddField(
            model_name='procedure',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
