# Generated by Django 2.0.9 on 2019-03-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0028_auto_20190211_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralroute',
            name='referral_reason',
            field=models.CharField(blank=True, choices=[('Symptomatic', 'Symptomatic'), ('TB contact screening', 'TB contact screening'), ('New entrant screening', 'New entrant screening'), ('Transferred in TB Rx', 'Transferred in TB Rx'), ('Immunosuppressant', 'Immunosuppressant'), ('BCG Vaccination', 'BCG Vaccination'), ('Other', 'Other')], default='', max_length=256),
        ),
    ]
