# Generated by Django 2.0.13 on 2019-04-18 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0037_auto_20181114_1445'),
        ('elcid', '0028_auto_20190211_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='symptomcomplex',
            options={'verbose_name': 'Presenting Symptoms'},
        ),
        migrations.RemoveField(
            model_name='referralroute',
            name='referral_reason',
        ),
        migrations.RemoveField(
            model_name='referralroute',
            name='referral_type',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='category',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='referralroute',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referralroute',
            name='referral_reason_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='referralroute',
            name='referral_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opal.ReferralType'),
        ),
        migrations.AddField(
            model_name='referralroute',
            name='referral_type_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='referralreason',
            unique_together={('code', 'system')},
        ),
        migrations.AddField(
            model_name='referralroute',
            name='referral_reason_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elcid.ReferralReason'),
        ),
    ]
