# Generated by Django 2.0.9 on 2018-12-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0028_auto_20181218_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalProcedure',
        ),
        migrations.DeleteModel(
            name='SurgicalProcedure',
        ),
    ]
