# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-23 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0029_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralroute',
            name='referral_reason',
            field=models.CharField(blank=True, choices=[(b'Symptomatic', b'Symptomatic'), (b'TB contact screening', b'TB contact screening'), (b'New entract screening', b'New entract screening'), (b'Transferred in TB Rx', b'Transferred in TB Rx'), (b'Immunosuppressant', b'Immunosuppressant'), (b'BCG Vaccination', b'BCG Vaccination'), (b'Other', b'Other')], default=b'', max_length=256),
        ),
    ]
