# Generated by Django 2.0.9 on 2018-11-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0029_merge_20181114_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antimicrobial',
            name='adverse_event_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='antimicrobial',
            name='delivered_by_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='antimicrobial',
            name='drug_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='antimicrobial',
            name='frequency_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='antimicrobial',
            name='reason_for_stopping_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='antimicrobial',
            name='route_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='birth_place_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='ethnicity_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='marital_status_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='sex_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='title_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='condition_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finaldiagnosis',
            name='hcai_related',
            field=models.BooleanField(default=False, verbose_name='HCAI related'),
        ),
        migrations.AlterField(
            model_name='imaging',
            name='imaging_type_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='infection',
            name='source_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='complications_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_type_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='removal_reason_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='site_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='category_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='hospital_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='provenance_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='ward_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='microbiologyinput',
            name='liver_function_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='microbiologyinput',
            name='reason_for_interaction_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='microbiologyinput',
            name='renal_function_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pastmedicalhistory',
            name='condition_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='primarydiagnosis',
            name='condition_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='medical_procedure_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='surgical_procedure_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referralroute',
            name='referral_reason',
            field=models.CharField(blank=True, choices=[('Symptomatic', 'Symptomatic'), ('TB contact screening', 'TB contact screening'), ('New entract screening', 'New entract screening'), ('Transferred in TB Rx', 'Transferred in TB Rx'), ('Anti TNF Treatment', 'Anti TNF Treatment'), ('BCG Vaccination', 'BCG Vaccination'), ('Other', 'Other')], default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='referralroute',
            name='referral_type',
            field=models.CharField(blank=True, choices=[('Primary care (GP)', 'Primary care (GP)'), ('Primary care (other)', 'Primary care (other)'), ('Secondary care', 'Secondary care'), ('TB service', 'TB service'), ('A&E', 'A&E'), ('Find & treat', 'Find & treat'), ('Prison screening', 'Prison screening'), ('Port Health/HPA', 'Port Health/HPA'), ('Private', 'Private')], default='', max_length=256),
        ),
    ]
