# Generated by Django 2.0.13 on 2019-03-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0029_auto_20190328_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodcultureisolate',
            name='aerobic',
            field=models.NullBooleanField(default=True),
        ),
    ]
