# Generated by Django 2.0.13 on 2019-06-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0030_auto_20190531_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodcultureset',
            name='date_positive',
        ),
        migrations.AddField(
            model_name='bloodcultureisolate',
            name='date_positive',
            field=models.DateField(blank=True, null=True),
        ),
    ]
