# Generated by Django 2.0.9 on 2019-03-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0030_auto_20190318_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='category',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
