# Generated by Django 2.0.9 on 2018-12-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0031_auto_20181114_1445'),
        ('elcid', '0029_appointment'),
    ]

    operations = [
    ]
