# Generated by Django 2.0.13 on 2019-04-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0031_auto_20190423_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodcultureisolate',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
