# Generated by Django 2.0.13 on 2019-06-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0031_auto_20190603_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
