# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-14 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0031_auto_20181214_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalProcedure',
        ),
        migrations.DeleteModel(
            name='SurgicalProcedure',
        ),
    ]
