# Generated by Django 2.0.13 on 2019-04-23 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0032_auto_20190423_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodcultureisolate',
            name='blood_culture_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='isolates', to='elcid.BloodCultureSet'),
        ),
    ]
