# Generated by Django 2.0.13 on 2020-03-02 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0037_auto_20181114_1445'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elcid', '0032_auto_20190617_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicAntifungal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, choices=[('Dispensary report', 'Dispensary report'), ('Reason for interaction', 'Reason for interaction')], null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRiskFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('date', models.DateField(blank=True, null=True)),
                ('risk_factor_ft', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_riskfactor_subrecords', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
                ('risk_factor_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elcid.PatientRiskFactor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_riskfactor_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk Factors',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='antimicrobial',
            options={'verbose_name': 'Anti-Infectives'},
        ),
        migrations.AddField(
            model_name='antimicrobial',
            name='indication',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='antimicrobial',
            name='treatment_reason',
            field=models.CharField(blank=True, choices=[('Empiric', 'Empiric'), ('Targetted', 'Targetted'), ('Pre-emptive', 'Pre-emptive')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='antimicrobial',
            name='no_antimicrobials',
            field=models.NullBooleanField(default=False, verbose_name='No anti-infectives'),
        ),
        migrations.AlterUniqueTogether(
            name='patientriskfactor',
            unique_together={('code', 'system')},
        ),
    ]
