# Generated by Django 2.0.13 on 2019-04-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0032_auto_20190401_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralroute',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
