# Generated by Django 2.0.13 on 2020-02-17 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0037_auto_20181114_1445'),
        ('elcid', '0032_auto_20190617_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicAntifungal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, choices=[('drug_list', 'drug_list'), ('Reason for interaction', 'Reason for interaction')], null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
            ],
        ),
    ]
