# Generated by Django 2.0.9 on 2020-03-23 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0037_auto_20181114_1445'),
        ('elcid', '0032_auto_20190617_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICUAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('apache_score', models.CharField(blank=True, max_length=200, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('Survived', 'Survived'), ('Atributable Death', 'Atributable Death'), ('Non-attributable Death', 'Non-attributable Death')], max_length=200, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_icuadmission_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_icuadmission_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ICU Admisssion',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
