# Generated by Django 2.0.13 on 2020-01-16 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0032_auto_20190617_2132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organism',
        ),
    ]
