# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0032_auto_20151207_0856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkpoints_assay',
        ),
        migrations.RemoveField(
            model_name='checkpointsassay',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='checkpointsassay',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='checkpointsassay',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='labspecimin',
            name='appearance_fk',
        ),
        migrations.RemoveField(
            model_name='labspecimin',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='labspecimin',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='labspecimin',
            name='specimin_type_fk',
        ),
        migrations.RemoveField(
            model_name='labspecimin',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='antimicrobials_intermediate_fk',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='antimicrobials_resistant_fk',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='antimicrobials_susceptible_fk',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='organism_details_fk',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='LabtestDetails',
        ),
        migrations.RemoveField(
            model_name='ridrtistudydiagnosis',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ridrtistudydiagnosis',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='ridrtistudydiagnosis',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='ridrtitest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ridrtitest',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='ridrtitest',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Antimicrobial_susceptability',
        ),
        migrations.DeleteModel(
            name='CheckpointsAssay',
        ),
        migrations.DeleteModel(
            name='LabSpecimin',
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
        migrations.DeleteModel(
            name='Organism_details',
        ),
        migrations.DeleteModel(
            name='RidRTIStudyDiagnosis',
        ),
        migrations.DeleteModel(
            name='RidRTITest',
        ),
        migrations.DeleteModel(
            name='Specimin',
        ),
        migrations.DeleteModel(
            name='Specimin_appearance',
        ),
    ]
