# Generated by Django 2.0.13 on 2019-04-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0033_referralroute_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symptomcomplex',
            options={'verbose_name': 'Presenting Symptoms'},
        ),
    ]
