# Generated by Django 2.0.13 on 2019-05-04 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0033_bloodcultureisolate_blood_culture_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodcultureisolate',
            name='gram_stains',
        ),
        migrations.AddField(
            model_name='bloodcultureisolate',
            name='gram_stain_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elcid.GramStainOutcome'),
        ),
        migrations.AddField(
            model_name='bloodcultureisolate',
            name='gram_stain_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bloodcultureisolate',
            name='resistances',
            field=models.ManyToManyField(blank=True, related_name='resistant_isolates', to='opal.Antimicrobial'),
        ),
        migrations.AlterField(
            model_name='bloodcultureisolate',
            name='sensitivities',
            field=models.ManyToManyField(blank=True, related_name='sensitive_isolates', to='opal.Antimicrobial'),
        ),
    ]
