# Generated by Django 2.0.13 on 2020-02-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0033_chronicantifungal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronicantifungal',
            name='reason',
            field=models.TextField(blank=True, choices=[('Dispensary report', 'Dispensary report'), ('Reason for interaction', 'Reason for interaction')], null=True),
        ),
    ]
