# Generated by Django 2.0.9 on 2020-03-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0033_icuadmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icuadmission',
            options={'verbose_name': 'ICU Admission'},
        ),
    ]
