# Generated by Django 2.0.13 on 2020-02-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0033_auto_20200228_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antimicrobial',
            options={'verbose_name': 'Anti-Infectives'},
        ),
        migrations.AlterField(
            model_name='antimicrobial',
            name='no_antimicrobials',
            field=models.NullBooleanField(default=False, verbose_name='No anti-infectives'),
        ),
    ]
