# Generated by Django 2.0.13 on 2019-05-08 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elcid', '0034_auto_20190504_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodcultureisolate',
            name='consistency_token',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodcultureisolate',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodcultureisolate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_bloodcultureisolate_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodcultureisolate',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodcultureisolate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_bloodcultureisolate_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bloodcultureisolate',
            name='blood_culture_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='isolates', to='elcid.BloodCultureSet'),
            preserve_default=False,
        ),
    ]
