# Generated by Django 2.0.9 on 2020-03-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0034_auto_20200323_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icuadmission',
            name='outcome',
            field=models.CharField(blank=True, choices=[('Survived', 'Survived'), ('Covid-19 Atributable Death', 'Covid-19 Atributable Death'), ('Covid-19 Non-attributable Death', 'Covid-19 Non-attributable Death')], max_length=200, null=True),
        ),
    ]
