# Generated by Django 2.0.13 on 2020-02-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0034_auto_20200228_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='antimicrobial',
            name='indication',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='antimicrobial',
            name='treatment_reason',
            field=models.CharField(blank=True, choices=[('Empiric', 'Empiric'), ('Targetted', 'Targetted'), ('Pre-emptive', 'Pre-emptive')], max_length=256, null=True),
        ),
    ]
