# Generated by Django 2.0.13 on 2020-03-26 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0037_auto_20181114_1445'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obs', '0004_auto_20181114_1424'),
        ('elcid', '0034_auto_20200323_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICURound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('when', models.DateTimeField(blank=True, null=True)),
                ('ventilated', models.NullBooleanField()),
                ('ventilation_type', models.CharField(blank=True, choices=[('NIV', 'NIV'), ('Intubated', 'Intubated')], max_length=200, null=True)),
                ('fio2', models.CharField(blank=True, max_length=200, null=True)),
                ('inotropic_dose', models.CharField(blank=True, max_length=200, null=True)),
                ('meld_score', models.CharField(blank=True, max_length=200, null=True)),
                ('sofa_score', models.CharField(blank=True, max_length=200, null=True)),
                ('inotropic_drug_ft', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_icuround_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
            ],
            options={
                'verbose_name': 'ICU Round',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InteropicDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MicroInputICURoundRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icu_round', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elcid.ICURound')),
                ('microbiology_input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elcid.MicrobiologyInput')),
                ('observation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obs.Observation')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='interopicdrug',
            unique_together={('code', 'system')},
        ),
        migrations.AddField(
            model_name='icuround',
            name='inotropic_drug_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elcid.InteropicDrug'),
        ),
        migrations.AddField(
            model_name='icuround',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_icuround_subrecords', to=settings.AUTH_USER_MODEL),
        ),
    ]
