# Generated by Django 2.0.13 on 2019-05-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0035_auto_20190508_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodcultureset',
            options={'verbose_name': 'Blood Culture'},
        ),
        migrations.RemoveField(
            model_name='bloodcultureisolate',
            name='aerobic',
        ),
        migrations.AddField(
            model_name='bloodcultureisolate',
            name='aerobic_or_anaerobic',
            field=models.CharField(blank=True, choices=[('Aerobic', 'Aerobic'), ('Anaerobic', 'Anaerobic')], max_length=256, null=True),
        ),
    ]
