# Generated by Django 2.0.13 on 2020-03-27 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0035_auto_20200326_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icuround',
            name='fio2',
            field=models.FloatField(blank=True, max_length=200, null=True, verbose_name='FiO₂'),
        ),
        migrations.AlterField(
            model_name='icuround',
            name='meld_score',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MELD score'),
        ),
        migrations.AlterField(
            model_name='icuround',
            name='sofa_score',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SOFA score'),
        ),
        migrations.AlterField(
            model_name='microinputicuroundrelation',
            name='icu_round',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elcid.ICURound'),
        ),
        migrations.AlterField(
            model_name='microinputicuroundrelation',
            name='microbiology_input',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elcid.MicrobiologyInput'),
        ),
        migrations.AlterField(
            model_name='microinputicuroundrelation',
            name='observation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obs.Observation'),
        ),
    ]
