# Generated by Django 2.0.13 on 2019-05-26 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0037_auto_20181114_1445'),
        ('elcid', '0036_auto_20190508_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodcultureisolate',
            old_name='resistances',
            new_name='resistance',
        ),
        migrations.AddField(
            model_name='bloodcultureisolate',
            name='sepsityper_organism_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sepsityper_organism', to='opal.Microbiology_organism'),
        ),
        migrations.AddField(
            model_name='bloodcultureisolate',
            name='sepsityper_organism_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bloodcultureisolate',
            name='aerobic_or_anaerobic',
            field=models.CharField(blank=True, choices=[('Aerobic', 'Aerobic'), ('Anaerobic', 'Anaerobic')], max_length=256, null=True, verbose_name='Blood culture bottle type'),
        ),
    ]
