# Generated by Django 2.0.13 on 2019-05-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0037_auto_20190526_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodcultureset',
            options={'verbose_name': 'Blood Cultures'},
        ),
    ]
