# Generated by Django 2.0.9 on 2020-04-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0039_auto_20200406_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationCategory',
        ),
        migrations.RemoveField(
            model_name='location',
            name='category_fk',
        ),
        migrations.RemoveField(
            model_name='location',
            name='category_ft',
        ),
    ]
