# Generated by Django 2.0.9 on 2020-04-07 11:10

from django.db import migrations, models
import elcid.models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0040_auto_20200407_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positivebloodculturehistory',
            name='when',
            field=models.DateTimeField(default=elcid.models.now),
        ),
    ]
