# Generated by Django 2.0.9 on 2020-04-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0040_auto_20200407_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icuround',
            name='fio2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='FiO₂'),
        ),
    ]
