# Generated by Django 2.0.9 on 2020-04-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0042_auto_20200407_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icuround',
            name='inotropic',
        ),
        migrations.RemoveField(
            model_name='icuround',
            name='ventilated',
        ),
    ]
