# Generated by Django 2.0.9 on 2020-04-20 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0045_auto_20200408_0944'),
        ('elcid', '0033_auto_20200302_1041'),
    ]

    operations = [
    ]
