# Generated by Django 2.0.13 on 2020-05-18 17:47

from django.db import migrations


def forwards(apps, schema_editor):
    # copy all ft_or_fk fields that were linking to opal Microbiology_organism
    # into the _ft fields
    BloodCultureIsolate = apps.get_model(
        'elcid', 'BloodCultureIsolate'
    )
    sepsityper_isolates = list(BloodCultureIsolate.objects.filter(
        sepsityper_organism_fk_id__isnull=False
    ))

    organism_isolates = list(BloodCultureIsolate.objects.filter(
        organism_fk_id__isnull=False
    ))
    isolates = list(set(sepsityper_isolates + organism_isolates))
    for isolate in isolates:
        if isolate.sepsityper_organism_fk_id:
            isolate.sepsityper_organism_ft = isolate.sepsityper_organism_fk.name
        if isolate.organism_fk_id:
            isolate.organism_ft = isolate.organism_fk.name
        isolate.save()


def backwards(apps, schema_editor):
    BloodCultureIsolate = apps.get_model(
        'elcid', 'BloodCultureIsolate'
    )
    MicrobiologyOrganism = apps.get_model(
        'opal', 'Microbiology_organism'
    )
    for isolate in BloodCultureIsolate.objects.all():
        sepsityper_organism = None
        organism = None

        sepsityper_organism = MicrobiologyOrganism.objects.filter(
            name=isolate.sepsityper_organism_ft
        ).first()

        if sepsityper_organism:
            isolate.sepsityper_organism_fk_id = sepsityper_organism.id
            isolate.sepsityper_organism_ft = ""

        organism = MicrobiologyOrganism.objects.filter(
            name=isolate.organism_ft
        ).first()

        if organism:
            isolate.organism_fk_id = organism.id
            isolate.organism_ft = ""

        if sepsityper_organism or organism:
            isolate.save()


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0048_auto_20200518_1456'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
