# Generated by Django 2.0.13 on 2020-05-18 17:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0049_auto_20200518_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodcultureisolate',
            name='organism_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elcid.MicrobiologyOrganism'),
        ),
        migrations.AlterField(
            model_name='bloodcultureisolate',
            name='sepsityper_organism_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sepsityper_organism', to='elcid.MicrobiologyOrganism'),
        ),
    ]
