# Generated by Django 2.0.13 on 2020-05-18 17:58

from django.db import migrations


def forwards(apps, schema_editor):
    # The fk of the ft or fk fields that were pointing to
    # Opal Microbiology_organism have now been updated to point
    # to their Elcid counterparts.
    # Move the data temporarily stored in _ft back into _fk.
    BloodCultureIsolate = apps.get_model(
        'elcid', 'BloodCultureIsolate'
    )
    MicrobiologyOrganism = apps.get_model(
        'elcid', 'MicrobiologyOrganism'
    )
    for isolate in BloodCultureIsolate.objects.all():
        sepsityper_organism = None
        organism = None
        if isolate.sepsityper_organism_ft:
            sepsityper_organism = MicrobiologyOrganism.objects.filter(
                name__iexact=isolate.sepsityper_organism_ft
            ).first()
            if sepsityper_organism:
                isolate.sepsityper_organism_fk_id = sepsityper_organism.id
                isolate.sepsityper_organism_ft = ""
        if isolate.organism_ft:
            organism = MicrobiologyOrganism.objects.filter(
                name__iexact=isolate.organism_ft
            ).first()
            if organism:
                isolate.organism_fk_id = organism.id
                isolate.organism_ft = ""

        if organism or sepsityper_organism:
            isolate.save()


def backwards(apps, schema_editor):
    BloodCultureIsolate = apps.get_model(
        'elcid', 'BloodCultureIsolate'
    )
    sepsityper_isolates = list(BloodCultureIsolate.objects.filter(
        sepsityper_organism_fk_id__isnull=False
    ))

    organism_isolates = list(BloodCultureIsolate.objects.filter(
        organism_fk_id__isnull=False
    ))
    isolates = list(set(sepsityper_isolates + organism_isolates))
    for isolate in isolates:
        if isolate.sepsityper_organism_fk_id:
            isolate.sepsityper_organism_ft = isolate.sepsityper_organism_fk.name
        if isolate.organism_fk_id:
            isolate.organism_ft = isolate.organism_fk.name
        isolate.save()


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0050_auto_20200518_1757'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
