# Generated by Django 2.0.13 on 2020-05-18 21:04

from django.db import migrations




def forwards(apps, schema_editor):
    """
    Move all ft_or_fk line fields into there _ft option
    """
    Line = apps.get_model(
        'elcid', 'Line'
    )

    for line in Line.objects.all():
        if line.line_type_fk_id or line.complications_fk_id or line.site_fk_id or line.removal_reason_fk_id:
            if line.line_type_fk_id:
                line.line_type_ft = line.line_type_fk.name
            if line.complications_fk_id:
                line.complications_ft = line.complications_fk.name
            if line.site_fk_id:
                line.site_ft = line.site_fk.name
            if line.removal_reason_fk_id:
                line.removal_reason_ft = line.removal_reason_fk.name
            line.save()


def backwards(apps, schema_editor):
    Line = apps.get_model(
        'elcid', 'Line'
    )
    OpalLineType = apps.get_model(
        'opal', 'Line_type'
    )
    OpalLineSite = apps.get_model(
        'opal', 'Line_site'
    )
    OpalLineComplication = apps.get_model(
        'opal', 'Line_complication'
    )
    OpalLineRemovalReason = apps.get_model(
        'opal', 'Line_removal_reason'
    )
    for line in Line.objects.all():
        line_type = OpalLineType.objects.filter(name=line.line_type_ft).first()
        line_site = OpalLineSite.objects.filter(name=line.site_ft).first()
        line_complication = OpalLineComplication.objects.filter(name=line.complications_ft).first()
        line_removal_reason = OpalLineRemovalReason.objects.filter(name=line.removal_reason_ft).first()
        if line_type:
            line.line_type_fk_id = line_type.id
            line.line_type_ft = ""
        if line_site:
            line.site_fk_id = line_site.id
            line.site_ft = ""
        if line_complication:
            line.complications_fk_id = line_complication.id
            line.complications_ft = ""
        if line_removal_reason:
            line.removal_reason_fk_id = line_removal_reason.id
            line.removal_reason_ft = ""
        line.save()



class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0052_auto_20200518_2059'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
