# Generated by Django 2.0.13 on 2020-05-18 21:12

from django.db import migrations


def forwards(apps, schema_editor):
    # Now that we have migrated the lookup lists
    # from opal.Line_* to elcid.Line* and updated the fk
    # of the fk_or_ft
    # move the ft back into fk if possible
    Line = apps.get_model(
        'elcid', 'Line'
    )
    LineType = apps.get_model(
        'elcid', 'LineType'
    )
    LineSite = apps.get_model(
        'elcid', 'LineSite'
    )
    LineComplication = apps.get_model(
        'elcid', 'LineComplication'
    )
    LineRemovalReason = apps.get_model(
        'elcid', 'LineRemovalReason'
    )
    for line in Line.objects.all():
        line_type = LineType.objects.filter(name=line.line_type_ft).first()
        line_site = LineSite.objects.filter(name=line.site_ft).first()
        line_complication = LineComplication.objects.filter(name=line.complications_ft).first()
        line_removal_reason = LineRemovalReason.objects.filter(name=line.removal_reason_ft).first()
        if line_type:
            line.line_type_fk_id = line_type.id
            line.line_type_ft = ""
        if line_site:
            line.site_fk_id = line_site.id
            line.site_ft = ""
        if line_complication:
            line.line_complication_fk_id = line_complication.id
            line.line_complication_ft = ""
        if line_removal_reason:
            line.removal_reason_fk_id = line_removal_reason.id
            line.removal_reason_ft = ""
        line.save()


def backwards(apps, schema_editor):
    Line = apps.get_model(
        'elcid', 'Line'
    )

    for line in Line.objects.all():
        if line.line_type_fk_id:
            line.line_type_ft = line.line_type_fk.name
        if line.site_fk_id:
            line.site_ft = line.site_fk.name
        if line.complications_fk_id:
            line.complications_ft = line.complications_fk.name
        if line.removal_reason_fk_id:
            line.removal_reason_ft = line.removal_reason_fk.name
        line.save()


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0054_auto_20200518_2112'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
