# Generated by Django 2.0.13 on 2020-06-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0056_auto_20200607_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpdetails',
            options={'verbose_name': 'GP'},
        ),
        migrations.AlterModelOptions(
            name='nextofkindetails',
            options={'verbose_name': 'Next Of Kin'},
        ),
    ]
