# Generated by Django 2.0.13 on 2021-01-06 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0057_auto_20200608_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antimicrobial',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='antimicrobial',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='antimicrobial',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_antimicrobial_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='antimicrobial',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='antimicrobial',
            name='treatment_reason',
            field=models.CharField(blank=True, choices=[('Empiric', 'Empiric'), ('Targeted', 'Targeted'), ('Pre-emptive', 'Pre-emptive')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='antimicrobial',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='antimicrobial',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_antimicrobial_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='bloodcultureisolate',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='bloodcultureisolate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_bloodcultureisolate_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='bloodcultureisolate',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='bloodcultureisolate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_bloodcultureisolate_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='bloodcultureset',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='bloodcultureset',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='bloodcultureset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_bloodcultureset_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='bloodcultureset',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='bloodcultureset',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='bloodcultureset',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_bloodcultureset_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='bloodculturesource',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='bloodculturesource',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bloodculturesource',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='bloodculturesource',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_contactinformation_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='external_identifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Extenal Identifier'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='external_system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='External System'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_contactinformation_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_demographics_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='death_indicator',
            field=models.BooleanField(default=False, help_text='This field will be True if the patient is deceased.', verbose_name='Death Indicator'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='external_identifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Extenal Identifier'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='external_system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='External System'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='hospital_number',
            field=models.CharField(blank=True, help_text='The unique identifier for this patient at the hospital.', max_length=255, verbose_name='Demographics'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Post Code'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='surname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_demographics_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_diagnosis_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_diagnosis_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='drug_delivered',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='drug_delivered',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='drug_delivered',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='drug_delivered',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='duplicatepatient',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='duplicatepatient',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='duplicatepatient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_duplicatepatient_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='duplicatepatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='duplicatepatient',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='duplicatepatient',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_duplicatepatient_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='finaldiagnosis',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='finaldiagnosis',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='finaldiagnosis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_finaldiagnosis_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='finaldiagnosis',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='finaldiagnosis',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='finaldiagnosis',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_finaldiagnosis_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='gnroutcome',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='gnroutcome',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='gnroutcome',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='gnroutcome',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='gp',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='gp',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='gp',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_gp_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='gp',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='gp',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='gp',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_gp_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='gpcstaphoutcome',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='gpcstaphoutcome',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='gpcstaphoutcome',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='gpcstaphoutcome',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='gpcstrepoutcome',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='gpcstrepoutcome',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='gpcstrepoutcome',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='gpcstrepoutcome',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='gpdetails',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='gpdetails',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='gpdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_gpdetails_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='gpdetails',
            name='external_identifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Extenal Identifier'),
        ),
        migrations.AlterField(
            model_name='gpdetails',
            name='external_system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='External System'),
        ),
        migrations.AlterField(
            model_name='gpdetails',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='gpdetails',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='gpdetails',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_gpdetails_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='gramstainoutcome',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='gramstainoutcome',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='gramstainoutcome',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='gramstainoutcome',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='icuadmission',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='icuadmission',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='icuadmission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_icuadmission_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='icuadmission',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='icuadmission',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='icuadmission',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_icuadmission_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='icuround',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='icuround',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='icuround',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_icuround_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='icuround',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='icuround',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='icuround',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_icuround_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='imaging',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='imaging',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='imaging',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_imaging_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='imaging',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='imaging',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='imaging',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_imaging_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='imagingtypes',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='imagingtypes',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='imagingtypes',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='imagingtypes',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='infection',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='infection',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='infection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_infection_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='infection',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='infection',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='infection',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_infection_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='infectionsource',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='infectionsource',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='infectionsource',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='infectionsource',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='inotropicdrug',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='inotropicdrug',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='inotropicdrug',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='inotropicdrug',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='iv_stop',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='iv_stop',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='iv_stop',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='iv_stop',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='line',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='line',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='line',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_line_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='line',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='line',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='line',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_line_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='linecomplication',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='linecomplication',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='linecomplication',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='linecomplication',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='lineremovalreason',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='lineremovalreason',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='lineremovalreason',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='lineremovalreason',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='linesite',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='linesite',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='linesite',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='linesite',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='linetype',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='linetype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='linetype',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='linetype',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='liverfunction',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='liverfunction',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='liverfunction',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='liverfunction',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='location',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_location_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='location',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_location_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='microbiologyinput',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='microbiologyinput',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='microbiologyinput',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_microbiologyinput_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='microbiologyinput',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='microbiologyinput',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='microbiologyinput',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_microbiologyinput_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='microbiologyorganism',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='microbiologyorganism',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='microbiologyorganism',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='microbiologyorganism',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='nextofkindetails',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='nextofkindetails',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='nextofkindetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_nextofkindetails_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='nextofkindetails',
            name='external_identifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Extenal Identifier'),
        ),
        migrations.AlterField(
            model_name='nextofkindetails',
            name='external_system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='External System'),
        ),
        migrations.AlterField(
            model_name='nextofkindetails',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='nextofkindetails',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='nextofkindetails',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_nextofkindetails_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='pastmedicalhistory',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='pastmedicalhistory',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='pastmedicalhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_pastmedicalhistory_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='pastmedicalhistory',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='pastmedicalhistory',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='pastmedicalhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_pastmedicalhistory_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='patientriskfactor',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='patientriskfactor',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='patientriskfactor',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='patientriskfactor',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='positivebloodculturehistory',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='positivebloodculturehistory',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='positivebloodculturehistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_positivebloodculturehistory_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='positivebloodculturehistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='positivebloodculturehistory',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='positivebloodculturehistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_positivebloodculturehistory_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='primarydiagnosis',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='primarydiagnosis',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='primarydiagnosis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_primarydiagnosis_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='primarydiagnosis',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='primarydiagnosis',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='primarydiagnosis',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_primarydiagnosis_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='primarydiagnosiscondition',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='primarydiagnosiscondition',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='primarydiagnosiscondition',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='primarydiagnosiscondition',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_procedure_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_procedure_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='quickfishoutcome',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='quickfishoutcome',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='quickfishoutcome',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='quickfishoutcome',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='referralreason',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='referralreason',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='referralreason',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='referralreason',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='referralroute',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='referralroute',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='referralroute',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_referralroute_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='referralroute',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='referralroute',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='referralroute',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_referralroute_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='renalfunction',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='renalfunction',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='renalfunction',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='renalfunction',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='riskfactor',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='riskfactor',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='riskfactor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_riskfactor_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='riskfactor',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='riskfactor',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='riskfactor',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_riskfactor_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='symptomcomplex',
            name='consistency_token',
            field=models.CharField(max_length=8, verbose_name='Consistency Token'),
        ),
        migrations.AlterField(
            model_name='symptomcomplex',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='symptomcomplex',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elcid_symptomcomplex_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='symptomcomplex',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='symptomcomplex',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='symptomcomplex',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elcid_symptomcomplex_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='vasopressor',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='vasopressor',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vasopressor',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='vasopressor',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
    ]
