# Generated by Django 2.0.13 on 2021-09-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0060_infectionservicenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='microbiologyinput',
            name='sent_upstream',
            field=models.BooleanField(default=False),
        ),
    ]
