# Generated by Django 2.0.13 on 2021-07-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        ('elcid', '0060_infectionservicenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='hospital_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opal.Hospital'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='hospital_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='operation',
            field=models.CharField(blank=True, choices=[('Prmary', 'Prmary'), ('Revision', 'Revision'), ('Decompression', 'Decompression'), ('Fixation', 'Fixation')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='side',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('L', 'L')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='site',
            field=models.CharField(blank=True, choices=[('THR', 'THR'), ('TKR', 'TKR'), ('TSR', 'TSR'), ('TER', 'TER'), ('TAR', 'TAR')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='stage',
            field=models.CharField(blank=True, choices=[('Partial', 'Partial'), ('1st stage', '1st stage'), ('Re-do 1st stage', 'Re-do 1st stage'), ('2nd stage', '2nd stage')], max_length=100, null=True),
        ),
    ]
