# Generated by Django 2.2.16 on 2022-01-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0061_microbiologyinput_sent_upstream'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodcultureset',
            name='community',
            field=models.BooleanField(default=False, verbose_name='Community Related'),
        ),
        migrations.AddField(
            model_name='bloodcultureset',
            name='contaminant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloodcultureset',
            name='hcai',
            field=models.BooleanField(default=False, verbose_name='HCAI related'),
        ),
    ]
