# Generated by Django 2.0.13 on 2021-07-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0061_auto_20210725_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='consultant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
