# Generated by Django 2.2.16 on 2022-01-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0061_microbiologyinput_sent_upstream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icuadmission',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='icuadmission',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='icuadmission',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='FinalDiagnosis',
        ),
        migrations.DeleteModel(
            name='ICUAdmission',
        ),
    ]
