# Generated by Django 2.2.16 on 2022-01-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0062_auto_20220120_0934'),
        ('elcid', '0062_auto_20220120_1009'),
    ]

    operations = [
    ]
