# Generated by Django 2.0.13 on 2021-08-13 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        ('elcid', '0062_auto_20210730_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='imaging',
            name='hospital_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opal.Hospital'),
        ),
        migrations.AddField(
            model_name='imaging',
            name='hospital_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
