# Generated by Django 2.0.13 on 2022-03-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0063_merge_20220121_1017'),
        ('elcid', '0063_auto_20210813_1113'),
    ]

    operations = [
    ]
