# Generated by Django 2.0.13 on 2021-09-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0061_microbiologyinput_sent_upstream'),
        ('elcid', '0063_auto_20210813_1113'),
    ]

    operations = [
    ]
