# Generated by Django 2.2.16 on 2021-11-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0063_auto_20210813_1113'),
        ('elcid', '0061_microbiologyinput_sent_upstream'),
    ]

    operations = [
    ]
