# Generated by Django 2.2.16 on 2022-01-24 10:07

from django.db import migrations

ROLE_NAMES = [
    "view_lab_tests_in_list",
    "view_lab_tests_in_detail",
    "view_lab_test_trends",
    "view_lab_test_json_in_detail"
]


def forwards(apps, schema_editor):
    Role = apps.get_model(
        'opal', 'Role'
    )
    Role.objects.filter(name__in=ROLE_NAMES).delete()


def backwards(apps, schema_editor):
    Role = apps.get_model(
        'opal', 'Role'
    )
    UserProfile = apps.get_model(
        'opal.UserProfile'
    )
    roles = []
    for role_name in ROLE_NAMES:
        roles.append(Role.objects.create(name=role_name))

    for user_profile in UserProfile.objects.all():
        user_profile.roles.add(*roles)


class Migration(migrations.Migration):

    dependencies = [
        ("elcid", "0063_merge_20220121_1017"),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
