# Generated by Django 2.2.16 on 2022-11-30 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        ('elcid', '0064_merge_20220311_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMerge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(max_length=256)),
                ('merge_comments', models.TextField(blank=True, default='', null=True)),
                ('upstream_merge_datetime', models.DateTimeField(blank=True, null=True)),
                ('our_merge_datetime', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
            ],
        ),
    ]
