# Generated by Django 2.2.16 on 2022-12-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0065_auto_20221201_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mergedmrn',
            name='created',
        ),
        migrations.RemoveField(
            model_name='mergedmrn',
            name='updated',
        ),
    ]
