# Generated by Django 2.2.16 on 2022-12-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0066_auto_20221201_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergedmrn',
            name='mrn',
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
    ]
