# Generated by Django 2.2.16 on 2022-11-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0066_auto_20221130_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pastmedicalhistory',
            options={},
        ),
    ]
