# Generated by Django 2.2.16 on 2023-03-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0068_remove_mergedmrn_upstream_merge_datetime'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='demographics',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, hospital_number__startswith=0), name='No initial zeros'),
        ),
    ]
