# Generated by Django 2.2.16 on 2023-04-21 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0068_remove_mergedmrn_upstream_merge_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PositiveBloodCultureHistory',
        ),
    ]
