"""
BloodCultureIsolate will no longer have created*/updated* attributes
and instead we will use the BloodCultureSet created*/updated*

If the isolate has been updated more recently than the set, make
sure the set has the most recent data.
"""
# Generated by Django 2.2.16 on 2023-05-10 07:39

from django.db import migrations

def forwards(apps, schema_editor):
    """
    If the isolate has been updated more recently than the blood culture set
    copy the isolates updated/updated_by onto the set.
    """
    BloodCultureIsolate = apps.get_model('elcid', 'BloodCultureIsolate')
    isolates = BloodCultureIsolate.objects.exclude(updated=None).select_related('blood_culture_set')
    for isolate in isolates:
        if isolate.blood_culture_set.updated is None:
            bcs = isolate.blood_culture_set
            bcs.updated = isolate.updated
            bcs.updated_by = isolate.updated_by
            bcs.save()
        elif isolate.updated > isolate.blood_culture_set.updated:
            bcs = isolate.blood_culture_set
            bcs.updated = isolate.updated
            bcs.updated_by = isolate.updated_by
            bcs.save()

def backwards(apps, schema_editor):
    """
    As defaults copy the created*/updated* fields back onto the blood culture
    set.
    """
    BloodCultureSet = apps.get_model('elcid', 'BloodCultureSet')
    for bcs in BloodCultureSet.objects.all():
        bcs.isolates.update(
            created=bcs.created,
            created_by=bcs.created_by,
            updated=bcs.updated,
            updated_by=bcs.updated_by,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0068_remove_mergedmrn_upstream_merge_datetime'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
