# Generated by Django 2.0.13 on 2023-09-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0070_auto_20230510_0750'),
        ('elcid', '0069_delete_positivebloodculturehistory'),
    ]

    operations = [
    ]
