# Generated by Django 2.2.16 on 2025-03-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0072_auto_20240510_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
