# Generated by Django 2.2.16 on 2025-03-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0073_line_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='notes',
        ),
    ]
