# Generated by Django 2.2.16 on 2025-03-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0074_remove_line_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='side',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('L', 'L'), ('Anterior', 'Anterior'), ('Posterior', 'Posterior')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='site',
            field=models.CharField(blank=True, choices=[('THR', 'THR'), ('TKR', 'TKR'), ('TSR', 'TSR'), ('TER', 'TER'), ('TAR', 'TAR'), ('Abdomen', 'Abdomen'), ('Ankle', 'Ankle'), ('Arm', 'Arm'), ('Back', 'Back'), ('Buttock', 'Buttock'), ('Calf', 'Calf'), ('Clavicle', 'Clavicle'), ('C-Spine', 'C-Spine'), ('Ear', 'Ear'), ('Elbow', 'Elbow'), ('Femur', 'Femur'), ('Fibula', 'Fibula'), ('Hip', 'Hip'), ('Humerus', 'Humerus'), ('Ilium Ischium', 'Ilium Ischium'), ('Ischial tuberosity', 'Ischial tuberosity'), ('Knee', 'Knee'), ('Leg', 'Leg'), ('L-Spine', 'L-Spine'), ('Nephrostomy', 'Nephrostomy'), ('Pelvis', 'Pelvis'), ('Pubis', 'Pubis'), ('Radius', 'Radius'), ('Sacrum', 'Sacrum'), ('Shoulder', 'Shoulder'), ('Spine', 'Spine'), ('Suprapubic', 'Suprapubic'), ('Tibia', 'Tibia'), ('Thigh', 'Thigh'), ('Throat', 'Throat'), ('T-spine', 'T-spine'), ('Ulnar', 'Ulnar'), ('Wrist', 'Wrist')], max_length=100, null=True),
        ),
    ]
