# Generated by Django 2.2.16 on 2025-03-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0075_auto_20250315_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='tunnelled_or_temp',
            new_name='central_or_periph',
        ),
    ]
