# Generated by Django 2.2.16 on 2025-03-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0076_auto_20250317_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='total_length',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
