# Generated by Django 2.2.16 on 2025-06-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0077_line_total_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='operation',
            field=models.CharField(blank=True, choices=[('Amputation', 'Amputation'), ('Debridement', 'Debridement'), ('Primary', 'Primary'), ('Revision', 'Revision'), ('Decompression', 'Decompression'), ('Fixation', 'Fixation')], max_length=100, null=True),
        ),
    ]
