# Generated by Django 2.2.16 on 2026-01-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0078_auto_20250603_0643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ('date',), 'verbose_name': 'Operation / Procedures'},
        ),
    ]
