# Generated by Django 2.2.16 on 2025-12-01 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
