# Generated by Django 2.2.16 on 2026-03-11 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20251201_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='state',
            field=models.TextField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN'),
        ),
        migrations.AddField(
            model_name='studyparticipant',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
