# Generated by Django 2.2.16 on 2026-05-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20260311_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyparticipant',
            name='removal_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyparticipant',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
