# Generated by Django 2.2.16 on 2026-05-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20260518_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyparticipant',
            name='removal_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
