# Generated by Django 2.2.16 on 2026-06-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_studyuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyUser',
        ),
    ]
