# Generated by Django 2.2.16 on 2026-06-14 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0008_delete_studyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
