# Generated by Django 2.2.16 on 2026-08-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_study_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name_plural': 'studies'},
        ),
    ]
