# Generated by Django 2.0.13 on 2020-06-10 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0037_auto_20181114_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeMedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_internal_id', models.IntegerField(blank=True, null=True)),
                ('tta_main_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=255, null=True)),
                ('drug_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dose', models.CharField(blank=True, max_length=255, null=True)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('status_comments', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_internal_id', models.IntegerField(blank=True, null=True)),
                ('rf1_number', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_nhs_number', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_forenames', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_surname', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_dob', models.DateTimeField(blank=True, null=True)),
                ('date_of_admission', models.DateTimeField(blank=True, null=True)),
                ('date_of_discharge', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('ward_name', models.CharField(blank=True, max_length=255, null=True)),
                ('consultant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('consultant_department', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_diagnosis', models.TextField(blank=True, null=True)),
                ('ae_diagnosis', models.TextField(blank=True, null=True)),
                ('hsep_problems_diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('hsep_actions', models.CharField(blank=True, max_length=255, null=True)),
                ('other_diagnoses', models.TextField(blank=True, null=True)),
                ('findings', models.TextField(blank=True, null=True)),
                ('procedures', models.TextField(blank=True, null=True)),
                ('investigation_results', models.TextField(blank=True, null=True)),
                ('management', models.TextField(blank=True, null=True)),
                ('future_management', models.TextField(blank=True, null=True)),
                ('allergies', models.CharField(blank=True, max_length=255, null=True)),
                ('letter_type1', models.CharField(blank=True, max_length=255, null=True)),
                ('letter_type2', models.CharField(blank=True, max_length=255, null=True)),
                ('final_letter', models.CharField(blank=True, max_length=255, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dischargesummaries', to='opal.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDischargeSummaryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('has_dischargesummaries', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dischargesummary_patientdischargesummarystatus_subrecords', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dischargesummary_patientdischargesummarystatus_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.AddField(
            model_name='dischargemedication',
            name='discharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='dischargesummary.DischargeSummary'),
        ),
    ]
