# Generated by Django 2.0.13 on 2020-06-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dischargesummary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargesummary',
            name='hsep_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='hsep_problems_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
