# Generated by Django 2.0.13 on 2021-10-15 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dischargesummary', '0003_auto_20210329_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargemedication',
            name='created_in_elcid',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dischargemedication',
            name='last_updated_str',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='created_in_elcid',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='last_updated_str',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dischargemedication',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
