# Generated by Django 2.0.13 on 2021-10-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dischargesummary', '0004_auto_20211015_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dischargemedication',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='dischargesummary',
            name='last_updated',
        ),
    ]
