# Generated by Django 2.0.13 on 2021-10-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dischargesummary', '0005_auto_20211018_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargemedication',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
